import type { Unit } from '../types';

export const c1PresentPerfect: Unit = {
  id: 'c1',
  stage: 'core',
  order: 1,
  title: 'Present perfect simple',
  summary: 'The tense that connects the past to now.',
  level: 'B1',
  errorTags: ['present-perfect-vs-past-simple', 'time-adverbial', 'for-since', 'been-vs-gone'],
  lesson: {
    rule: 'Use the present perfect when the time is unspecified, the period is still open, or the past action still matters now; as soon as you name a finished moment, you must switch to the past simple.',
    schema: [
      { label: 'Form', value: 'have / has + past participle (third column)' },
      { label: 'Unspecified time', value: 'Tim has bought a new car (when? we are not saying)' },
      { label: 'Unfinished period', value: 'We have worked hard today' },
      { label: 'Past action, present result', value: 'She has gone out (so she is not here)' },
      { label: 'First time ever', value: 'This is the first time I have been camping' },
      { label: 'ever, never, just, already, yet', value: 'Have you ever eaten alligator?' },
      { label: 'for + duration, since + starting point', value: 'for six years, since 2002' },
    ],
    examples: [
      {
        wrong: 'I have seen him yesterday.',
        right: 'I saw him yesterday.',
        note: 'A named finished moment kills the present perfect.',
      },
      {
        wrong: 'We are here since two hours.',
        right: 'We have been here for two hours.',
        note: 'Two mistakes: the Italian present, and "since" used for a length of time.',
      },
      {
        wrong: 'Angie has been to London, she will be back on Friday.',
        right: 'Angie has gone to London, she will be back on Friday.',
        note: '"Been" means went and came back; "gone" means still there.',
      },
    ],
    traps: [
      'Where Italian uses the present ("vivo qui dal 2023", "aspetto da un\'ora") English must use the present perfect.',
      '"Already" goes between the auxiliary and the verb; "yet" goes at the end, in questions and negatives only.',
      'Never say "I haven\'t never": "never" is already negative.',
      '"Have you met her?" is the first time; "Have you known her long?" is the state since then.',
    ],
  },
  cards: [
    {
      id: 'c1-001',
      type: 'choice',
      prompt: 'They ___ their homework yet.',
      answers: ["haven't finished", "didn't finish", 'finished', 'have finished'],
      options: ["haven't finished", "didn't finish", 'finished', 'have finished'],
      explanation: '"Yet" means the matter is still open, so present perfect in a negative.',
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'c1-002',
      type: 'choice',
      prompt: '___ Tom\'s new car?',
      answers: ['Have you seen', 'Have you saw', 'Did you seen', 'Are you seen'],
      options: ['Have you seen', 'Have you saw', 'Did you seen', 'Are you seen'],
      explanation: 'After "have" comes the past participle: see / saw / seen.',
      errorTags: ['irregular-verb', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c1-003',
      type: 'choice',
      prompt: 'Laura ___ your birthday present.',
      answers: ['has already bought', 'already buyed', 'already boughts', 'have already bought'],
      options: ['has already bought', 'already buyed', 'already boughts', 'have already bought'],
      explanation: '"Already" sits between the auxiliary and the participle.',
      errorTags: ['time-adverbial', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'c1-004',
      type: 'fill',
      prompt: 'This is the first time I ___ (write) a report in English.',
      answers: ['have written', "'ve written"],
      hint: 'After "it is the first time" English does not use the present.',
      explanation: 'Fixed structure: it is the first / second / last time plus present perfect.',
      errorTags: ['present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'c1-005',
      type: 'fill',
      prompt: 'I ___ (have) this phone for three years.',
      answers: ['have had', "'ve had"],
      hint: 'The verb is "have", and so is the auxiliary.',
      explanation: 'Possession stays in the simple form: "I have had", never "I have been having".',
      errorTags: ['for-since', 'state-verbs'],
      level: 'B1',
    },
    {
      id: 'c1-006',
      type: 'fill',
      prompt: 'She ___ (not eat) anything since lunchtime.',
      answers: ["hasn't eaten", 'has not eaten'],
      explanation: '"Since" plus a starting point: present perfect.',
      errorTags: ['for-since', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'c1-007',
      type: 'correct',
      prompt: 'I have never seen not that film.',
      answers: ['I have never seen that film.'],
      explanation: 'One negative only, and "never" already is one.',
      errorTags: ['negative-form'],
      level: 'B1',
    },
    {
      id: 'c1-008',
      type: 'correct',
      prompt: 'Have you already finished? I am surprised. No, I did not finish yet.',
      answers: ['Have you already finished? I am surprised. No, I have not finished yet.'],
      explanation: '"Yet" belongs to the present perfect, in negatives and questions, at the end.',
      errorTags: ['time-adverbial', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'c1-009',
      type: 'choice',
      prompt: 'Have you ever ___ in a five-star hotel?',
      answers: ['stayed', 'been', 'gone', 'be'],
      options: ['stayed', 'been', 'gone', 'be'],
      explanation: 'With a place where you stay, use "stayed". "Been" is for movement: have you ever been to London?',
      errorTags: ['been-vs-gone'],
      level: 'B1',
    },
    {
      id: 'c1-010',
      type: 'choice',
      prompt: 'A: Have you met Tom\'s wife? B: Yes, I ___ her for two years.',
      answers: ['have known', 'have met', 'know', 'have been knowing'],
      options: ['have known', 'have met', 'know', 'have been knowing'],
      explanation: '"Meet" is the first encounter, "know" the state that follows. And "know" never takes the continuous.',
      errorTags: ['state-verbs', 'for-since'],
      level: 'B2',
    },
    {
      id: 'c1-011',
      type: 'rewrite',
      prompt: 'Conosco la mia amica da sedici anni.',
      answers: ['I have known my friend for sixteen years.', "I've known my friend for sixteen years."],
      explanation: 'Italian present plus "da" becomes English present perfect plus "for".',
      errorTags: ['for-since', 'state-verbs'],
      level: 'B1',
    },
    {
      id: 'c1-012',
      type: 'rewrite',
      prompt: 'Ho la stessa macchina dal 2022.',
      answers: ['I have had the same car since 2022.', "I've had the same car since 2022."],
      explanation: 'A starting point takes "since", and possession stays simple.',
      errorTags: ['for-since', 'state-verbs'],
      level: 'B1',
    },
    {
      id: 'c1-013',
      type: 'rewrite',
      prompt: 'Non sono mai stato a Londra.',
      answers: ['I have never been to London.', "I've never been to London."],
      explanation: '"Been to" means went and came back. With "never" the present perfect is compulsory.',
      errorTags: ['been-vs-gone'],
      level: 'B1',
    },
    {
      id: 'c1-014',
      type: 'build',
      prompt: 'how long/you/live/in this flat?',
      answers: ['How long have you lived in this flat?', 'How long have you been living in this flat?'],
      explanation: '"How long" about something still true takes the present perfect.',
      errorTags: ['for-since', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c1-015',
      type: 'build',
      prompt: 'the price of coffee/drop/since January',
      answers: ['The price of coffee has dropped since January.'],
      explanation: '"Since" plus a starting point, and this is exactly how a chart is described.',
      errorTags: ['for-since', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c1-016',
      type: 'transform',
      prompt: 'I started working here in September.',
      keyword: 'SINCE',
      given: 'I have',
      answers: ['I have worked here since September.', 'I have been working here since September.'],
      explanation: 'The starting point stays, and the tense moves to the present perfect.',
      errorTags: ['for-since'],
      level: 'B1',
    },
    {
      id: 'c1-017',
      type: 'transform',
      prompt: 'This is my first visit to Ireland.',
      keyword: 'NEVER',
      given: 'I have',
      answers: ['I have never been to Ireland before.', 'I have never been to Ireland.'],
      explanation: 'A first time is a life experience, so present perfect with "never".',
      errorTags: ['been-vs-gone', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'c1-018',
      type: 'choice',
      prompt: 'In recent years more and more people ___ to online banking.',
      answers: ['have turned', 'turned', 'turn', 'had turned'],
      options: ['have turned', 'turned', 'turn', 'had turned'],
      explanation: '"In recent years" is an unfinished period running up to now.',
      errorTags: ['time-adverbial', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'c1-019',
      type: 'fill',
      prompt: 'Tom and Lisa are not here, they ___ (just leave).',
      answers: ['have just left', "'ve just left"],
      explanation: '"Just" means a short time ago and sits between auxiliary and participle.',
      errorTags: ['time-adverbial', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'c1-020',
      type: 'form',
      prompt: 'There has been a marked ___ in sales this quarter.',
      root: 'IMPROVE',
      answers: ['improvement'],
      explanation: 'improve becomes improvement, one of the nouns used for an upward trend.',
      errorTags: ['word-formation', 'esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'c1-021',
      type: 'correct',
      prompt: 'I have lived in Milan since three years.',
      answers: ['I have lived in Milan for three years.'],
      explanation: '"Since" needs a point in time, "for" a length of time.',
      errorTags: ['for-since'],
      level: 'B1',
    },
    {
      id: 'c1-022',
      type: 'vocab',
      prompt: 'DA QUANTO TEMPO STUDI INGLESE?',
      answers: ['How long have you been studying English?', 'How long have you studied English?'],
      explanation: 'Note the translation: Italian present becomes English present perfect.',
      errorTags: ['for-since', 'question-form'],
      level: 'B1',
    },
  ],
};
