import type { Unit } from '../types';

export const c10Ability: Unit = {
  id: 'c10',
  stage: 'core',
  order: 10,
  title: 'Modals: ability and possibility',
  summary: 'Can, could, be able to, may and might.',
  level: 'B1',
  errorTags: ['modal'],
  lesson: {
    rule: 'Can and could cover ability in the present and the past, and be able to supplies every tense they do not have, while may and might express possibility rather than permission.',
    schema: [
      { label: 'Present ability or possibility', value: 'can: I can swim' },
      { label: 'Past ability, general', value: 'could: when I was a child I could climb trees' },
      { label: 'Past ability, one occasion', value: 'was able to / managed to: I managed to reach her' },
      { label: 'Perfect and future', value: 'be able to: I have not been able to, I will be able to' },
      { label: 'Possibility in the future', value: 'may / might: it might rain tonight' },
      { label: 'Politeness', value: 'could you pass me the salt?' },
    ],
    examples: [
      {
        wrong: 'I have could finish it yesterday.',
        right: 'I was able to finish it yesterday.',
        note: 'Modals have no participle, so the perfect needs "be able to".',
      },
      {
        wrong: 'Maybe Tim is the best advisor I have ever had.',
        right: 'Tim may be the best advisor I have ever had.',
        note: 'Idiomatic English prefers the modal to "maybe", especially with "be".',
      },
      {
        wrong: 'Do you can play videos on your old phone?',
        right: 'Could you play videos on your old phone?',
        note: 'No auxiliary before a modal, and a past ability takes "could".',
      },
    ],
    traps: [
      'Italian leans on "forse" plus a verb; English leans on may or might plus a verb. Train yourself to use the modal.',
      '"Could" is the past of can, but also a polite present and part of the second conditional. Context decides.',
      '"Be able to" has no continuous form.',
      '"I used to be able to" is how you say an ability you have lost.',
    ],
  },
  cards: [
    {
      id: 'c10-001',
      type: 'choice',
      prompt: '___ you play videos on your old mobile?',
      answers: ['Could', 'Do can', 'Did can', 'Were can'],
      options: ['Could', 'Do can', 'Did can', 'Were can'],
      explanation: 'Past ability, and a modal never takes an auxiliary.',
      errorTags: ['modal', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c10-002',
      type: 'choice',
      prompt: '___ drink the water from the tap here?',
      answers: ['Can you', 'Have you', 'Do you can', 'Are you can'],
      options: ['Can you', 'Have you', 'Do you can', 'Are you can'],
      explanation: 'Possibility or permission in the present: "can", by simple inversion.',
      errorTags: ['modal', 'question-form'],
      level: 'A2',
    },
    {
      id: 'c10-003',
      type: 'choice',
      prompt: 'We ___ to contact Mr Ling all day but we ___ get through.',
      answers: [
        "have been trying / haven't been able to",
        "tried / haven't could",
        "have tried / haven't",
        "are trying / couldn't",
      ],
      options: [
        "have been trying / haven't been able to",
        "tried / haven't could",
        "have tried / haven't",
        "are trying / couldn't",
      ],
      explanation: 'An unfinished attempt across the day, and "be able to" because "can" has no perfect.',
      errorTags: ['modal', 'present-perfect-continuous'],
      level: 'B2',
    },
    {
      id: 'c10-004',
      type: 'fill',
      prompt: 'I ___ (not be able to) swim for a while because of my shoulder.',
      answers: ["haven't been able to", 'have not been able to'],
      explanation: 'The present perfect of ability has to go through "be able to".',
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'c10-005',
      type: 'fill',
      prompt: 'When I was a child I ___ (use to / be able to) climb any tree.',
      answers: ['used to be able to'],
      explanation: 'A lost ability: used to be able to.',
      errorTags: ['modal', 'used-to'],
      level: 'B2',
    },
    {
      id: 'c10-006',
      type: 'fill',
      prompt: 'It ___ (rain) tonight, so take an umbrella.',
      answers: ['might rain', 'may rain', 'could rain'],
      explanation: 'Possibility in the future: may, might or could.',
      errorTags: ['modal'],
      level: 'B1',
    },
    {
      id: 'c10-007',
      type: 'correct',
      prompt: 'Maybe Lisa will move to Jakarta next year.',
      answers: ['Lisa might be moving to Jakarta next year.', 'Lisa may move to Jakarta next year.'],
      explanation: 'Not wrong, but far less idiomatic. English speakers put the uncertainty in the modal.',
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'c10-008',
      type: 'correct',
      prompt: 'She will can help us tomorrow.',
      answers: ['She will be able to help us tomorrow.'],
      explanation: 'Two modals cannot combine. The future of "can" is "will be able to".',
      errorTags: ['modal'],
      level: 'B1',
    },
    {
      id: 'c10-009',
      type: 'rewrite',
      prompt: 'Non siamo riusciti a contattare il direttore.',
      answers: ['We have been unable to reach the manager.', 'We have not been able to reach the manager.'],
      explanation: '"Riuscire a" is "be able to" or "manage to", never "succeed to".',
      errorTags: ['modal', 'false-friend'],
      level: 'B2',
    },
    {
      id: 'c10-010',
      type: 'rewrite',
      prompt: 'Potresti aprire la finestra, per favore?',
      answers: ['Could you open the window, please?', 'Would you open the window, please?'],
      explanation: '"Could" as a polite present, not a past.',
      errorTags: ['modal'],
      level: 'A2',
    },
    {
      id: 'c10-011',
      type: 'build',
      prompt: 'we/be unable to/offer/you/the job',
      answers: ['We are unable to offer you the job.'],
      explanation: 'The formal negative of ability, standard in business letters.',
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'c10-012',
      type: 'transform',
      prompt: 'Perhaps she knows the answer.',
      keyword: 'MIGHT',
      given: 'She',
      answers: ['She might know the answer.'],
      explanation: '"Perhaps" plus a verb becomes a modal plus a bare infinitive.',
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'c10-013',
      type: 'choice',
      prompt: 'Oil prices ___ rise sharply if the conflict continues.',
      answers: ['could', 'can to', 'could to', 'are could'],
      options: ['could', 'can to', 'could to', 'are could'],
      explanation: 'A projection about data: modal plus bare infinitive, very common in the ESP section.',
      errorTags: ['modal', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c10-014',
      type: 'form',
      prompt: 'Her ___ to work under pressure impressed the board.',
      root: 'ABLE',
      answers: ['ability'],
      explanation: 'able becomes ability, like responsible and responsibility.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'verb-015',
      type: 'choice',
      prompt: "When I was eight I ___ swim quite well.",
      answers: ['could', 'can', 'was able', 'managed'],
      options: ['could', 'can', 'was able', 'managed'],
      explanation: "\"Could\" for a general ability in the past. For one specific success you use \"was able to\" or \"managed to\".",
      errorTags: ['modal'],
      level: 'B1',
    },
  ],
};
