import type { Unit } from '../types';

export const c11Deduction: Unit = {
  id: 'c11',
  stage: 'core',
  order: 11,
  title: 'Modals of deduction and speculation',
  summary: 'Guessing in English, present and past. This is what puts you at B2.',
  level: 'B2',
  errorTags: ['deduction', 'modal', 'past-infinitive'],
  lesson: {
    rule: 'To guess about the past you cannot conjugate a modal, so you add a past infinitive: modal plus have plus past participle, and the modal you choose sets how sure you are.',
    schema: [
      { label: 'Sure it is true', value: 'must: he must be working late' },
      { label: 'Sure it is not true', value: "can't: he can't be serious" },
      { label: 'Expected, near certain', value: 'should: she should have finished by now' },
      { label: 'Possible', value: 'could / might / may: she might be finishing' },
      { label: 'Guess about now', value: 'modal + be + -ing: he must be joking' },
      { label: 'Guess about the past', value: 'modal + have + participle: he must have left' },
      { label: 'Never', value: 'no continuous infinitive with state verbs: not "must be having money"' },
    ],
    examples: [
      {
        wrong: 'Tom must has left early.',
        right: 'Tom must have left early.',
        note: 'After a modal, "have" is an infinitive and never changes.',
      },
      {
        wrong: "He mustn't have forgotten, he never forgets.",
        right: "He can't have forgotten, he never forgets.",
        note: 'The negative of certainty is "can\'t", not "mustn\'t", which means forbidden.',
      },
      {
        wrong: 'You must joke!',
        right: 'You must be joking!',
        note: '"Must + bare infinitive" is an obligation. For a guess about now, use the continuous infinitive.',
      },
    ],
    traps: [
      'One English sentence covers two Italian ones: "she should have finished" is both "avrebbe dovuto finire" and "dovrebbe avere finito".',
      'Compare carefully: "Tom must have left" is a guess, "Tom must leave" is an order.',
      'State verbs take no continuous infinitive: "they must prefer Greece", not "must be preferring".',
      'The whole scale, from sure to unsure: must, can\'t, should, could, might, may.',
    ],
  },
  cards: [
    {
      id: 'c11-001',
      type: 'choice',
      prompt: 'The manager ___ your report by now.',
      answers: ['must have seen', 'can see', 'is supposed to see', 'must seen'],
      options: ['must have seen', 'can see', 'is supposed to see', 'must seen'],
      explanation: '"By now" plus a confident guess about the past: must plus past infinitive.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c11-002',
      type: 'choice',
      prompt: 'A: Why are your colleagues not here? B: They ___ not ___ about the meeting.',
      answers: [
        'may / have been told',
        'will / told',
        'should / have been told',
        'can / have told',
      ],
      options: ['may / have been told', 'will / told', 'should / have been told', 'can / have told'],
      explanation: 'A guess about the past, in the passive: may not have been told.',
      errorTags: ['deduction', 'passive', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c11-003',
      type: 'choice',
      prompt: "You ___ be tired, you've been studying since seven.",
      answers: ['must', 'can', 'should', 'might not'],
      options: ['must', 'can', 'should', 'might not'],
      explanation: 'Near certainty about the present: "must".',
      errorTags: ['deduction'],
      level: 'B2',
    },
    {
      id: 'c11-004',
      type: 'choice',
      prompt: "It ___ be the postman, but I'm not sure.",
      answers: ['might', 'must', "can't", 'will'],
      options: ['might', 'must', "can't", 'will'],
      explanation: 'Uncertain possibility: might, may or could.',
      errorTags: ['deduction'],
      level: 'B1',
    },
    {
      id: 'c11-005',
      type: 'fill',
      prompt: "She ___ (can / not forget) her phone again! She just bought a case for it.",
      answers: ["can't have forgotten", 'cannot have forgotten'],
      explanation: 'Certainty that something did NOT happen: can\'t plus past infinitive.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c11-006',
      type: 'fill',
      prompt: 'It ___ (must / rain), the street is soaking wet.',
      answers: ['must have rained'],
      explanation: 'Present evidence of a past event: must plus past infinitive.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c11-007',
      type: 'fill',
      prompt: 'Tina ___ (should / finish) her homework by now.',
      answers: ['should have finished'],
      explanation: '"Should" plus past infinitive: what you expect has happened.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c11-008',
      type: 'correct',
      prompt: 'Lisa\'s parents must be having a lot of money.',
      answers: ['Lisa\'s parents must have a lot of money.'],
      explanation: '"Have" meaning possession is a state verb, so no continuous infinitive.',
      errorTags: ['deduction', 'state-verbs'],
      level: 'B2',
    },
    {
      id: 'c11-009',
      type: 'correct',
      prompt: 'He mustn\'t have left, his coat is still here.',
      answers: ["He can't have left, his coat is still here."],
      explanation: 'The negative of a deduction is "can\'t have", because "mustn\'t" means forbidden.',
      errorTags: ['deduction'],
      level: 'B2',
    },
    {
      id: 'c11-010',
      type: 'correct',
      prompt: 'You could tell me you do not like fish!',
      answers: ['You could have told me you do not like fish!'],
      explanation: 'A reproach about the past needs the past infinitive.',
      errorTags: ['past-infinitive', 'deduction'],
      level: 'B2',
    },
    {
      id: 'c11-011',
      type: 'rewrite',
      prompt: 'Forse non le è piaciuto il modo in cui l\'ho cucinato.',
      answers: ['She may not have liked the way I cooked it.', 'She might not have liked the way I cooked it.'],
      explanation: 'The Italian "forse" becomes may or might, and the past becomes a past infinitive.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c11-012',
      type: 'rewrite',
      prompt: 'Deve essere andato via presto.',
      answers: ['He must have left early.', 'He must have gone early.'],
      explanation: 'The Italian "deve essere" of deduction is "must have" plus participle.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c11-013',
      type: 'transform',
      prompt: 'I am sure she has not finished.',
      keyword: 'CANNOT',
      given: 'She',
      answers: ['She cannot have finished.', "She can't have finished."],
      explanation: 'Certainty that something is not true: can\'t plus past infinitive.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c11-014',
      type: 'transform',
      prompt: 'I am sure he is working late.',
      keyword: 'MUST',
      given: 'He',
      answers: ['He must be working late.'],
      explanation: 'A guess about right now: modal plus continuous infinitive.',
      errorTags: ['deduction'],
      level: 'B2',
    },
    {
      id: 'c11-015',
      type: 'vocab',
      prompt: 'Traduci: I SHOULD HAVE GONE (due significati)',
      answers: [
        'sarei dovuto andare / dovrei essere andato',
        'sarei dovuto andare, dovrei essere andato',
      ],
      explanation: 'One English form, two Italian readings: the reproach and the expectation. Context decides.',
      errorTags: ['past-infinitive', 'deduction'],
      level: 'C1',
    },
    {
      id: 'c11-016',
      type: 'vocab',
      prompt: 'Traduci: I MIGHT HAVE FINISHED',
      answers: ['forse avrei finito', 'forse avrei potuto finire', 'potrei aver finito'],
      explanation: 'May and might plus a past infinitive cover both the speculation and the third conditional.',
      errorTags: ['past-infinitive', 'deduction'],
      level: 'C1',
    },
    {
      id: 'c11-017',
      type: 'choice',
      prompt: 'There ___ a rise in oil prices last quarter, judging by these figures.',
      answers: ['must have been', 'must be', 'must been', 'should be'],
      options: ['must have been', 'must be', 'must been', 'should be'],
      explanation: 'Speculating about past data: modal plus have been, in the ESP structure "there + be".',
      errorTags: ['deduction', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c11-018',
      type: 'form',
      prompt: 'That is only a ___, we have no evidence yet.',
      root: 'SPECULATE',
      answers: ['speculation'],
      explanation: 'speculate becomes speculation.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'verb-011',
      type: 'choice',
      prompt: "You ___ be tired: you've been studying since seven.",
      answers: ['must', 'can', 'should', 'might not'],
      options: ['must', 'can', 'should', 'might not'],
      explanation: "\"Must\" for a logical deduction when you are almost certain. The opposite is \"can't\": \"You can't be tired, you slept ten hours\".",
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'verb-012',
      type: 'choice',
      prompt: "You ___ have told me! I waited outside for an hour.",
      answers: ['could', 'can', 'must', 'should not'],
      options: ['could', 'can', 'must', 'should not'],
      explanation: "\"Could have + participle\" reproaches somebody for something that was possible and did not happen. \"Should have told me\" would also work in real life.",
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'verb-014',
      type: 'choice',
      prompt: "It ___ be the postman, but I'm not sure.",
      answers: ['might', 'must', "can't", 'will'],
      options: ['might', 'must', "can't", 'will'],
      explanation: "\"Might / may / could\" for uncertain possibility. \"Must\" would be near certainty.",
      errorTags: ['modal'],
      level: 'B1',
    },
  ],
};
