import type { Unit } from '../types';

export const c12Get: Unit = {
  id: 'c12',
  stage: 'core',
  order: 12,
  title: 'Uses of GET and phrasal verbs',
  summary: 'One verb, a dozen meanings, and the phrasal verbs built on it.',
  level: 'B2',
  errorTags: ['get', 'phrasal-verb'],
  lesson: {
    rule: 'GET means receive, arrive, become or make somebody do something, and which one it is depends entirely on what follows it.',
    schema: [
      { label: 'get + noun', value: 'receive, buy, fetch, understand: I get your point' },
      { label: 'get + place', value: 'arrive: what time did you get home?' },
      { label: 'get + person + to do', value: 'make or ask them: I will get someone to fix it' },
      { label: 'get + adjective', value: 'become: it is getting colder, they got hungry' },
      { label: 'get + past participle', value: 'a passive: my phone got stolen, we got married' },
      { label: 'get + object + participle', value: 'have it done: get your car washed' },
      { label: 'get used to + -ing', value: 'become accustomed' },
    ],
    examples: [
      {
        wrong: 'When we arrived to the station the train had already left.',
        right: 'When we got to the station the train had already left.',
        note: '"Get to" is the everyday way to say arrive, and "arrive" never takes "to".',
      },
      {
        wrong: 'The children were becoming hungry.',
        right: 'The children were getting hungry.',
        note: '"Get" is the natural verb for changing state; "become" sounds formal here.',
      },
      {
        wrong: 'I will get that someone fixes my computer.',
        right: 'I will get someone to fix my computer.',
        note: 'get + person + to + infinitive.',
      },
    ],
    traps: [
      'A phrasal verb is learnt with a synonym and an example, never with a translation.',
      'The same phrasal verb can have several meanings: "get over" an illness, but also "get over" an idea to somebody.',
      '"Get married", "get lost", "get paid" are passives in disguise.',
      '"Get used to doing" means becoming accustomed; "used to do" is a past habit.',
    ],
  },
  cards: [
    {
      id: 'c12-001',
      type: 'choice',
      prompt: 'My sister makes barely enough money to ___.',
      answers: ['get by', 'get along', 'get out', 'get over'],
      options: ['get by', 'get along', 'get out', 'get over'],
      explanation: '"Get by" means to manage on very little.',
      errorTags: ['phrasal-verb', 'get'],
      level: 'B2',
    },
    {
      id: 'c12-002',
      type: 'choice',
      prompt: 'It took her months to ___ the flu.',
      answers: ['get over', 'get by', 'get off', 'get across'],
      options: ['get over', 'get by', 'get off', 'get across'],
      explanation: '"Get over" means to recover from something.',
      errorTags: ['phrasal-verb'],
      level: 'B2',
    },
    {
      id: 'c12-003',
      type: 'choice',
      prompt: 'I called three times but I could not ___ to the helpline.',
      answers: ['get through', 'get along', 'get up', 'get in'],
      options: ['get through', 'get along', 'get up', 'get in'],
      explanation: '"Get through" is to reach somebody by phone.',
      errorTags: ['phrasal-verb'],
      level: 'B2',
    },
    {
      id: 'c12-004',
      type: 'choice',
      prompt: 'She ___ very well with her new colleagues.',
      answers: ['gets on', 'gets off', 'gets over', 'gets by'],
      options: ['gets on', 'gets off', 'gets over', 'gets by'],
      explanation: '"Get on with" or "get along with" somebody means to have a good relationship.',
      errorTags: ['phrasal-verb'],
      level: 'B1',
    },
    {
      id: 'c12-005',
      type: 'fill',
      prompt: 'You look tired, I will ___ you a coffee.',
      answers: ['get'],
      explanation: 'get + person + noun: fetch or buy something for them.',
      errorTags: ['get'],
      level: 'B1',
    },
    {
      id: 'c12-006',
      type: 'fill',
      prompt: 'You should ___ your car ___ (wash), it is filthy.',
      answers: ['get / washed', 'get your car washed'],
      explanation: 'get something done: somebody else does it for you.',
      errorTags: ['have-something-done', 'get'],
      level: 'B2',
    },
    {
      id: 'c12-007',
      type: 'fill',
      prompt: 'My phone ___ (steal) in Cairo.',
      answers: ['got stolen', 'was stolen'],
      explanation: 'get plus past participle works as an informal passive.',
      errorTags: ['get', 'passive'],
      level: 'B2',
    },
    {
      id: 'c12-008',
      type: 'correct',
      prompt: 'What time did you arrive to home?',
      answers: ['What time did you get home?', 'What time did you arrive home?'],
      explanation: '"Get home" needs no preposition, and "arrive" is never followed by "to".',
      errorTags: ['get', 'preposition'],
      level: 'B1',
    },
    {
      id: 'c12-009',
      type: 'correct',
      prompt: 'It is becoming colder and colder.',
      answers: ['It is getting colder and colder.'],
      explanation: '"Get" is the idiomatic verb for a progressive change of state.',
      errorTags: ['get'],
      level: 'B1',
    },
    {
      id: 'c12-010',
      type: 'rewrite',
      prompt: 'Ho capito il tuo punto di vista, ma non sono d\'accordo.',
      answers: ['I get your point, but I do not agree.', "I get your point, but I don't agree."],
      explanation: '"Get" as understand, very common in speech. And "agree" is a verb.',
      errorTags: ['get', 'false-friend'],
      level: 'B2',
    },
    {
      id: 'c12-011',
      type: 'rewrite',
      prompt: 'Mi sono fatto tagliare i capelli.',
      answers: ['I had my hair cut.', 'I got my hair cut.'],
      explanation: 'This structure is compulsory in English: you cannot say "I cut my hair" unless you did it yourself.',
      errorTags: ['have-something-done', 'get'],
      level: 'B2',
    },
    {
      id: 'c12-012',
      type: 'build',
      prompt: 'I/get/my PA/set up a meeting',
      answers: ['I got my PA to set up a meeting.', 'I will get my PA to set up a meeting.'],
      explanation: 'get + person + to + infinitive.',
      errorTags: ['get'],
      level: 'B2',
    },
    {
      id: 'c12-013',
      type: 'transform',
      prompt: 'Somebody fixed my car yesterday.',
      keyword: 'HAD',
      given: 'I',
      answers: ['I had my car fixed yesterday.'],
      explanation: 'have something done: the service you paid for, not the work you did.',
      errorTags: ['have-something-done'],
      level: 'B2',
    },
    {
      id: 'c12-014',
      type: 'vocab',
      prompt: 'GET RID OF',
      answers: ['to throw away', 'throw away', 'to remove', 'to dispose of', 'get free of something'],
      explanation: 'Learn a phrasal verb with a synonym, not a translation: get rid of equals dispose of.',
      errorTags: ['phrasal-verb'],
      level: 'B2',
    },
    {
      id: 'c12-015',
      type: 'vocab',
      prompt: 'GET AWAY WITH (something)',
      answers: ['to avoid punishment', 'avoid punishment', 'escape punishment', 'to escape punishment'],
      explanation: 'To do something wrong and not be punished for it.',
      errorTags: ['phrasal-verb'],
      level: 'C1',
    },
    {
      id: 'c12-016',
      type: 'vocab',
      prompt: 'GET AHEAD',
      answers: ['to make progress', 'make progress', 'to advance', 'to be successful'],
      explanation: 'To progress in a career. Its opposite is "get behind", to fall behind schedule.',
      errorTags: ['phrasal-verb'],
      level: 'B2',
    },
    {
      id: 'c12-017',
      type: 'choice',
      prompt: 'It took me a month to ___ working night shifts.',
      answers: ['get used to', 'used to', 'get use to', 'be used'],
      options: ['get used to', 'used to', 'get use to', 'be used'],
      explanation: 'get used to + -ing: becoming accustomed. Not the same as "used to work", a past habit.',
      errorTags: ['get', 'used-to'],
      level: 'B2',
    },
    {
      id: 'c12-018',
      type: 'form',
      prompt: 'We are having trouble getting the job ___.',
      root: 'DO',
      answers: ['done'],
      explanation: 'get something done takes the past participle.',
      errorTags: ['have-something-done', 'get'],
      level: 'B2',
    },
  ],
};
