import type { Unit } from '../types';

export const c13Passive: Unit = {
  id: 'c13',
  stage: 'core',
  order: 13,
  title: 'The passive',
  summary: 'Far more common in English than in Italian, in speech as well as in writing.',
  level: 'B2',
  errorTags: ['passive', 'double-object-passive', 'have-something-done'],
  lesson: {
    rule: 'The passive is always be plus the past participle, with be carrying the tense the active verb would have had, and English reaches for it wherever Italian would use an impersonal "si" or a vague "they".',
    schema: [
      { label: 'Present simple', value: 'is / are + participle: cheese is made from milk' },
      { label: 'Present continuous', value: 'is being + participle: a new hospital is being built' },
      { label: 'Past simple', value: 'was / were + participle: my bike was stolen' },
      { label: 'Past continuous', value: 'was being + participle: I was being followed' },
      { label: 'Perfect', value: 'has / had been + participle' },
      { label: 'Future and modals', value: 'will be, must be, may have been + participle' },
      { label: 'The agent, if it matters', value: 'by + doer: written by Shakespeare' },
    ],
    examples: [
      {
        wrong: 'They stole my bike but they caught the thief.',
        right: 'My bike was stolen but they caught the thief.',
        note: 'English needs to know who "they" is. When you do not, use the passive.',
      },
      {
        wrong: 'The results will publish next Monday.',
        right: 'The results will be published next Monday.',
        note: 'Without "be" the sentence says the results will publish something.',
      },
      {
        wrong: 'In Japan fish eats raw.',
        right: 'In Japan fish is eaten raw.',
        note: 'The Italian impersonal "si mangia" becomes an English passive.',
      },
    ],
    traps: [
      'English has almost no impersonal constructions, which is why the passive does that work.',
      'English has a passive continuous, which Italian can barely translate: "the brochure is being printed".',
      'Double object verbs give two passives, and the one starting with the person is the more common: "I was shown my new office".',
      'There is no passive continuous in the perfect or the future: no "has been being built".',
    ],
  },
  cards: [
    {
      id: 'c13-001',
      type: 'choice',
      prompt: 'The lights ___ off.',
      answers: ['have been turned', 'have turned', 'turned', 'are turning'],
      options: ['have been turned', 'have turned', 'turned', 'are turning'],
      explanation: 'Somebody turned them off, and we do not say who: present perfect passive.',
      errorTags: ['passive'],
      level: 'B1',
    },
    {
      id: 'c13-002',
      type: 'choice',
      prompt: 'My car ___ yesterday.',
      answers: ['was stolen', 'is stolen', 'has been stolen', 'stole'],
      options: ['was stolen', 'is stolen', 'has been stolen', 'stole'],
      explanation: '"Yesterday" fixes the moment, so the past simple passive.',
      errorTags: ['passive', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'c13-003',
      type: 'fill',
      prompt: 'They are building a new hospital. A new hospital ___ (build).',
      answers: ['is being built'],
      explanation: 'Present continuous passive: is being plus participle.',
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'c13-004',
      type: 'fill',
      prompt: "I didn't realise they were following me. I didn't realise I ___ (follow).",
      answers: ['was being followed'],
      explanation: 'Past continuous passive: was being plus participle.',
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'c13-005',
      type: 'fill',
      prompt: 'The IT module ___ (teach) in the first semester.',
      answers: ['will be taught', 'is taught'],
      explanation: 'Future passive: will be plus participle.',
      errorTags: ['passive'],
      level: 'B1',
    },
    {
      id: 'c13-006',
      type: 'fill',
      prompt: 'Are you ___ (pay) for your internship?',
      answers: ['being paid'],
      explanation: 'A present continuous passive in question form.',
      errorTags: ['passive', 'question-form'],
      level: 'B2',
    },
    {
      id: 'c13-007',
      type: 'choice',
      prompt: 'Lisa gave Tim some flowers. Which passive is the more natural?',
      answers: [
        'Tim was given some flowers.',
        'Some flowers were given Tim.',
        'Tim was gave some flowers.',
        'Some flowers gave to Tim.',
      ],
      options: [
        'Tim was given some flowers.',
        'Some flowers were given Tim.',
        'Tim was gave some flowers.',
        'Some flowers gave to Tim.',
      ],
      explanation: 'With double object verbs the person usually becomes the subject.',
      errorTags: ['double-object-passive'],
      level: 'B2',
    },
    {
      id: 'c13-008',
      type: 'fill',
      prompt: 'Tina ___ (not show) her new office yet.',
      answers: ["hasn't been shown", 'has not been shown'],
      explanation: 'Present perfect passive with a double object verb.',
      errorTags: ['double-object-passive', 'passive'],
      level: 'B2',
    },
    {
      id: 'c13-009',
      type: 'fill',
      prompt: 'She should ___ (tell) what to do.',
      answers: ['have been told', 'be told'],
      explanation: 'After a modal the passive goes into an infinitive: be told, or have been told for the past.',
      errorTags: ['passive', 'modal'],
      level: 'B2',
    },
    {
      id: 'c13-010',
      type: 'correct',
      prompt: 'I do not like to be told what to do, and I left without being give permission.',
      answers: ['I do not like being told what to do, and I left without being given permission.'],
      explanation: 'After "like" and after a preposition the passive takes the -ing form: being told, being given.',
      errorTags: ['passive', 'preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c13-011',
      type: 'rewrite',
      prompt: 'Hanno regalato dei fiori a mio marito.',
      answers: ['My husband was given some flowers.'],
      explanation: 'The Italian vague "hanno" becomes an English passive, with the person as subject.',
      errorTags: ['double-object-passive'],
      level: 'B2',
    },
    {
      id: 'c13-012',
      type: 'rewrite',
      prompt: 'Ieri le hanno chiesto di non parcheggiare qui.',
      answers: ['She was asked not to park here yesterday.'],
      explanation: 'Note where the negative goes: asked NOT to park.',
      errorTags: ['double-object-passive', 'gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c13-013',
      type: 'rewrite',
      prompt: 'Il francese mi è stato insegnato da una cantante.',
      answers: ['I was taught French by a singer.'],
      explanation: 'The person first, then the thing, then the agent with "by".',
      errorTags: ['double-object-passive'],
      level: 'B2',
    },
    {
      id: 'c13-014',
      type: 'rewrite',
      prompt: 'Mi pagavano meglio nell\'altro lavoro.',
      answers: ['I was paid better in my other job.', 'I was better paid in my other job.'],
      explanation: 'Another vague Italian subject that becomes an English passive.',
      errorTags: ['double-object-passive'],
      level: 'B2',
    },
    {
      id: 'c13-015',
      type: 'rewrite',
      prompt: 'Ai turisti non è permesso entrare in cucina.',
      answers: [
        'Tourists are not allowed into the kitchen.',
        'Visitors are not allowed in the kitchen.',
        'Tourists are not allowed to enter the kitchen.',
      ],
      explanation: '"Allow" is a double object verb, so the people become the subject.',
      errorTags: ['double-object-passive'],
      level: 'B2',
    },
    {
      id: 'c13-016',
      type: 'transform',
      prompt: 'Somebody has to review our risk management policy.',
      keyword: 'NEEDS',
      given: 'Our risk management policy',
      answers: ['Our risk management policy needs reviewing.', 'Our risk management policy needs to be reviewed.'],
      explanation: '"Need" plus -ing carries a passive meaning: my car needs washing.',
      errorTags: ['passive', 'gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c13-017',
      type: 'build',
      prompt: 'the lecture/hold/every Tuesday/in room 12',
      answers: ['The lecture is held every Tuesday in room 12.'],
      explanation: 'Present simple passive for a routine.',
      errorTags: ['passive'],
      level: 'B1',
    },
    {
      id: 'c13-018',
      type: 'build',
      prompt: 'the data/analyse/by two different teams/last year',
      answers: ['The data were analysed by two different teams last year.', 'The data was analysed by two different teams last year.'],
      explanation: 'Past simple passive with the agent. In academic English "data" takes a plural verb.',
      errorTags: ['passive', 'uncountable'],
      level: 'B2',
    },
    {
      id: 'c13-019',
      type: 'choice',
      prompt: 'Most paper ___ from wood.',
      answers: ['is made', 'makes', 'is making', 'made'],
      options: ['is made', 'makes', 'is making', 'made'],
      explanation: 'The Italian "si fa" becomes an English passive.',
      errorTags: ['passive'],
      level: 'B1',
    },
    {
      id: 'c13-020',
      type: 'form',
      prompt: 'The theory is based on a single ___.',
      root: 'ASSUME',
      answers: ['assumption'],
      explanation: 'assume becomes assumption. Note "based ON", a fixed preposition.',
      errorTags: ['word-formation', 'preposition'],
      level: 'B2',
    },
    {
      id: 'verb-016',
      type: 'choice',
      prompt: 'The results ___ next Monday.',
      answers: ['will be published', 'will publish', 'are publishing', 'will been published'],
      options: ['will be published', 'will publish', 'are publishing', 'will been published'],
      explanation: "Passive: who does it is not the point. Fixed structure: be plus past participle, with \"be\" carrying the tense of the sentence.",
      errorTags: ['passive'],
      level: 'B1',
    },
    {
      id: 'verb-017',
      type: 'choice',
      prompt: 'The data ___ by two different teams last year.',
      answers: ['were analysed', 'analysed', 'have analysed', 'was analysing'],
      options: ['were analysed', 'analysed', 'have analysed', 'was analysing'],
      explanation: "Passive in the past simple. In academic English \"data\" is technically plural (\"data were\"), though \"data was\" is common in speech.",
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'verb-020',
      type: 'choice',
      prompt: 'The lecture ___ every Tuesday in room 12.',
      answers: ['is held', 'holds', 'is holding', 'has held'],
      options: ['is held', 'holds', 'is holding', 'has held'],
      explanation: "Passive in the present simple for a routine: be plus participle.",
      errorTags: ['passive'],
      level: 'B1',
    },
  ],
};
