import type { Unit } from '../types';

export const c14Reporting: Unit = {
  id: 'c14',
  stage: 'core',
  order: 14,
  title: 'Reporting verbs and the special passive',
  summary: 'How news, law and academic writing report what is said without naming who said it.',
  level: 'B2',
  errorTags: ['reported-speech', 'passive', 'past-infinitive'],
  lesson: {
    rule: 'To report what people in general say or think, English uses a passive twice over: "it is thought that..." or, more elegantly, the subject first and then "is thought to...".',
    schema: [
      { label: 'Basic form', value: 'It is said / thought / believed / known that...' },
      { label: 'Elegant form', value: 'Subject + is said / thought / believed + to + infinitive' },
      { label: 'Earlier than the reporting', value: 'to have + participle: is reported to have happened' },
      { label: 'Same time or later', value: 'plain infinitive: is expected to last' },
      { label: 'The verbs', value: 'say, think, believe, know, consider, report, expect, understand, allege' },
      { label: 'Reported speech', value: 'every tense steps one notch back, and time words shift' },
      { label: 'Never', value: '"say" does not take a person: tell somebody, say to somebody' },
    ],
    examples: [
      {
        wrong: 'She said me to check the figures.',
        right: 'She asked me to check the figures.',
        note: 'Say takes no direct person. Ask or tell somebody to do something.',
      },
      {
        wrong: 'He said he has finished the report the day before.',
        right: 'He said he had finished the report the day before.',
        note: 'In reported speech the present perfect becomes the past perfect.',
      },
      {
        wrong: 'The accident is reported to happen around 11pm.',
        right: 'The accident is reported to have happened around 11pm.',
        note: 'It happened before the reporting, so the infinitive is a past one.',
      },
    ],
    traps: [
      'Italian "si dice che", "si pensa che", "si sa che" all become this English structure.',
      'The past infinitive is only for something that happened earlier. A regular or future fact takes the plain infinitive: "Australia is known to have many poisonous animals".',
      'In reported speech, "yesterday" becomes "the day before", "here" becomes "there", "tomorrow" becomes "the next day".',
      '"Allegedly" is the one-word version of "is alleged to".',
    ],
  },
  cards: [
    {
      id: 'c14-001',
      type: 'choice',
      prompt: 'He said he ___ the report the day before.',
      answers: ['had finished', 'has finished', 'finished', 'was finishing'],
      options: ['had finished', 'has finished', 'finished', 'was finishing'],
      explanation: 'Reported speech pushes the tense one step back.',
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'c14-002',
      type: 'choice',
      prompt: 'She ___ me to check the figures again.',
      answers: ['asked', 'said', 'told to', 'said to me to'],
      options: ['asked', 'said', 'told to', 'said to me to'],
      explanation: 'ask or tell somebody TO do something. Say never takes the person directly.',
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'c14-003',
      type: 'fill',
      prompt: 'Tom and Tina ___ (believe) to be divorced.',
      answers: ['are believed'],
      explanation: 'The elegant form: subject plus passive reporting verb plus infinitive.',
      errorTags: ['reported-speech', 'passive'],
      level: 'B2',
    },
    {
      id: 'c14-004',
      type: 'fill',
      prompt: 'The wounds ___ (understand) to be the result of the fight.',
      answers: ['are understood'],
      explanation: '"Understand" joins say, think and believe in this structure.',
      errorTags: ['reported-speech', 'passive'],
      level: 'C1',
    },
    {
      id: 'c14-005',
      type: 'fill',
      prompt: 'Australia ___ (know) to have many poisonous animals.',
      answers: ['is known'],
      explanation: 'A fact that holds now, so a plain infinitive after it.',
      errorTags: ['reported-speech', 'passive'],
      level: 'B2',
    },
    {
      id: 'c14-006',
      type: 'fill',
      prompt: 'This weather ___ (expect) to last for another week.',
      answers: ['is expected'],
      explanation: 'Projected into the future, so no past infinitive.',
      errorTags: ['reported-speech', 'passive'],
      level: 'B2',
    },
    {
      id: 'c14-007',
      type: 'fill',
      prompt: 'This film is known ___ (shoot) in the actor\'s hometown.',
      answers: ['to have been shot'],
      hint: 'It happened before, and somebody else did it.',
      explanation: 'Past infinitive in the passive: to have been plus participle.',
      errorTags: ['past-infinitive', 'passive'],
      level: 'C1',
    },
    {
      id: 'c14-008',
      type: 'fill',
      prompt: 'The asteroid is reported ___ (fall) in the middle of the Pacific.',
      answers: ['to have fallen'],
      explanation: 'Earlier than the reporting, and "fall" is intransitive, so no passive.',
      errorTags: ['past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c14-009',
      type: 'transform',
      prompt: 'Everyone knows they moved to New York.',
      keyword: 'ARE',
      given: 'They',
      answers: ['They are known to have moved to New York.'],
      explanation: 'The move happened before the knowing, so a past infinitive.',
      errorTags: ['reported-speech', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c14-010',
      type: 'transform',
      prompt: 'It is said that the CEO has disappeared.',
      keyword: 'ALLEGED',
      given: 'The CEO',
      answers: ['The CEO is alleged to have disappeared.'],
      explanation: '"Allege" belongs to the same family, common in legal and press English.',
      errorTags: ['reported-speech', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c14-011',
      type: 'transform',
      prompt: 'People believed that the Sun circled the Earth.',
      keyword: 'WAS',
      given: 'The Sun',
      answers: ['The Sun was believed to circle the Earth.', 'The Sun was believed to circle around the Earth.'],
      explanation: 'A repeated, regular fact, so the plain infinitive even though the belief is past.',
      errorTags: ['reported-speech'],
      level: 'C1',
    },
    {
      id: 'c14-012',
      type: 'rewrite',
      prompt: 'Si dice che il mercato crescerà.',
      answers: ['The market is said to be growing.', 'It is said that the market will grow.', 'The market is expected to grow.'],
      explanation: 'The Italian impersonal "si dice" becomes the English reporting passive.',
      errorTags: ['reported-speech', 'passive'],
      level: 'B2',
    },
    {
      id: 'c14-013',
      type: 'rewrite',
      prompt: 'Si ritiene che l\'incidente sia avvenuto verso le undici.',
      answers: [
        'The accident is thought to have happened around eleven.',
        'It is thought that the accident happened around eleven.',
      ],
      explanation: 'Both forms are correct; the second is the more elegant one for written English.',
      errorTags: ['reported-speech', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c14-014',
      type: 'build',
      prompt: 'from the window/the thieves/report/escape',
      answers: [
        'The thieves are reported to have escaped from the window.',
        'The thieves were reported to have escaped from the window.',
      ],
      explanation: 'The escape came before the report, so a past infinitive.',
      errorTags: ['reported-speech', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'c14-015',
      type: 'build',
      prompt: 'unlikely/the boss/be/be on time',
      answers: ['The boss is unlikely to be on time.', 'It is unlikely that the boss will be on time.'],
      explanation: '"Unlikely to" follows the same subject-plus-infinitive shape.',
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'c14-016',
      type: 'correct',
      prompt: 'He told that he would come later.',
      answers: ['He said that he would come later.', 'He told me that he would come later.'],
      explanation: '"Tell" needs a person; "say" does not take one directly.',
      errorTags: ['reported-speech'],
      level: 'B1',
    },
    {
      id: 'c14-017',
      type: 'choice',
      prompt: 'The market ___ to spike after the announcement.',
      answers: ['is expected', 'expects', 'is expecting', 'expected'],
      options: ['is expected', 'expects', 'is expecting', 'expected'],
      explanation: 'The standard formula of financial reporting.',
      errorTags: ['reported-speech', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c14-018',
      type: 'form',
      prompt: 'According to the official ___, no one was hurt.',
      root: 'STATE',
      answers: ['statement'],
      explanation: 'state becomes statement.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'verb-018',
      type: 'choice',
      prompt: 'He said he ___ the report the day before.',
      answers: ['had finished', 'has finished', 'finished', 'was finishing'],
      options: ['had finished', 'has finished', 'finished', 'was finishing'],
      explanation: "Reported speech: the present perfect becomes the past perfect, and \"yesterday\" becomes \"the day before\".",
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'verb-019',
      type: 'choice',
      prompt: 'She ___ me to check the figures again.',
      answers: ['asked', 'said', 'told to', 'said to me to'],
      options: ['asked', 'said', 'told to', 'said to me to'],
      explanation: "\"Ask / tell somebody TO do something\". \"Say\" never takes a person straight after it: you say something to me, you never \"say me\".",
      errorTags: ['reported-speech'],
      level: 'B2',
    },
  ],
};
