import type { Unit } from '../types';

export const c15Conditionals: Unit = {
  id: 'c15',
  stage: 'core',
  order: 15,
  title: 'Conditionals and wish',
  summary: 'First, second, third: how real is the thing you are imagining.',
  level: 'B2',
  errorTags: ['conditional', 'wish'],
  lesson: {
    rule: 'The if-half never takes will or would: its tense steps one notch back from the time you actually mean, and "wish" behaves exactly like "if".',
    schema: [
      { label: 'First, real and likely', value: 'if + present simple, then will + infinitive' },
      { label: 'Second, unreal present', value: 'if + past simple, then would + infinitive' },
      { label: 'Third, unreal past', value: 'if + past perfect, then would have + participle' },
      { label: 'Instead of would', value: 'could (ability), might (possibility), should (obligation)' },
      { label: 'Wish about the present', value: 'I wish I had more time' },
      { label: 'Wish about the past', value: 'I wish I had studied harder' },
      { label: 'Wish about other people', value: 'I wish he would not play loud music' },
    ],
    examples: [
      {
        wrong: 'If I would have more time, I would read it.',
        right: 'If I had more time, I would read it.',
        note: 'Never "would" inside the if.',
      },
      {
        wrong: 'If I was you, I would not buy that car.',
        right: 'If I were you, I would not buy that car.',
        note: 'Formal English keeps "were" for every person in the second conditional.',
      },
      {
        wrong: 'The CEO would have promoted me if I could have worked harder.',
        right: 'The CEO would have promoted me if I had been able to work harder.',
        note: 'The if-half of a third conditional takes the past perfect, and "could" is a past simple.',
      },
    ],
    traps: [
      'Italian uses the subjunctive ("se avessi tempo"); English uses a past that talks about the present.',
      'First or second? First means you are fairly sure it will happen; second is a fifty-fifty hypothesis.',
      '"Wish" replaces "if", so it inherits all the same tense rules.',
      'We never say "wish + would have": for the past it is "wish + past perfect".',
    ],
  },
  cards: [
    {
      id: 'c15-001',
      type: 'choice',
      prompt: 'If John asked you to marry him, what ___ you say?',
      answers: ['would', 'did', 'do', 'will'],
      options: ['would', 'did', 'do', 'will'],
      explanation: 'Second conditional: if plus past simple, then "would".',
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'c15-002',
      type: 'choice',
      prompt: 'He would buy a car if he ___ the money.',
      answers: ['had', 'would have', 'has', 'will have'],
      options: ['had', 'would have', 'has', 'will have'],
      explanation: 'The if-half of a second conditional takes the past simple.',
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'c15-003',
      type: 'choice',
      prompt: 'If trains ___ more reliable, more people ___ use them.',
      answers: ['were / would', 'would / would', 'were / will', 'are / would'],
      options: ['were / would', 'would / would', 'were / will', 'are / would'],
      explanation: 'Second conditional with "were" for every person.',
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'c15-004',
      type: 'choice',
      prompt: 'If he ___ more time, he ___ you.',
      answers: ['had / would help', 'has / helps', 'would have / will help', 'had / will help'],
      options: ['had / would help', 'has / helps', 'would have / will help', 'had / will help'],
      explanation: 'Classic second conditional pattern.',
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'c15-005',
      type: 'fill',
      prompt: 'If she ___ (not lose) her phone, she would have been able to call you.',
      answers: ["hadn't lost", 'had not lost'],
      explanation: 'Third conditional: past perfect in the if-half.',
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'c15-006',
      type: 'fill',
      prompt: 'What ___ you ___ (do) if Tim had not been there?',
      answers: ['would / have done', 'would you have done'],
      explanation: 'Third conditional in question form: would have plus participle.',
      errorTags: ['conditional', 'question-form'],
      level: 'B2',
    },
    {
      id: 'c15-007',
      type: 'fill',
      prompt: 'We ___ (can / win) the match if I had not missed the penalty.',
      answers: ['could have won'],
      explanation: '"Could have" replaces "would have" when you mean it was possible.',
      errorTags: ['conditional', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c15-008',
      type: 'fill',
      prompt: 'She ___ (might / pass) the exam if they had asked her another question.',
      answers: ['might have passed'],
      explanation: '"Might have" softens the third conditional to a possibility.',
      errorTags: ['conditional', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'c15-009',
      type: 'correct',
      prompt: 'If I would be you, I would not sign that contract.',
      answers: ['If I were you, I would not sign that contract.'],
      explanation: 'No "would" in the if-half, and the fixed form is "if I were you".',
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'c15-010',
      type: 'correct',
      prompt: 'I wish I would have studied harder.',
      answers: ['I wish I had studied harder.'],
      explanation: 'Wish about the past takes the past perfect, never "would have".',
      errorTags: ['wish', 'conditional'],
      level: 'B2',
    },
    {
      id: 'c15-011',
      type: 'fill',
      prompt: 'I wish I ___ (know) how to code in Python.',
      answers: ['knew'],
      explanation: 'A wish about the present takes the past simple.',
      errorTags: ['wish'],
      level: 'B2',
    },
    {
      id: 'c15-012',
      type: 'fill',
      prompt: 'I wish he ___ (not play) loud music at night.',
      answers: ["wouldn't play", 'would not play'],
      explanation: 'When the wish is about somebody else\'s annoying behaviour, "wish" takes "would".',
      errorTags: ['wish'],
      level: 'C1',
    },
    {
      id: 'c15-013',
      type: 'rewrite',
      prompt: 'Comprerei una barca se fossi ricco.',
      answers: ['I would buy a boat if I were rich.', "I'd buy a boat if I were rich."],
      explanation: 'Italian conditional plus imperfect subjunctive becomes would plus past simple.',
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'c15-014',
      type: 'rewrite',
      prompt: 'Se avessi avuto più tempo, avrei finito.',
      answers: ['If I had had more time, I would have finished.', "If I'd had more time, I would have finished."],
      explanation: 'Third conditional. Note the double "had had": the auxiliary plus the verb "have".',
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'c15-015',
      type: 'rewrite',
      prompt: 'Vorrei essere più alto.',
      answers: ['I wish I were taller.', 'I wish I was taller.'],
      explanation: '"I wish" is how "vorrei" and "magari" are usually rendered.',
      errorTags: ['wish'],
      level: 'B2',
    },
    {
      id: 'c15-016',
      type: 'build',
      prompt: 'they/study/they/pass the exam',
      answers: [
        'If they studied, they would pass the exam.',
        'If they study, they will pass the exam.',
        'If they had studied, they would have passed the exam.',
      ],
      explanation: 'All three conditionals work here; what changes is how real you think it is.',
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'c15-017',
      type: 'transform',
      prompt: 'I did not revise, so I failed the test.',
      keyword: 'HAD',
      given: 'If I',
      answers: ['If I had revised, I would have passed the test.', 'If I had revised, I would not have failed the test.'],
      explanation: 'Turning a real past into a third conditional flips both halves.',
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'c15-018',
      type: 'transform',
      prompt: 'I am sorry I do not have a bigger house.',
      keyword: 'WISH',
      given: 'I',
      answers: ['I wish I had a bigger house.'],
      explanation: 'Wish about the present: past simple.',
      errorTags: ['wish'],
      level: 'B2',
    },
    {
      id: 'c15-019',
      type: 'choice',
      prompt: 'We ___ new staff if we expanded the branch.',
      answers: ['would need', 'will need', 'needed', 'would have needed'],
      options: ['would need', 'will need', 'needed', 'would have needed'],
      explanation: 'Second conditional: a hypothesis rather than a plan.',
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'c15-020',
      type: 'form',
      prompt: 'Under no ___ should you share this file.',
      root: 'CIRCUMSTANCE',
      answers: ['circumstances'],
      explanation: 'The fixed phrase is plural: under no circumstances.',
      errorTags: ['word-formation'],
      level: 'C1',
    },
    {
      id: 'verb-021',
      type: 'choice',
      prompt: 'If I ___ more time, I would read the whole paper.',
      answers: ['had', 'have', 'would have', 'will have'],
      options: ['had', 'have', 'would have', 'will have'],
      explanation: "Second conditional, an unreal present situation: if plus past simple, then would plus infinitive. Never \"would\" inside the if.",
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'verb-022',
      type: 'choice',
      prompt: 'If you ___ the deadline, email the secretary.',
      answers: ['miss', 'will miss', 'missed', 'would miss'],
      options: ['miss', 'will miss', 'missed', 'would miss'],
      explanation: "First conditional: if plus present simple. The future never goes into the \"if\" half.",
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'verb-023',
      type: 'choice',
      prompt: 'If I had revised more, I ___ that question.',
      answers: ['would have answered', 'would answer', 'had answered', 'will have answered'],
      options: ['would have answered', 'would answer', 'had answered', 'will have answered'],
      explanation: "Third conditional, the regret: if plus past perfect, then would have plus participle. It is about a past you cannot change.",
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'verb-024',
      type: 'choice',
      prompt: 'I wish I ___ how to code in Python.',
      answers: ['knew', 'know', 'would know', 'have known'],
      options: ['knew', 'know', 'would know', 'have known'],
      explanation: "After \"I wish\", a wish about the present takes the past simple. Same unreal logic as the second conditional.",
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'verb-025',
      type: 'choice',
      prompt: "Unless we ___ now, we'll miss the train.",
      answers: ['leave', "don't leave", 'will leave', 'left'],
      options: ['leave', "don't leave", 'will leave', 'left'],
      explanation: "\"Unless\" already means \"if not\": adding a negative doubles it. And it is still a first conditional, so the present.",
      errorTags: ['conditional'],
      level: 'B2',
    },
  ],
};
