import type { Unit } from '../types';

export const c16Gerund: Unit = {
  id: 'c16',
  stage: 'core',
  order: 16,
  title: 'Gerund or infinitive',
  summary: 'Which verbs take -ing, which take "to", and the ones where the meaning changes.',
  level: 'B2',
  errorTags: ['gerund-vs-infinitive', 'preposition-plus-gerund'],
  lesson: {
    rule: 'After a preposition it is always -ing; after another verb it depends on that verb, and a small group changes meaning depending on which one you pick.',
    schema: [
      { label: 'After any preposition', value: '-ing: good at explaining, thanks for calling' },
      { label: 'Gerund verbs', value: 'enjoy, avoid, mind, suggest, finish, keep, consider, deny, risk, postpone, practise' },
      { label: 'Infinitive verbs', value: 'decide, hope, agree, manage, refuse, promise, offer, afford, arrange, seem' },
      { label: 'Verb + object + to', value: 'want, expect, ask, tell, remind, persuade, warn, would like' },
      { label: 'As the subject', value: '-ing: Smoking is unhealthy' },
      { label: 'Purpose', value: 'to + infinitive: I went out to get some bread' },
      { label: 'Negative', value: 'not goes before: he promised not to tell' },
    ],
    examples: [
      {
        wrong: 'I look forward to hear from you.',
        right: 'I look forward to hearing from you.',
        note: 'Here "to" is a preposition, not an infinitive marker.',
      },
      {
        wrong: 'I went out for getting some bread.',
        right: 'I went out to get some bread.',
        note: 'Purpose takes the plain infinitive, never "for + -ing".',
      },
      {
        wrong: 'To smoke is unhealthy.',
        right: 'Smoking is unhealthy.',
        note: 'As the subject of a sentence, English uses the -ing form.',
      },
    ],
    traps: [
      'Italian uses the infinitive almost everywhere, so every -ing verb has to be learnt deliberately.',
      'remember to do is a future intention; remember doing is a memory. Same for forget, stop and regret.',
      'try to do is make an effort; try doing is give it a go as an experiment.',
      'need doing is a passive in disguise: "the report needs working on".',
      'Verbs of liking take -ing, but "would like" always takes the infinitive.',
    ],
  },
  cards: [
    {
      id: 'c16-001',
      type: 'choice',
      prompt: 'I look forward to ___ from you.',
      answers: ['hearing', 'hear', 'be hearing', 'have heard'],
      options: ['hearing', 'hear', 'be hearing', 'have heard'],
      explanation: '"To" is a preposition here, so it takes -ing. The standard close of a formal email.',
      errorTags: ['preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c16-002',
      type: 'choice',
      prompt: 'They decided ___ the project until September.',
      answers: ['to postpone', 'postponing', 'postpone', 'for postponing'],
      options: ['to postpone', 'postponing', 'postpone', 'for postponing'],
      explanation: '"Decide" takes the infinitive. Same family: agree, hope, manage, refuse, promise.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'c16-003',
      type: 'choice',
      prompt: "I don't mind ___ early when I have a nine o'clock lecture.",
      answers: ['getting up', 'to get up', 'get up', 'to getting up'],
      options: ['getting up', 'to get up', 'get up', 'to getting up'],
      explanation: '"Mind" always takes the gerund. So does "enjoy".',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'c16-004',
      type: 'choice',
      prompt: 'Remember ___ the attachment before you send it.',
      answers: ['to check', 'checking', 'check', 'of checking'],
      options: ['to check', 'checking', 'check', 'of checking'],
      explanation: '"Remember to do" is the intention. "Remember doing" would be a memory.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-005',
      type: 'choice',
      prompt: 'My job ___ travelling to foreign countries.',
      answers: ['involves', 'involves to', 'is involving', 'involve'],
      options: ['involves', 'involves to', 'is involving', 'involve'],
      explanation: '"Involve" takes the gerund directly.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-006',
      type: 'fill',
      prompt: 'It is too hot in here. Try ___ (open) the window.',
      answers: ['opening'],
      explanation: '"Try + -ing" means give it a go as an experiment. "Try to open" would mean making an effort.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-007',
      type: 'fill',
      prompt: 'Someone tried ___ (open) our back window last night.',
      answers: ['to open'],
      explanation: 'Here it is an attempt that failed, so the infinitive.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-008',
      type: 'fill',
      prompt: 'We regret ___ (inform) you that we cannot offer you the job.',
      answers: ['to inform'],
      explanation: 'The one formal exception: "regret to inform", "regret to say".',
      errorTags: ['gerund-vs-infinitive'],
      level: 'C1',
    },
    {
      id: 'c16-009',
      type: 'fill',
      prompt: 'She apologised ___ (call) at six in the morning.',
      answers: ['for calling'],
      explanation: 'apologise FOR plus -ing. The preposition is fixed.',
      errorTags: ['preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c16-010',
      type: 'fill',
      prompt: 'We could not prevent him ___ (leave).',
      answers: ['from leaving'],
      explanation: 'prevent somebody FROM doing something.',
      errorTags: ['preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c16-011',
      type: 'correct',
      prompt: 'He had promised to not tell anyone.',
      answers: ['He had promised not to tell anyone.'],
      explanation: 'The negative goes before "to", not between "to" and the verb.',
      errorTags: ['gerund-vs-infinitive', 'negative-form'],
      level: 'B2',
    },
    {
      id: 'c16-012',
      type: 'correct',
      prompt: 'I want that you read this report.',
      answers: ['I want you to read this report.'],
      explanation: 'English has no "want that" clause: want somebody TO do something.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'c16-013',
      type: 'correct',
      prompt: 'To find a job is not easy nowadays.',
      answers: ['Finding a job is not easy nowadays.', 'It is not easy to find a job nowadays.'],
      explanation: 'As a subject, use the -ing form, or start with the empty "it".',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-014',
      type: 'rewrite',
      prompt: 'Non vedo l\'ora di incontrarti.',
      answers: ['I look forward to meeting you.', "I'm looking forward to meeting you."],
      explanation: 'The standard formula, and it always takes -ing.',
      errorTags: ['preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c16-015',
      type: 'rewrite',
      prompt: 'Ho smesso di fumare due anni fa.',
      answers: ['I stopped smoking two years ago.', 'I gave up smoking two years ago.'],
      explanation: '"Stop doing" is to quit. "Stop to do" would mean pausing in order to do it.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-016',
      type: 'transform',
      prompt: 'He said he had not been in the office.',
      keyword: 'DENIED',
      given: 'He',
      answers: ['He denied being in the office.', 'He denied having been in the office.'],
      explanation: '"Deny" takes the gerund.',
      errorTags: ['gerund-vs-infinitive', 'reported-speech'],
      level: 'C1',
    },
    {
      id: 'c16-017',
      type: 'transform',
      prompt: 'It is a good idea to park here, said my friend.',
      keyword: 'SUGGESTED',
      given: 'My friend',
      answers: ['My friend suggested parking here.'],
      explanation: '"Suggest" takes the gerund, never "suggest me to".',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-018',
      type: 'build',
      prompt: 'the board/be interested in/meet/you',
      answers: ['The board is interested in meeting you.'],
      explanation: 'interested IN plus -ing when you plan to do something.',
      errorTags: ['preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c16-019',
      type: 'choice',
      prompt: 'I will be interested ___ what he has to say about it.',
      answers: ['to hear', 'in hearing', 'hearing', 'for hearing'],
      options: ['to hear', 'in hearing', 'hearing', 'for hearing'],
      explanation: 'With hear, know, see, read and learn, "interested" takes the infinitive.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'C1',
    },
    {
      id: 'c16-020',
      type: 'choice',
      prompt: 'I was sorry ___ about your loss.',
      answers: ['to hear', 'for hearing', 'hearing', 'of hearing'],
      options: ['to hear', 'for hearing', 'hearing', 'of hearing'],
      explanation: '"Sorry to hear" is the fixed condolence. "Sorry for" plus -ing apologises for what you did.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'c16-021',
      type: 'fill',
      prompt: 'I just cannot help ___ (laugh) when he tells that story.',
      answers: ['laughing'],
      explanation: '"Can\'t help" plus -ing means being unable to resist.',
      errorTags: ['gerund-vs-infinitive'],
      level: 'C1',
    },
    {
      id: 'c16-022',
      type: 'form',
      prompt: 'Her ___ to move abroad surprised everyone.',
      root: 'DECIDE',
      answers: ['decision'],
      explanation: 'decide becomes decision.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'verb-026',
      type: 'choice',
      prompt: 'I look forward to ___ from you.',
      answers: ['hearing', 'hear', 'be hearing', 'have heard'],
      options: ['hearing', 'hear', 'be hearing', 'have heard'],
      explanation: "Here \"to\" is a preposition, not an infinitive, so it takes the -ing form. It is the standard closing line of a formal email.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'verb-027',
      type: 'choice',
      prompt: 'They decided ___ the project until September.',
      answers: ['to postpone', 'postponing', 'postpone', 'for postponing'],
      options: ['to postpone', 'postponing', 'postpone', 'for postponing'],
      explanation: "\"Decide\" takes the infinitive with \"to\". Same family: agree, hope, manage, refuse, promise.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'verb-028',
      type: 'choice',
      prompt: "I don't mind ___ early when I have a lecture at nine.",
      answers: ['getting up', 'to get up', 'get up', 'to getting up'],
      options: ['getting up', 'to get up', 'get up', 'to getting up'],
      explanation: "\"Mind\" takes the gerund. Same family: enjoy, avoid, suggest, finish, keep, consider.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'verb-029',
      type: 'choice',
      prompt: 'Remember ___ the attachment before you send it.',
      answers: ['to check', 'checking', 'check', 'of checking'],
      options: ['to check', 'checking', 'check', 'of checking'],
      explanation: "\"Remember to do\" means do not forget to do it. \"Remember doing\" means you recall having done it. The meaning changes, not just the form.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'verb-030',
      type: 'choice',
      prompt: "He's good at ___ complex ideas simply.",
      answers: ['explaining', 'explain', 'to explain', 'explained'],
      options: ['explaining', 'explain', 'to explain', 'explained'],
      explanation: "After a preposition (\"at, of, in, about, for\") the verb always takes -ing.",
      errorTags: ['gerund-vs-infinitive', 'preposition'],
      level: 'B1',
    },
  ],
};
