import type { Unit } from '../types';

export const c17WordFormation: Unit = {
  id: 'c17',
  stage: 'core',
  order: 17,
  title: 'Word formation',
  summary: 'A whole section of the written exam: turn the root word into the right part of speech.',
  level: 'B2',
  errorTags: ['word-formation'],
  lesson: {
    rule: 'Read the gap first and decide what part of speech is missing, then pick the suffix; the negative prefix is a property of the word and has to be learnt with it.',
    schema: [
      { label: 'Noun, action or result', value: '-tion, -sion, -ment, -al, -ure: reduction, agreement, refusal, failure' },
      { label: 'Noun, person', value: '-er, -or, -ist, -ant: employer, investor, economist, applicant' },
      { label: 'Noun, quality', value: '-ity, -ness, -ence: ability, weakness, difference' },
      { label: 'Adjective', value: '-able, -ible, -ive, -ous, -ful, -less, -al: profitable, effective, careless' },
      { label: 'Verb', value: '-ise, -ify, -en: modernise, simplify, strengthen' },
      { label: 'Adverb', value: '-ly: significantly, gradually' },
      { label: 'Negative prefixes', value: 'un-, in-, im-, il-, ir-, dis-, mis-: unemployment, impossible, irregular' },
    ],
    examples: [
      {
        wrong: 'The ultimatum game enhances fair behave.',
        right: 'The ultimatum game enhances fair behaviour.',
        note: 'After an adjective the gap wants a noun.',
      },
      {
        wrong: 'The analysises showed a clear trend.',
        right: 'The analyses showed a clear trend.',
        note: 'analysis becomes analyses in the plural, pronounced with a final /iːz/.',
      },
      {
        wrong: 'He was disemployed for two years.',
        right: 'He was unemployed for two years.',
        note: 'The prefix belongs to the word: it is not chosen by logic.',
      },
    ],
    traps: [
      'Decide the part of speech before you decide the suffix. An adjective before a noun, an adverb after a verb.',
      'Some gaps need the negative form even though the root is positive. Read the whole sentence.',
      'Plural or singular matters: the exam marks "figure" wrong where "figures" is needed.',
      'Some roots change spelling: decide becomes decision, long becomes length, strong becomes strength.',
    ],
  },
  cards: [
    {
      id: 'c17-001',
      type: 'form',
      prompt: 'The ultimatum game is a ___ Economics game involving two players.',
      root: 'BEHAVE',
      answers: ['behavioural', 'behavioral'],
      explanation: 'The gap sits before a noun, so it wants an adjective: behavioural Economics.',
      errorTags: ['word-formation'],
      level: 'C1',
    },
    {
      id: 'c17-002',
      type: 'form',
      prompt: 'One player proposes how to split a sum and the other accepts or rejects the ___.',
      root: 'PROPOSE',
      answers: ['proposal'],
      explanation: 'After "the" the gap wants a noun: propose becomes proposal.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-003',
      type: 'form',
      prompt: 'Unlike the ___ game, the ultimatum game enhances fair behaviour.',
      root: 'DICTATE',
      answers: ['dictator'],
      explanation: 'The name of the game is the dictator game: the person who dictates.',
      errorTags: ['word-formation'],
      level: 'C1',
    },
    {
      id: 'c17-004',
      type: 'form',
      prompt: 'The ultimatum game has potential for ___.',
      root: 'REJECT',
      answers: ['rejection'],
      explanation: 'reject becomes rejection.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-005',
      type: 'form',
      prompt: 'Ecotourism is a type of ___ development.',
      root: 'SUSTAIN',
      answers: ['sustainable'],
      explanation: 'Before a noun the gap wants an adjective: sustainable development.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-006',
      type: 'form',
      prompt: 'The aim is to reduce the impact tourism has on ___ beautiful environments.',
      root: 'NATURE',
      answers: ['naturally'],
      explanation: 'It modifies the adjective "beautiful", so it wants an adverb.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-007',
      type: 'form',
      prompt: 'Any ___ destination can be harmed by increased levels of tourism.',
      root: 'TOUR',
      answers: ['tourist', 'touristic'],
      explanation: 'A destination for tourists: "tourist destination" is the usual collocation.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-008',
      type: 'form',
      prompt: 'Ecotourism must observe ___ friendly practices.',
      root: 'ENVIRONMENT',
      answers: ['environmentally'],
      explanation: 'It modifies the adjective "friendly": environmentally friendly.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-009',
      type: 'form',
      prompt: 'The rate of ___ fell to 7% last year.',
      root: 'EMPLOY',
      answers: ['unemployment'],
      explanation: 'A rate that falls is usually unemployment; the prefix is un-, not dis- or in-.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-010',
      type: 'form',
      prompt: 'The figures are almost ___ to read at this size.',
      root: 'POSSIBLE',
      answers: ['impossible'],
      explanation: 'Before p, the negative prefix is im-: impossible, impatient, improbable.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'c17-011',
      type: 'form',
      prompt: 'The results were highly ___ across the sample.',
      root: 'REGULAR',
      answers: ['irregular'],
      explanation: 'Before r, the prefix is ir-: irregular, irrelevant, irresponsible.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-012',
      type: 'form',
      prompt: 'We need a more ___ approach to the problem.',
      root: 'SYSTEM',
      answers: ['systematic'],
      explanation: 'system becomes systematic.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-013',
      type: 'form',
      prompt: 'The policy has proved highly ___.',
      root: 'EFFECT',
      answers: ['effective'],
      explanation: 'effect becomes effective, and the adverb is effectively.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'c17-014',
      type: 'form',
      prompt: 'Prices rose ___ in the second half of the year.',
      root: 'SIGNIFICANT',
      answers: ['significantly'],
      explanation: 'After a verb the gap wants an adverb.',
      errorTags: ['word-formation', 'esp-structure'],
      level: 'B1',
    },
    {
      id: 'c17-015',
      type: 'form',
      prompt: 'There is a clear ___ between the two data sets.',
      root: 'DIFFERENT',
      answers: ['difference'],
      explanation: 'different becomes difference. Note "difference between", not "of".',
      errorTags: ['word-formation', 'preposition'],
      level: 'B1',
    },
    {
      id: 'c17-016',
      type: 'form',
      prompt: 'The company is looking for a new financial ___.',
      root: 'ANALYSE',
      answers: ['analyst'],
      explanation: 'The person is an analyst, the thing is an analysis.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-017',
      type: 'form',
      prompt: 'The project turned out to be very ___.',
      root: 'PROFIT',
      answers: ['profitable'],
      explanation: 'profit becomes profitable; the opposite is unprofitable.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'c17-018',
      type: 'form',
      prompt: 'We must ___ the procedure before the audit.',
      root: 'SIMPLE',
      answers: ['simplify'],
      explanation: 'The gap follows a modal, so it wants a verb: simple becomes simplify.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-019',
      type: 'form',
      prompt: 'Her main ___ is the lack of experience abroad.',
      root: 'WEAK',
      answers: ['weakness'],
      explanation: 'weak becomes weakness. Its opposite is strength.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'c17-020',
      type: 'form',
      prompt: 'There were three ___ for the post.',
      root: 'APPLY',
      answers: ['applicants'],
      explanation: 'The person is an applicant, the document is an application. Note the plural.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-021',
      type: 'form',
      prompt: 'This measure will ___ the banking sector.',
      root: 'STRONG',
      answers: ['strengthen'],
      explanation: 'The suffix -en makes a verb out of an adjective: strengthen, shorten, widen.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'c17-022',
      type: 'form',
      prompt: 'The report contains several ___ about the method.',
      root: 'ASSUME',
      answers: ['assumptions'],
      explanation: 'assume becomes assumption, and "several" makes it plural.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'ff-022',
      type: 'choice',
      prompt: 'Word building: da "analyse" il sostantivo è ___.',
      answers: ['analysis', 'analyse', 'analysing', 'analysation'],
      options: ['analysis', 'analyse', 'analysing', 'analysation'],
      explanation: "The plural is \"analyses\", pronounced /uh-NAL-uh-seez/. Word building is a fixed part of the mock exam.",
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'ff-023',
      type: 'choice',
      prompt: 'Word building: da "able" il sostantivo è ___.',
      answers: ['ability', 'ableness', 'abilty', 'abling'],
      options: ['ability', 'ableness', 'abilty', 'abling'],
      explanation: "Recurring pattern: -able becomes -ability (able/ability, responsible/responsibility).",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'ff-024',
      type: 'choice',
      prompt: 'Word building: il contrario di "employment" è ___.',
      answers: ['unemployment', 'disemployment', 'inemployment', 'nonemploy'],
      options: ['unemployment', 'disemployment', 'inemployment', 'nonemploy'],
      explanation: "Negative prefixes are not interchangeable and are learnt with the word: un-, in-, im-, il-, ir-, dis-.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
  ],
};
