import type { Unit } from '../types';

export const c2PresentPerfectContinuous: Unit = {
  id: 'c2',
  stage: 'core',
  order: 2,
  title: 'Present perfect continuous',
  summary: 'The form that moves you towards B2: unfinished activity and how long.',
  level: 'B2',
  errorTags: ['present-perfect-continuous', 'for-since', 'state-verbs'],
  lesson: {
    rule: 'Use have been plus -ing when the activity is unfinished, or when you want to stress how long it has been going on; the simple form stresses the finished result instead.',
    schema: [
      { label: 'Form', value: 'have / has been + -ing' },
      { label: 'Unfinished activity', value: 'I have been working all day (maybe not finished)' },
      { label: 'Finished result', value: 'I have worked all day (now I am done)' },
      { label: 'How long', value: 'How long have you been studying English?' },
      { label: 'Recent activity with visible effect', value: 'It has been raining, the ground is wet' },
      { label: 'Never with', value: 'state verbs, and not with already or yet' },
    ],
    examples: [
      {
        wrong: 'I have been knowing her for years.',
        right: 'I have known her for years.',
        note: 'State verbs have no continuous form at all.',
      },
      {
        wrong: 'He has been reading that book, he has finished it.',
        right: 'He has read that book, he has finished it.',
        note: 'The continuous says it is not finished; the simple says it is.',
      },
      {
        wrong: 'How long are you waiting?',
        right: 'How long have you been waiting?',
        note: 'Italian uses the present here; English cannot.',
      },
    ],
    traps: [
      'Ask yourself whether the action is over. Over means simple, still going means continuous.',
      '"Have" in the sense of possession stays simple, but "have" meaning do an activity can take the continuous: I have been having too much coffee.',
      'In everyday native English the continuous is very common. If you can use it, use it.',
    ],
  },
  cards: [
    {
      id: 'c2-001',
      type: 'choice',
      prompt: 'My grandparents ___ well recently.',
      answers: ["haven't been feeling", "don't feel", "aren't feeling", 'have not felt well'],
      options: ["haven't been feeling", "don't feel", "aren't feeling", 'have not felt well'],
      explanation: '"Recently" plus an ongoing state of health: present perfect continuous.',
      errorTags: ['present-perfect-continuous', 'time-adverbial'],
      level: 'B2',
    },
    {
      id: 'c2-002',
      type: 'fill',
      prompt: 'We ___ (analyse) the data for two weeks and there is still no clear pattern.',
      answers: ['have been analysing', 'have been analyzing'],
      hint: 'The work is still going on as you speak.',
      explanation: 'Unfinished activity with a duration: the continuous is the natural choice.',
      errorTags: ['present-perfect-continuous', 'for-since'],
      level: 'B2',
    },
    {
      id: 'c2-003',
      type: 'fill',
      prompt: 'It ___ (rain) since the beginning of the week.',
      answers: ['has been raining'],
      explanation: 'Continuing weather with a starting point takes the continuous.',
      errorTags: ['present-perfect-continuous', 'for-since'],
      level: 'B1',
    },
    {
      id: 'c2-004',
      type: 'choice',
      prompt: 'He ___ that book you lent him, he has one more chapter to go.',
      answers: ['has been reading', 'has read', 'read', 'is reading'],
      options: ['has been reading', 'has read', 'read', 'is reading'],
      explanation: 'Not finished yet, so the continuous.',
      errorTags: ['present-perfect-continuous'],
      level: 'B2',
    },
    {
      id: 'c2-005',
      type: 'choice',
      prompt: 'She ___ that book already, you can borrow it.',
      answers: ['has read', 'has been reading', 'reads', 'is reading'],
      options: ['has read', 'has been reading', 'reads', 'is reading'],
      explanation: 'Finished, with a result available now, so the simple form.',
      errorTags: ['present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'c2-006',
      type: 'correct',
      prompt: 'I have been having a red car for three years.',
      answers: ['I have had a red car for three years.'],
      explanation: '"Have" meaning possession never takes the continuous.',
      errorTags: ['state-verbs', 'present-perfect-continuous'],
      level: 'B2',
    },
    {
      id: 'c2-007',
      type: 'correct',
      prompt: 'They have been wanting a house by the sea for years.',
      answers: ['They have wanted a house by the sea for years.'],
      explanation: '"Want" is a state verb. Same family: need, believe, prefer, belong.',
      errorTags: ['state-verbs'],
      level: 'B2',
    },
    {
      id: 'c2-008',
      type: 'rewrite',
      prompt: 'Stai aspettando da tanto?',
      answers: ['Have you been waiting long?', 'Have you been waiting for a long time?'],
      explanation: 'The Italian present continuous plus "da" becomes the English present perfect continuous.',
      errorTags: ['present-perfect-continuous', 'for-since'],
      level: 'B1',
    },
    {
      id: 'c2-009',
      type: 'rewrite',
      prompt: 'Sto pulendo tutto il giorno.',
      answers: ['I have been cleaning all day.', "I've been cleaning all day."],
      explanation: 'The day is not over and the activity is not finished.',
      errorTags: ['present-perfect-continuous'],
      level: 'B1',
    },
    {
      id: 'c2-010',
      type: 'rewrite',
      prompt: 'Gioco a tennis da quando ero bambino.',
      answers: ['I have been playing tennis since I was a child.', 'I have played tennis since I was a child.'],
      explanation: 'After "since" the clause goes to the past simple, because being a child is a finished moment.',
      errorTags: ['for-since', 'present-perfect-continuous'],
      level: 'B2',
    },
    {
      id: 'c2-011',
      type: 'build',
      prompt: 'how long/it/rain?',
      answers: ['How long has it been raining?'],
      explanation: 'Duration of something still happening: continuous.',
      errorTags: ['present-perfect-continuous', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c2-012',
      type: 'build',
      prompt: 'they/play/in the same band/for six years',
      answers: ['They have been playing in the same band for six years.'],
      explanation: 'The continuous says they are still playing; the simple would leave that open.',
      errorTags: ['present-perfect-continuous', 'for-since'],
      level: 'B2',
    },
    {
      id: 'c2-013',
      type: 'transform',
      prompt: 'I started waiting an hour ago and I am still here.',
      keyword: 'BEEN',
      given: 'I have',
      answers: ['I have been waiting for an hour.'],
      explanation: 'Started in the past, still going: the continuous with "for".',
      errorTags: ['present-perfect-continuous', 'for-since'],
      level: 'B2',
    },
    {
      id: 'c2-014',
      type: 'choice',
      prompt: 'The price of coffee ___ since January, and it is still falling.',
      answers: ['has been dropping', 'has dropped', 'dropped', 'drops'],
      options: ['has been dropping', 'has dropped', 'dropped', 'drops'],
      explanation: 'Still falling as we speak, so the continuous. Exactly the distinction the ESP section tests.',
      errorTags: ['esp-structure', 'present-perfect-continuous'],
      level: 'B2',
    },
    {
      id: 'c2-015',
      type: 'fill',
      prompt: 'You look exhausted. ___ you ___ (work) all night?',
      answers: ['Have / been working', 'Have you been working'],
      explanation: 'Visible present effect of a long activity: the continuous.',
      errorTags: ['present-perfect-continuous', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c2-016',
      type: 'correct',
      prompt: 'I have been finishing my report already.',
      answers: ['I have already finished my report.'],
      explanation: 'The continuous is never used with "already" or "yet", and finishing is by definition complete.',
      errorTags: ['present-perfect-continuous', 'time-adverbial'],
      level: 'B2',
    },
    {
      id: 'c2-017',
      type: 'vocab',
      prompt: 'BERE TROPPI CAFFE ULTIMAMENTE (dillo di te)',
      answers: ['I have been having too much coffee recently.', 'I have been drinking too much coffee recently.'],
      explanation: '"Have" meaning to consume does take the continuous, unlike "have" meaning to own.',
      errorTags: ['present-perfect-continuous', 'state-verbs'],
      level: 'B2',
    },
    {
      id: 'c2-018',
      type: 'form',
      prompt: 'The market has shown a slow but steady ___.',
      root: 'RECOVER',
      answers: ['recovery'],
      explanation: 'recover becomes recovery, the noun for an upward trend after a fall.',
      errorTags: ['word-formation', 'esp-trend-vocabulary'],
      level: 'B2',
    },
  ],
};
