import type { Unit } from '../types';

export const c4Narrative: Unit = {
  id: 'c4',
  stage: 'core',
  order: 4,
  title: 'Narrative tenses: past continuous and used to',
  summary: 'The background of a story, and habits that are over.',
  level: 'B1',
  errorTags: ['narrative-tense', 'used-to'],
  lesson: {
    rule: 'The past simple moves a story forward, the past continuous sets the scene around it, and "used to" plus the bare infinitive describes a past habit that has stopped.',
    schema: [
      { label: 'Main events, in order', value: 'past simple: she fell in a puddle' },
      { label: 'Action in progress, interrupted', value: 'past continuous: she was playing football' },
      { label: 'What someone was doing at a time', value: 'What were you doing at eleven last night?' },
      { label: 'Past habit, now over', value: 'used to + bare infinitive: I used to smoke' },
      { label: 'Question and negative of used to', value: 'did you use to...? / did not use to...' },
      { label: 'Do not confuse', value: 'be or get used to + -ing = to be, or become, accustomed' },
    ],
    examples: [
      {
        wrong: 'While I read my notes, the lecturer changed the slide.',
        right: 'While I was reading my notes, the lecturer changed the slide.',
        note: '"While" plus a long action calls for the past continuous.',
      },
      {
        wrong: 'Did you used to wear a uniform?',
        right: 'Did you use to wear a uniform?',
        note: 'Once "did" carries the past, "used" goes back to "use".',
      },
      {
        wrong: 'I was used to go to Brighton every summer.',
        right: 'I used to go to Brighton every summer.',
        note: '"Be used to" means accustomed and takes -ing. Different structure, different meaning.',
      },
    ],
    traps: [
      'The Italian imperfetto is not always a past continuous: "abitavo a Roma" is "I lived in Rome".',
      '"Used to" exists only in the past. For a present habit use the present simple.',
      'Without "used to" a sentence can be ambiguous: "we went to Greece" sounds like once, "we used to go to Greece" means regularly.',
      'State verbs have no continuous: "I was having a grey car" is wrong.',
    ],
  },
  cards: [
    {
      id: 'c4-001',
      type: 'choice',
      prompt: 'The children ___ breakfast when I woke up.',
      answers: ['were preparing', 'have prepared', 'prepare', 'had prepared'],
      options: ['were preparing', 'have prepared', 'prepare', 'had prepared'],
      explanation: 'An action in progress at a moment in the past: past continuous.',
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'c4-002',
      type: 'choice',
      prompt: 'My mother called while I ___ your message.',
      answers: ['was reading', 'reading', 'have read', 'read'],
      options: ['was reading', 'reading', 'have read', 'read'],
      explanation: 'The long action takes the continuous, the short one that interrupts takes the past simple.',
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'c4-003',
      type: 'fill',
      prompt: 'What ___ you ___ (do) at eleven o\'clock last night?',
      answers: ['were / doing', 'were you doing'],
      explanation: 'Asking what somebody was in the middle of: past continuous.',
      errorTags: ['narrative-tense', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c4-004',
      type: 'fill',
      prompt: 'When I was a child we ___ (go) to the seaside every summer.',
      answers: ['used to go', 'went'],
      explanation: '"Used to" makes the repetition explicit; the past simple alone would sound like a single trip.',
      errorTags: ['used-to'],
      level: 'B1',
    },
    {
      id: 'c4-005',
      type: 'correct',
      prompt: 'She didn\'t used to like fish.',
      answers: ["She didn't use to like fish."],
      explanation: 'With "did", "used" loses its -d.',
      errorTags: ['used-to', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'c4-006',
      type: 'correct',
      prompt: 'I am used to smoke, but I stopped last year.',
      answers: ['I used to smoke, but I stopped last year.'],
      explanation: '"Used to + infinitive" is the past habit. "Be used to + -ing" means accustomed.',
      errorTags: ['used-to'],
      level: 'B2',
    },
    {
      id: 'c4-007',
      type: 'choice',
      prompt: 'It took a while, but now I ___ getting up at six.',
      answers: ['am used to', 'used to', 'use to', 'am using to'],
      options: ['am used to', 'used to', 'use to', 'am using to'],
      explanation: 'Accustomed to something: be used to plus -ing.',
      errorTags: ['used-to', 'preposition-plus-gerund'],
      level: 'B2',
    },
    {
      id: 'c4-008',
      type: 'build',
      prompt: 'the projector/break down/while/the professor/explain/the model',
      answers: ['The projector broke down while the professor was explaining the model.'],
      explanation: 'Short interrupting action in the past simple, long background in the continuous.',
      errorTags: ['narrative-tense', 'phrasal-verb'],
      level: 'B2',
    },
    {
      id: 'c4-009',
      type: 'rewrite',
      prompt: 'Da bambino giocavo a calcio ogni giorno.',
      answers: ['As a child I used to play football every day.', 'When I was a child I used to play football every day.'],
      explanation: 'A habit that has stopped: "used to".',
      errorTags: ['used-to'],
      level: 'B1',
    },
    {
      id: 'c4-010',
      type: 'rewrite',
      prompt: 'Stavo lavorando quando è arrivata la notizia.',
      answers: ['I was working when the news arrived.', 'I was working when the news came.'],
      explanation: '"News" takes a singular verb.',
      errorTags: ['narrative-tense', 'uncountable'],
      level: 'B1',
    },
    {
      id: 'c4-011',
      type: 'transform',
      prompt: 'I played tennis regularly when I was younger, but not any more.',
      keyword: 'USED',
      given: 'I',
      answers: ['I used to play tennis when I was younger.'],
      explanation: 'A stopped habit is exactly what "used to" is for.',
      errorTags: ['used-to'],
      level: 'B1',
    },
    {
      id: 'c4-012',
      type: 'correct',
      prompt: 'I was having a grey car when I was a student.',
      answers: ['I had a grey car when I was a student.'],
      explanation: '"Have" meaning possession never takes the continuous.',
      errorTags: ['state-verbs', 'narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c4-013',
      type: 'fill',
      prompt: 'The price of oil ___ (rise) gradually while that of gas remained stable.',
      answers: ['was rising'],
      explanation: 'Two things going on at once in the past: the continuous sets them side by side.',
      errorTags: ['narrative-tense', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c4-014',
      type: 'form',
      prompt: 'There was a gradual ___ in oil prices.',
      root: 'RISE',
      answers: ['rise'],
      explanation: '"Rise" is both the verb and the noun. "Raise" is a different, transitive verb.',
      errorTags: ['word-formation', 'esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'verb-001',
      type: 'choice',
      prompt: 'While I ___ my notes, the lecturer changed the slide.',
      answers: ['was reading', 'read', 'have read', 'had read'],
      options: ['was reading', 'read', 'have read', 'had read'],
      explanation: "Past continuous for the long action interrupted by a short one. Standard pattern: \"while\" plus past continuous, then past simple.",
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'verb-003',
      type: 'choice',
      prompt: 'I ___ take the bus to campus, but now I cycle.',
      answers: ['used to', 'was used to', 'use to', 'am used to'],
      options: ['used to', 'was used to', 'use to', 'am used to'],
      explanation: "\"Used to + infinitive\" is a past habit that is over. Do not confuse it with \"to be used to + -ing\", which means to be accustomed to something.",
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'verb-005',
      type: 'choice',
      prompt: 'The professor was explaining the model when the projector ___.',
      answers: ['broke down', 'was breaking down', 'had broken down', 'breaks down'],
      options: ['broke down', 'was breaking down', 'had broken down', 'breaks down'],
      explanation: "The short action that interrupts takes the past simple. Note the phrasal verb too: \"break down\" means to stop working.",
      errorTags: ['narrative-tense', 'phrasal-verb'],
      level: 'B1',
    },
  ],
};
