import type { Unit } from '../types';

export const c5PastPerfect: Unit = {
  id: 'c5',
  stage: 'core',
  order: 5,
  title: 'Past perfect and past perfect continuous',
  summary: 'The flashback: what had already happened before the moment you are describing.',
  level: 'B2',
  errorTags: ['narrative-tense', 'irregular-verb'],
  lesson: {
    rule: 'When you are telling a story in the past, anything that happened earlier than your starting point goes into the past perfect, and if you want to stress how long it had been going on, use had been plus -ing.',
    schema: [
      { label: 'Form', value: 'had + past participle, for every person' },
      { label: 'Earlier than the past event', value: 'When we arrived, the train had left' },
      { label: 'Reason for a past state', value: 'I was tired because I had not slept' },
      { label: 'Duration up to a past point', value: 'had been + -ing: she had been waiting for hours' },
      { label: 'With already and yet', value: 'I realised I had already met her' },
      { label: 'Also used in', value: 'the third conditional and reported speech' },
    ],
    examples: [
      {
        wrong: 'When we arrived, the seminar has already started.',
        right: 'When we arrived, the seminar had already started.',
        note: 'Talking in the past means the flashback is past perfect, not present perfect.',
      },
      {
        wrong: 'She was waiting for three hours when the results came out.',
        right: 'She had been waiting for three hours when the results came out.',
        note: 'A duration completed before another past event needs "had been waiting".',
      },
      {
        wrong: 'I was sure I have seen him before.',
        right: 'I was sure I had seen him before.',
        note: 'The main verb is in the past, so everything earlier moves back one step.',
      },
    ],
    traps: [
      'Every present perfect in a present story becomes a past perfect in a past story. Practise the pair: "I am tired because I have not eaten" becomes "I was tired because I had not eaten".',
      'Do not use the past perfect everywhere. If the order is already clear from the sentence, the past simple is enough.',
      'State verbs have no past perfect continuous.',
      'The past perfect continuous must be anchored to another moment in the past; on its own it sounds unfinished.',
    ],
  },
  cards: [
    {
      id: 'c5-001',
      type: 'choice',
      prompt: 'They ___ their homework, so they started playing.',
      answers: ['had finished', 'have finished', 'had finishing', 'were finishing'],
      options: ['had finished', 'have finished', 'had finishing', 'were finishing'],
      explanation: 'Finished before the next past event: past perfect.',
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'c5-002',
      type: 'choice',
      prompt: 'When I closed the door I realised I ___ my keys on the table.',
      answers: ['had forgotten', 'forgot', 'have forgotten', 'was forgetting'],
      options: ['had forgotten', 'forgot', 'have forgotten', 'was forgetting'],
      explanation: 'The forgetting happened before the realising.',
      errorTags: ['narrative-tense', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'c5-003',
      type: 'choice',
      prompt: 'She ___ for three hours when the results finally came out.',
      answers: ['had been waiting', 'was waiting', 'has been waiting', 'waited'],
      options: ['had been waiting', 'was waiting', 'has been waiting', 'waited'],
      explanation: 'Duration running up to a past moment: past perfect continuous.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-004',
      type: 'fill',
      prompt: 'Lisa was very happy when they hired her because she ___ (look for) a job for a long time.',
      answers: ['had been looking for', 'had looked for'],
      explanation: 'A long search that ended at the moment of hiring: the continuous stresses the length.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-005',
      type: 'fill',
      prompt: 'Angie ___ (drive) for about half an hour when the police stopped her.',
      answers: ['had been driving'],
      explanation: 'Classic pattern: had been plus -ing, then "when" plus past simple.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-006',
      type: 'fill',
      prompt: 'It ___ (rain) for days, so the ground was soggy.',
      answers: ['had been raining'],
      explanation: 'The past version of "it has been raining, so the ground is soggy".',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-007',
      type: 'correct',
      prompt: 'Tom could not get on the plane because he has forgotten his passport.',
      answers: ['Tom could not get on the plane because he had forgotten his passport.'],
      explanation: 'The whole story is in the past, so the earlier event is past perfect.',
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'c5-008',
      type: 'correct',
      prompt: 'Although she had not played tennis for months, Lisa has won the match.',
      answers: ['Although she had not played tennis for months, Lisa won the match.'],
      explanation: 'The main event goes in the past simple; only the flashback is past perfect.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-009',
      type: 'rewrite',
      prompt: 'Ero stanco perché non avevo dormito.',
      answers: ['I was tired because I had not slept.', "I was tired because I hadn't slept."],
      explanation: 'Italian trapassato prossimo becomes the English past perfect, one to one.',
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'c5-010',
      type: 'rewrite',
      prompt: 'Quando siamo arrivati al concerto, l\'orchestra suonava già da dieci minuti.',
      answers: [
        'When we arrived at the concert, the orchestra had already been playing for ten minutes.',
        'When we got to the concert, the orchestra had already been playing for ten minutes.',
      ],
      explanation: 'Duration up to the moment of arrival: past perfect continuous with "already".',
      errorTags: ['narrative-tense', 'for-since'],
      level: 'B2',
    },
    {
      id: 'c5-011',
      type: 'build',
      prompt: 'we/go out/for a while/when/she/decide/to break up with me',
      answers: ['We had been going out for a while when she decided to break up with me.'],
      explanation: 'A relationship running up to a past decision: past perfect continuous.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-012',
      type: 'transform',
      prompt: 'She started working there in 2015 and left in 2020.',
      keyword: 'HAD',
      given: 'By 2020 she',
      answers: ['By 2020 she had worked there for five years.', 'By 2020 she had been working there for five years.'],
      explanation: '"By" plus a past date sets the point that the flashback measures up to.',
      errorTags: ['narrative-tense', 'for-since'],
      level: 'B2',
    },
    {
      id: 'c5-013',
      type: 'choice',
      prompt: 'Lisa realised that someone ___ her, though they were no longer there.',
      answers: ['had been following', 'was following', 'has been following', 'followed'],
      options: ['had been following', 'was following', 'has been following', 'followed'],
      explanation: 'The continuous past perfect says it may be over but it had been going on: the idiomatic choice.',
      errorTags: ['narrative-tense'],
      level: 'C1',
    },
    {
      id: 'c5-014',
      type: 'fill',
      prompt: 'Before the crash, there ___ (be) a steady increase in house prices.',
      answers: ['had been'],
      explanation: 'The ESP structure "there + be + adjective + noun" in the past perfect, to sequence changes.',
      errorTags: ['esp-structure', 'narrative-tense'],
      level: 'B2',
    },
    {
      id: 'c5-015',
      type: 'form',
      prompt: 'Cruise-liner tourism had seen a remarkable ___ before 1912.',
      root: 'GROW',
      answers: ['growth'],
      explanation: 'grow becomes growth, uncountable.',
      errorTags: ['word-formation', 'esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'verb-002',
      type: 'choice',
      prompt: 'When we arrived, the seminar ___ already ___.',
      answers: ['had / started', 'has / started', 'was / starting', 'did / start'],
      options: ['had / started', 'has / started', 'was / starting', 'did / start'],
      explanation: "Past perfect: something that happened before another past event. It is the Italian trapassato prossimo.",
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'verb-004',
      type: 'choice',
      prompt: 'She ___ for three hours when the results finally came out.',
      answers: [
        'had been waiting',
        'was waiting',
        'has been waiting',
        'waited',
      ],
      options: ['had been waiting', 'was waiting', 'has been waiting', 'waited'],
      explanation: "Past perfect continuous: the duration of an activity up to a point in the past. \"For three hours\" plus a second past event calls for it.",
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
  ],
};
