import type { Unit } from '../types';

export const c6FutureBasic: Unit = {
  id: 'c6',
  stage: 'core',
  order: 6,
  title: 'The future: will, going to, present continuous',
  summary: 'Three futures, chosen by how settled the plan already is.',
  level: 'B1',
  errorTags: ['future-form'],
  lesson: {
    rule: 'Will is for what you decide as you speak, going to for an intention you already had or a prediction you can see coming, and the present continuous for an arrangement already in the diary.',
    schema: [
      { label: 'Instant decision', value: "will: I'll call him" },
      { label: 'Offer, promise, request', value: "will: I'll carry your bags. Will you marry me?" },
      { label: 'Prediction from an opinion', value: 'will: interest rates will rise' },
      { label: 'Prediction from evidence', value: "going to: look at those clouds, it's going to rain" },
      { label: 'Intention already formed', value: "going to: I'm going to buy a new car" },
      { label: 'Fixed arrangement', value: 'present continuous: I am meeting him at four' },
      { label: 'Timetable', value: 'present simple: the train leaves at six' },
    ],
    examples: [
      {
        wrong: "I'll go to London this summer, it is all booked.",
        right: 'I am going to London this summer, it is all booked.',
        note: '"Will" is not used for plans that are already arranged.',
      },
      {
        wrong: 'Look at those clouds, it will rain.',
        right: 'Look at those clouds, it is going to rain.',
        note: 'There is evidence in front of you, so "going to".',
      },
      {
        wrong: 'A: What are you doing this weekend? B: I will stay at home.',
        right: 'A: What are you doing this weekend? B: I am staying at home.',
        note: 'An existing plan takes the present continuous.',
      },
    ],
    traps: [
      '"Will" originally meant "want", which is why it fits offers, promises and instant decisions but not arrangements.',
      'Italian uses one future for everything, so the choice has to be made deliberately each time.',
      '"Shall" survives mainly in offers and suggestions: "Shall I open the window?".',
      '"It is raining" is now, "it is going to rain" is a prediction. Keep them apart.',
    ],
  },
  cards: [
    {
      id: 'c6-001',
      type: 'choice',
      prompt: 'Her parents ___ for dinner tonight, they told us last week.',
      answers: ['are coming', 'will come', 'come', 'are going to come'],
      options: ['are coming', 'will come', 'come', 'are going to come'],
      explanation: 'A fixed arrangement takes the present continuous.',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-002',
      type: 'choice',
      prompt: "We ___ with my sister when we're in London.",
      answers: ['are staying', 'stayed', 'have stayed', 'stay'],
      options: ['are staying', 'stayed', 'have stayed', 'stay'],
      explanation: 'An arrangement already made: present continuous.',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-003',
      type: 'choice',
      prompt: "I'm hungry! ___ a sandwich.",
      answers: ["I'll make", 'I make', 'I making', 'I am making'],
      options: ["I'll make", 'I make', 'I making', 'I am making'],
      explanation: 'A decision made at the moment of speaking: "will".',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-004',
      type: 'choice',
      prompt: "I can't come to your party, ___ on Saturday.",
      answers: ["I'm working", 'I work', "I'll work", 'I will be work'],
      options: ["I'm working", 'I work', "I'll work", 'I will be work'],
      explanation: 'A work commitment already in the diary: present continuous.',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-005',
      type: 'fill',
      prompt: 'That bag looks heavy. ___ (I help) you.',
      answers: ["I'll help", 'I will help'],
      explanation: 'An offer made on the spot: "will".',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-006',
      type: 'fill',
      prompt: 'She ___ (buy) a flat, she has been saving for two years.',
      answers: ['is going to buy'],
      explanation: 'An intention formed some time ago: "going to".',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-007',
      type: 'correct',
      prompt: 'What will you do this weekend? I will visit my grandmother, it is arranged.',
      answers: ['What are you doing this weekend? I am visiting my grandmother, it is arranged.'],
      explanation: 'Both halves describe arrangements, so both take the present continuous.',
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'c6-008',
      type: 'correct',
      prompt: 'I think it is going to rain, but I am not sure.',
      answers: ['I think it will rain, but I am not sure.'],
      explanation: '"I think" signals an opinion, so "will". "Going to" would claim visible evidence.',
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'c6-009',
      type: 'rewrite',
      prompt: 'Domani vado a Roma, ho già il biglietto.',
      answers: ['I am going to Rome tomorrow, I already have the ticket.', "I'm going to Rome tomorrow, I've already got the ticket."],
      explanation: 'The Italian present with future meaning becomes the English present continuous.',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-010',
      type: 'rewrite',
      prompt: 'Ti prometto che ti chiamerò.',
      answers: ['I promise I will call you.', "I promise I'll call you."],
      explanation: 'A promise is the classic use of "will".',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-011',
      type: 'build',
      prompt: 'you/spend/the day/with your brother/tomorrow?',
      answers: ['Are you spending the day with your brother tomorrow?', 'Are you going to spend the day with your brother tomorrow?'],
      explanation: 'A question about an arrangement: present continuous.',
      errorTags: ['future-form', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c6-012',
      type: 'build',
      prompt: 'we/believe/there/be/a drop in car sales',
      answers: ['We believe there will be a drop in car sales.'],
      explanation: 'A prediction based on opinion takes "will", in the ESP structure "there will be a drop in".',
      errorTags: ['future-form', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c6-013',
      type: 'choice',
      prompt: '___ I open the window?',
      answers: ['Shall', 'Will', 'Do', 'Am'],
      options: ['Shall', 'Will', 'Do', 'Am'],
      explanation: '"Shall I" is the standard way to make an offer or suggestion.',
      errorTags: ['future-form', 'modal'],
      level: 'B2',
    },
    {
      id: 'c6-014',
      type: 'transform',
      prompt: 'I have decided to look for a new job.',
      keyword: 'GOING',
      given: 'I am',
      answers: ['I am going to look for a new job.'],
      explanation: 'A decision already taken is exactly what "going to" expresses.',
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'c6-015',
      type: 'fill',
      prompt: 'The market ___ (crash) unless we act quickly.',
      answers: ['is going to crash', 'will crash'],
      explanation: 'A prediction about a threat. Note that "unless" itself never takes the future.',
      errorTags: ['future-form', 'future-time-clause'],
      level: 'B2',
    },
    {
      id: 'c6-016',
      type: 'form',
      prompt: 'Analysts expect a sharp ___ in demand.',
      root: 'REDUCE',
      answers: ['reduction'],
      explanation: 'reduce becomes reduction, like produce and production.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'verb-006',
      type: 'choice',
      prompt: "Look at those clouds: it ___ rain.",
      answers: ['is going to', 'will', 'is raining', 'shall'],
      options: ['is going to', 'will', 'is raining', 'shall'],
      explanation: "\"Going to\" when there is present evidence of what is about to happen. \"Will\" is the prediction based on an opinion.",
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'verb-007',
      type: 'choice',
      prompt: "I ___ my supervisor at four, it's already in the diary.",
      answers: ['am meeting', 'will meet', 'meet', 'will be met'],
      options: ['am meeting', 'will meet', 'meet', 'will be met'],
      explanation: "Present continuous for arrangements already fixed. It is the most natural form for an organised future.",
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'verb-008',
      type: 'choice',
      prompt: "That bag looks heavy: I ___ you.",
      answers: ["'ll help", "'m going to help", 'help', "'m helping"],
      options: ["'ll help", "'m going to help", 'help', "'m helping"],
      explanation: "\"Will\" for a decision made on the spot. \"Going to\" would imply you had already thought about it.",
      errorTags: ['future-form'],
      level: 'B1',
    },
  ],
};
