import type { Unit } from '../types';

export const c7FuturePerfect: Unit = {
  id: 'c7',
  stage: 'core',
  order: 7,
  title: 'Future continuous and future perfect',
  summary: 'What will be going on, and what will already be finished.',
  level: 'B2',
  errorTags: ['future-form'],
  lesson: {
    rule: 'Will be plus -ing describes what will be in progress at a future moment; will have plus the past participle describes what will already be complete by a future deadline.',
    schema: [
      { label: 'In progress at a future time', value: 'This time tomorrow I will be flying to Delhi' },
      { label: 'Planned or foreseeable event', value: 'When will you be arriving?' },
      { label: 'Polite offer or enquiry', value: 'Will you be chairing the meeting?' },
      { label: 'Complete by a deadline', value: 'By 2028 I will have graduated' },
      { label: 'Needs a time marker', value: 'by then, by June, this time next week' },
      { label: 'With already and yet', value: "By the time you get here, we'll have already left" },
    ],
    examples: [
      {
        wrong: 'This time next week I will work in Delhi.',
        right: 'This time next week I will be working in Delhi.',
        note: 'A precise future moment needs the action in progress.',
      },
      {
        wrong: 'By June I will finish the thesis.',
        right: 'By June I will have finished the thesis.',
        note: '"By" marks a deadline, which calls for the future perfect.',
      },
      {
        wrong: 'No need to cook for me, I will have my dinner by then already.',
        right: 'No need to cook for me, I will have had my dinner by then.',
        note: 'The future perfect of "have" is "will have had".',
      },
    ],
    traps: [
      'The Italian futuro anteriore matches the future perfect closely, but in English it carries no speculative sense: "sarà andato via" is "he must have left", not "he will have left".',
      'The future continuous is also a politeness device at work: "Will you be needing anything else?".',
      '"By" is a deadline, "until" is a duration: submit by Friday, wait until Friday.',
    ],
  },
  cards: [
    {
      id: 'c7-001',
      type: 'choice',
      prompt: 'By the end of the year I ___ all the first-term exams.',
      answers: ['will have passed', 'will pass', 'am passing', 'would pass'],
      options: ['will have passed', 'will pass', 'am passing', 'would pass'],
      explanation: '"By" plus a future time marks a deadline: future perfect.',
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'c7-002',
      type: 'choice',
      prompt: 'This time tomorrow I ___ on the beach.',
      answers: ['will be relaxing', 'will relax', 'am relaxing', 'will have relaxed'],
      options: ['will be relaxing', 'will relax', 'am relaxing', 'will have relaxed'],
      explanation: 'In progress at a precise future moment: future continuous.',
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'c7-003',
      type: 'fill',
      prompt: 'By 2030 car sales ___ (rise) by six per cent.',
      answers: ['will have risen'],
      explanation: 'The projection formula of the ESP section: by plus a year, then the future perfect.',
      errorTags: ['future-form', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c7-004',
      type: 'fill',
      prompt: 'Car sales ___ (rise) slowly over the next few years.',
      answers: ['will be rising'],
      explanation: 'A trend in progress across a future period: future continuous.',
      errorTags: ['future-form', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'c7-005',
      type: 'fill',
      prompt: 'By the time you get here, we ___ (already leave).',
      answers: ['will have already left', "'ll have already left"],
      explanation: '"Already" sits between "have" and the participle.',
      errorTags: ['future-form', 'time-adverbial'],
      level: 'B2',
    },
    {
      id: 'c7-006',
      type: 'fill',
      prompt: 'I ___ (not finish) the report in time for tomorrow\'s meeting.',
      answers: ["won't have finished", 'will not have finished'],
      explanation: 'Negative future perfect, often with "yet" at the end.',
      errorTags: ['future-form', 'negative-form'],
      level: 'B2',
    },
    {
      id: 'c7-007',
      type: 'choice',
      prompt: '___ you ___ an interpreter for the trip, sir?',
      answers: ['Will / be hiring', 'Will / hire', 'Do / hire', 'Are / hire'],
      options: ['Will / be hiring', 'Will / hire', 'Do / hire', 'Are / hire'],
      explanation: 'The future continuous used as a courtesy form in professional English.',
      errorTags: ['future-form'],
      level: 'C1',
    },
    {
      id: 'c7-008',
      type: 'correct',
      prompt: 'Applications must be submitted until 15th July.',
      answers: ['Applications must be submitted by 15th July.'],
      explanation: '"By" is a deadline. "Until" would mean you keep submitting the whole time.',
      errorTags: ['preposition', 'future-form'],
      level: 'B2',
    },
    {
      id: 'c7-009',
      type: 'rewrite',
      prompt: 'Per allora avrò già finito.',
      answers: ['By then I will have already finished.', "By then I'll have already finished."],
      explanation: 'The Italian futuro anteriore maps onto the future perfect here.',
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'c7-010',
      type: 'rewrite',
      prompt: 'Domani a quest\'ora starò facendo l\'esame.',
      answers: ['This time tomorrow I will be taking the exam.', "This time tomorrow I'll be sitting the exam."],
      explanation: 'In progress at a named future moment, and you take or sit an exam, you do not "support" it.',
      errorTags: ['future-form', 'false-friend'],
      level: 'B2',
    },
    {
      id: 'c7-011',
      type: 'transform',
      prompt: 'I will finish the project before June.',
      keyword: 'HAVE',
      given: 'By June I',
      answers: ['By June I will have finished the project.'],
      explanation: '"By" plus a deadline turns the simple future into the future perfect.',
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'c7-012',
      type: 'build',
      prompt: 'when/you/land/in Beijing?',
      answers: ['When will you be landing in Beijing?', 'When will you land in Beijing?'],
      explanation: 'For a foreseeable, planned event the future continuous sounds more natural.',
      errorTags: ['future-form', 'question-form'],
      level: 'B2',
    },
    {
      id: 'c7-013',
      type: 'form',
      prompt: 'The board expects a further ___ of the market next year.',
      root: 'EXPAND',
      answers: ['expansion'],
      explanation: 'expand becomes expansion.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'verb-010',
      type: 'choice',
      prompt: 'By the end of the year I ___ all the exams of the first term.',
      answers: ['will have passed', 'will pass', 'am passing', 'would pass'],
      options: ['will have passed', 'will pass', 'am passing', 'would pass'],
      explanation: "Future perfect: an action that will be complete by a future point. The signal is \"by\" plus a future time.",
      errorTags: ['future-form'],
      level: 'B2',
    },
  ],
};
