import type { Unit } from '../types';

export const c8FutureClauses: Unit = {
  id: 'c8',
  stage: 'core',
  order: 8,
  title: 'Future time and condition clauses',
  summary: 'The rule Italian speakers break most often: no "will" after when, if, until.',
  level: 'B1',
  errorTags: ['future-time-clause', 'future-form'],
  lesson: {
    rule: 'After a conjunction of time or condition English never uses will: the clause takes a present tense, even though Italian puts a future there.',
    schema: [
      { label: 'Condition', value: 'if, unless, in case, as long as' },
      { label: 'Time', value: 'when, while, as, until, before, after, by the time, as soon as' },
      { label: 'Inside the clause', value: 'present simple, or present perfect for a completed step' },
      { label: 'In the other half', value: 'will, going to, an imperative or a modal' },
      { label: 'unless', value: 'means "if not", so it is never made negative again' },
      { label: 'by the time', value: 'pairs naturally with the future perfect: she will have finished by the time we get back' },
    ],
    examples: [
      {
        wrong: 'I will call you as soon as I will get the email.',
        right: 'I will call you as soon as I get the email.',
        note: 'Italian "appena riceverò" is a future; English is not.',
      },
      {
        wrong: 'We will celebrate when I will pass my exam.',
        right: 'We will celebrate when I pass my exam.',
        note: 'Or "when I have passed my exam", to stress that it is completed first.',
      },
      {
        wrong: "Unless we don't leave now, we'll miss the train.",
        right: "Unless we leave now, we'll miss the train.",
        note: '"Unless" already contains the negative.',
      },
    ],
    traps: [
      'Not all these conjunctions take the future in Italian, which is why some feel right and some do not. The English rule is the same for all of them.',
      'The same conjunctions can appear in ordinary past narrative, where this rule does not apply. It is specific to future and conditional clauses.',
      '"In case" means as a precaution, not "if": "take a sandwich in case you get hungry".',
      '"Until" and "by the time" are not interchangeable: one is a duration, the other a deadline.',
    ],
  },
  cards: [
    {
      id: 'c8-001',
      type: 'choice',
      prompt: "I'll call you as soon as I ___ the email.",
      answers: ['get', 'will get', 'am getting', 'will have got'],
      options: ['get', 'will get', 'am getting', 'will have got'],
      explanation: 'No "will" after "as soon as".',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-002',
      type: 'choice',
      prompt: '___ we arrived at the beach we jumped into the sea.',
      answers: ['as soon as', 'before', 'by the time', 'until'],
      options: ['as soon as', 'before', 'by the time', 'until'],
      explanation: 'The two actions follow immediately, which is what "as soon as" means.',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-003',
      type: 'choice',
      prompt: "I'll meet you at six ___ my bus is late.",
      answers: ['unless', 'when', 'as long as', 'in case'],
      options: ['unless', 'when', 'as long as', 'in case'],
      explanation: '"Unless" introduces the one thing that would stop it happening.',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-004',
      type: 'choice',
      prompt: 'If ___ no traffic, we will get to the airport on time.',
      answers: ["there isn't", "there's", 'there will be', "there won't be"],
      options: ["there isn't", "there's", 'there will be', "there won't be"],
      explanation: 'The if-clause takes the present, and the meaning is negative.',
      errorTags: ['future-time-clause', 'conditional'],
      level: 'B1',
    },
    {
      id: 'c8-005',
      type: 'fill',
      prompt: 'She will have finished by the time we ___ (get) back.',
      answers: ['get'],
      explanation: '"By the time" takes the present, and the other half takes the future perfect.',
      errorTags: ['future-time-clause'],
      level: 'B2',
    },
    {
      id: 'c8-006',
      type: 'fill',
      prompt: "I won't be able to start cooking until you ___ (get) me some olive oil.",
      answers: ['get'],
      explanation: 'No future after "until".',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-007',
      type: 'fill',
      prompt: "I'll be waiting here in case you ___ (finish) early.",
      answers: ['finish'],
      explanation: '"In case" is a precaution and also takes the present.',
      errorTags: ['future-time-clause'],
      level: 'B2',
    },
    {
      id: 'c8-008',
      type: 'correct',
      prompt: 'We will have a farewell party before she will leave.',
      answers: ['We will have a farewell party before she leaves.'],
      explanation: 'No "will" after "before".',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-009',
      type: 'correct',
      prompt: 'As long as you will help me, I will be able to do the job.',
      answers: ['As long as you help me, I will be able to do the job.'],
      explanation: 'Condition clause, so the present.',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-010',
      type: 'rewrite',
      prompt: 'Quando arriverà il pacco, Tom sarà felice.',
      answers: ['When the parcel arrives, Tom will be happy.', 'Tom will be happy when the parcel arrives.'],
      explanation: 'The Italian future inside the "quando" clause becomes an English present.',
      errorTags: ['future-time-clause'],
      level: 'B1',
    },
    {
      id: 'c8-011',
      type: 'rewrite',
      prompt: 'Starai meglio dopo che avrai mangiato qualcosa.',
      answers: ['You will feel better after you have eaten something.', "You'll feel better after you've eaten something."],
      explanation: 'The present perfect is used for the step that must be completed first.',
      errorTags: ['future-time-clause'],
      level: 'B2',
    },
    {
      id: 'c8-012',
      type: 'rewrite',
      prompt: 'Non possiamo fermarci finché non saremo arrivati.',
      answers: ['We cannot stop until we have arrived.', "We can't stop until we arrive."],
      explanation: 'Italian adds a "non" after "finché" that English does not want.',
      errorTags: ['future-time-clause', 'negative-form'],
      level: 'B2',
    },
    {
      id: 'c8-013',
      type: 'rewrite',
      prompt: 'Porta un panino nel caso ti venisse fame.',
      answers: ['Take a sandwich in case you get hungry.', 'Bring a sandwich in case you get hungry.'],
      explanation: '"In case" plus the present. Note "get hungry", not "come hungry".',
      errorTags: ['future-time-clause', 'get'],
      level: 'B2',
    },
    {
      id: 'c8-014',
      type: 'build',
      prompt: 'the taxi/not wait/for you/if/you/be/late',
      answers: ["The taxi won't wait for you if you are late.", 'The taxi will not wait for you if you are late.'],
      explanation: 'Future in the main half, present in the if half.',
      errorTags: ['future-time-clause', 'conditional'],
      level: 'B1',
    },
    {
      id: 'c8-015',
      type: 'transform',
      prompt: 'If we do not freeze his assets, he will sue us.',
      keyword: 'UNLESS',
      given: 'He will not sue us',
      answers: ['He will not sue us unless we freeze his assets.', "He won't sue us unless we freeze his assets."],
      explanation: '"Unless" replaces "if not", so both halves flip their polarity.',
      errorTags: ['future-time-clause', 'conditional'],
      level: 'B2',
    },
    {
      id: 'c8-016',
      type: 'choice',
      prompt: 'Surely the dog will bark ___ I am recording the lesson.',
      answers: ['while', 'until', 'by the time', 'unless'],
      options: ['while', 'until', 'by the time', 'unless'],
      explanation: '"While" sets two things running at the same time.',
      errorTags: ['future-time-clause'],
      level: 'B2',
    },
    {
      id: 'verb-009',
      type: 'choice',
      prompt: "I'll call you as soon as I ___ the email.",
      answers: ['get', 'will get', 'am getting', 'will have got'],
      options: ['get', 'will get', 'am getting', 'will have got'],
      explanation: "After \"when, as soon as, until, before, after\" the future is not used: put the present. Italian says \"appena ricever\u00f2\", which is where the mistake comes from.",
      errorTags: ['future-form'],
      level: 'B2',
    },
  ],
};
