import type { Unit } from '../types';

export const c9Obligation: Unit = {
  id: 'c9',
  stage: 'core',
  order: 9,
  title: 'Modals: obligation and necessity',
  summary: 'Must, have to, should: and the trap where two of them mean the opposite.',
  level: 'B1',
  errorTags: ['modal', 'obligation'],
  lesson: {
    rule: 'Modals never change form, never take "to" after them and never take an -s; and "mustn\'t" means it is forbidden while "don\'t have to" means it is not necessary.',
    schema: [
      { label: 'Obligation', value: 'must / have to: you must water the plants' },
      { label: 'Prohibition', value: "mustn't: you mustn't smoke in class" },
      { label: 'No obligation', value: "don't have to: you don't have to come" },
      { label: 'Advice, recommendation', value: 'should / ought to: you should call her' },
      { label: 'Questions', value: 'use have to: do I have to wear a seatbelt?' },
      { label: 'Other tenses', value: 'have to covers them all: had to, will have to, have had to' },
      { label: 'Never', value: 'no auxiliary before a modal, no modal after a modal' },
    ],
    examples: [
      {
        wrong: 'I must to study tonight.',
        right: 'I must study tonight.',
        note: 'After a modal the infinitive is bare.',
      },
      {
        wrong: "You don't have to smoke in here, it's forbidden.",
        right: "You mustn't smoke in here, it's forbidden.",
        note: 'These two are opposites, not synonyms.',
      },
      {
        wrong: 'Yesterday I must go to the bank.',
        right: 'Yesterday I had to go to the bank.',
        note: '"Must" has no past. "Have to" supplies every other tense.',
      },
    ],
    traps: [
      'Italian "devo" covers must and have to alike: must is an obligation you feel, have to one imposed from outside.',
      'Questions normally use "have to", not "must".',
      'After will, would, may and might you use "have to", never "must": "I might have to work tonight".',
      '"Should" also appears after verbs of recommending and in opinion structures: "it is only natural you should feel stressed".',
    ],
  },
  cards: [
    {
      id: 'c9-001',
      type: 'choice',
      prompt: 'This information is highly confidential, so you ___ discuss it with anyone.',
      answers: ["mustn't", "don't have to", 'are allowed to', 'should have to'],
      options: ["mustn't", "don't have to", 'are allowed to', 'should have to'],
      explanation: 'A prohibition, so "mustn\'t".',
      errorTags: ['obligation', 'modal'],
      level: 'B2',
    },
    {
      id: 'c9-002',
      type: 'choice',
      prompt: 'She ___ leave the window open, the cats will jump out!',
      answers: ["mustn't", "don't have to", "hasn't to", 'not must'],
      options: ["mustn't", "don't have to", "hasn't to", 'not must'],
      explanation: 'Negative obligation: it is compulsory NOT to do it.',
      errorTags: ['obligation'],
      level: 'B1',
    },
    {
      id: 'c9-003',
      type: 'choice',
      prompt: 'You ___ your sister, she has been waiting for your call.',
      answers: ['should phone', 'should to phone', 'have phone', 'should phoning'],
      options: ['should phone', 'should to phone', 'have phone', 'should phoning'],
      explanation: 'Advice, with a bare infinitive.',
      errorTags: ['modal'],
      level: 'A2',
    },
    {
      id: 'c9-004',
      type: 'fill',
      prompt: "Lisa's car broke down last night, so she ___ (have to) walk home.",
      answers: ['had to'],
      explanation: 'The past of both "must" and "have to" is "had to".',
      errorTags: ['obligation'],
      level: 'B1',
    },
    {
      id: 'c9-005',
      type: 'fill',
      prompt: "Tina is unwell, so we ___ (have to) cancel our holiday.",
      answers: ["'ve had to", 'have had to'],
      explanation: 'Present perfect of "have to": a recent, still relevant obligation.',
      errorTags: ['obligation'],
      level: 'B2',
    },
    {
      id: 'c9-006',
      type: 'fill',
      prompt: "We ___ (have to) go home if it starts raining.",
      answers: ["'ll have to", 'will have to'],
      explanation: 'The future of obligation is "will have to". "Will must" does not exist.',
      errorTags: ['obligation', 'modal'],
      level: 'B1',
    },
    {
      id: 'c9-007',
      type: 'correct',
      prompt: 'She cans speak three languages and she musts practise every day.',
      answers: ['She can speak three languages and she must practise every day.'],
      explanation: 'Modals never take the third person -s.',
      errorTags: ['modal'],
      level: 'A2',
    },
    {
      id: 'c9-008',
      type: 'correct',
      prompt: 'Do you must wear a uniform at work?',
      answers: ['Do you have to wear a uniform at work?'],
      explanation: 'No auxiliary before a modal, and questions about obligation use "have to".',
      errorTags: ['obligation', 'question-form'],
      level: 'B1',
    },
    {
      id: 'c9-009',
      type: 'correct',
      prompt: 'I will must finish the report by Friday.',
      answers: ['I will have to finish the report by Friday.'],
      explanation: 'Two modals cannot be combined. "Have to" carries the future.',
      errorTags: ['obligation', 'modal'],
      level: 'B1',
    },
    {
      id: 'c9-010',
      type: 'rewrite',
      prompt: 'Non è necessario che tu venga.',
      answers: ["You don't have to come.", 'You do not have to come.', "You needn't come."],
      explanation: '"Not necessary" is "do not have to", never "must not".',
      errorTags: ['obligation'],
      level: 'B1',
    },
    {
      id: 'c9-011',
      type: 'rewrite',
      prompt: 'Dovresti mangiare più verdura.',
      answers: ['You should eat more vegetables.', 'You ought to eat more vegetables.'],
      explanation: 'Advice: should, with a bare infinitive.',
      errorTags: ['modal'],
      level: 'A2',
    },
    {
      id: 'c9-012',
      type: 'build',
      prompt: 'papers/must/sign/by both parties',
      answers: ['Papers must be signed by both parties.'],
      explanation: 'A modal followed by a passive infinitive: must be signed. Typical of legal English.',
      errorTags: ['modal', 'passive'],
      level: 'B2',
    },
    {
      id: 'c9-013',
      type: 'choice',
      prompt: 'A: Are you coming to the party? B: No, I ___ work tonight.',
      answers: ['might have to', 'might must', 'will must', 'should must'],
      options: ['might have to', 'might must', 'will must', 'should must'],
      explanation: 'After a modal, obligation is expressed with "have to".',
      errorTags: ['obligation', 'modal'],
      level: 'B2',
    },
    {
      id: 'c9-014',
      type: 'transform',
      prompt: 'It is not necessary for you to pay now.',
      keyword: 'HAVE',
      given: 'You',
      answers: ["You don't have to pay now.", 'You do not have to pay now.'],
      explanation: 'The standard transformation between "not necessary" and "do not have to".',
      errorTags: ['obligation'],
      level: 'B2',
    },
    {
      id: 'c9-015',
      type: 'transform',
      prompt: 'Smoking is forbidden in this building.',
      keyword: 'MUST',
      given: 'You',
      answers: ["You mustn't smoke in this building.", 'You must not smoke in this building.'],
      explanation: 'A prohibition turns into "mustn\'t".',
      errorTags: ['obligation'],
      level: 'B2',
    },
    {
      id: 'c9-016',
      type: 'fill',
      prompt: "It's only natural you ___ (should) feel nervous, it's your first exam.",
      answers: ['should'],
      explanation: 'Opinion adjective structures take "should": it is interesting, strange, natural that you should...',
      errorTags: ['modal'],
      level: 'C1',
    },
    {
      id: 'c9-017',
      type: 'form',
      prompt: 'Signing the contract is ___ for both parties.',
      root: 'OBLIGE',
      answers: ['obligatory'],
      explanation: 'oblige becomes obligatory, and the noun is obligation.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'verb-013',
      type: 'choice',
      prompt: "In the library you ___ eat: there is a sign at the entrance.",
      answers: ["mustn't", "don't have to", "shouldn't have to", 'may not have to'],
      options: ["mustn't", "don't have to", "shouldn't have to", 'may not have to'],
      explanation: "A classic trap: \"mustn't\" means it is forbidden, \"don't have to\" means it is not necessary. They are opposites, not synonyms.",
      errorTags: ['modal'],
      level: 'B2',
    },
  ],
};
