import type { Unit } from '../types';

export const e1Trends: Unit = {
  id: 'e1',
  stage: 'esp',
  order: 1,
  title: 'The language of trends',
  summary: 'The verbs, nouns and adverbs you need to describe any chart.',
  level: 'B2',
  errorTags: ['esp-trend-vocabulary', 'preposition'],
  lesson: {
    rule: 'Every movement on a chart is described with three pieces: a verb or noun of direction, a word for how strong it is, and the right preposition.',
    schema: [
      { label: 'Up, neutral', value: 'rise, increase, grow, climb, improve, recover' },
      { label: 'Up, strong', value: 'soar, surge, jump, spike, rocket, peak' },
      { label: 'Down, neutral', value: 'fall, decrease, decline, go down, worsen' },
      { label: 'Down, strong', value: 'drop, dip, plunge, plummet, hit a trough' },
      { label: 'No change', value: 'level off, plateau, remain stable, stay constant, fluctuate' },
      { label: 'How strong', value: 'slight, gradual, moderate, steady, sharp, dramatic, steep, significant' },
      { label: 'Prepositions', value: 'by = the size of the change, to = the level reached, at = a fixed point' },
    ],
    examples: [
      {
        wrong: 'Sales increased of 15%.',
        right: 'Sales increased by 15%.',
        note: 'The size of a change always takes "by".',
      },
      {
        wrong: 'The index raised to 40 points.',
        right: 'The index rose to 40 points.',
        note: 'rise goes up by itself; raise lifts something else.',
      },
      {
        wrong: 'There was a strong rise of prices.',
        right: 'There was a sharp rise in prices.',
        note: 'The noun structure takes "in", and the usual adjective is "sharp".',
      },
    ],
    traps: [
      'Most of these verbs are both verbs and nouns: a rise, a fall, a drop, a peak.',
      'rise / rose / risen is irregular and intransitive. raise / raised / raised is regular and transitive.',
      'With the verb you need an adverb (rose sharply); with the noun you need an adjective (a sharp rise).',
      'Vary the two structures in a description, or it reads like a list.',
    ],
  },
  cards: [
    {
      id: 'e1-001',
      type: 'vocab',
      prompt: 'AUMENTARE BRUSCAMENTE (di un valore)',
      answers: ['to soar', 'soar', 'to surge', 'surge', 'to rocket', 'rocket'],
      explanation: 'Scale of intensity: rise or increase, then climb, then soar, surge and rocket.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-002',
      type: 'vocab',
      prompt: 'CROLLARE (di un mercato)',
      answers: ['to plummet', 'plummet', 'to plunge', 'plunge', 'to collapse', 'collapse'],
      explanation: 'Scale downwards: fall or decrease, then decline, drop, plummet, plunge, collapse.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-003',
      type: 'vocab',
      prompt: 'STABILIZZARSI DOPO UNA CRESCITA',
      answers: ['to level off', 'level off', 'to plateau', 'plateau'],
      explanation: '"Level off" is the verb for a curve that flattens out.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-004',
      type: 'vocab',
      prompt: 'OSCILLARE / FLUTTUARE',
      answers: ['to fluctuate', 'fluctuate', 'to vary', 'vary'],
      explanation: 'The noun is fluctuation, the adjective volatile.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-005',
      type: 'vocab',
      prompt: 'RAGGIUNGERE IL PUNTO PIU ALTO',
      answers: ['to peak', 'peak', 'to hit a peak', 'to reach a peak'],
      explanation: '"Peak" is verb and noun. The lowest point is a trough.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-006',
      type: 'vocab',
      prompt: 'UNA RIPRESA (dopo un calo)',
      answers: ['a recovery', 'recovery'],
      explanation: 'The verb is "recover": the market made a quick recovery.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-007',
      type: 'vocab',
      prompt: 'GRAFICO A TORTA',
      answers: ['a pie chart', 'pie chart'],
      explanation: 'Bar chart, line graph and scatter plot are the other three.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B1',
    },
    {
      id: 'e1-008',
      type: 'vocab',
      prompt: 'ASSE ORIZZONTALE E ASSE VERTICALE',
      answers: ['the horizontal axis and the vertical axis', 'the x-axis and the y-axis'],
      explanation: 'The plural of axis is axes. The wording on it is the label, the key is the legend.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-009',
      type: 'choice',
      prompt: 'Sales increased ___ 15% in the second quarter.',
      answers: ['by', 'of', 'with', 'for'],
      options: ['by', 'of', 'with', 'for'],
      explanation: 'The size of the change takes "by".',
      errorTags: ['preposition', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-010',
      type: 'choice',
      prompt: 'The index rose ___ 40 points and then levelled off.',
      answers: ['to', 'by', 'at', 'in'],
      options: ['to', 'by', 'at', 'in'],
      explanation: 'The level reached takes "to".',
      errorTags: ['preposition', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-011',
      type: 'choice',
      prompt: 'There was a sharp ___ in unemployment between 2020 and 2021.',
      answers: ['rise', 'raise', 'arise', 'rising'],
      options: ['rise', 'raise', 'arise', 'rising'],
      explanation: 'rise is the noun and the intransitive verb; raise is transitive; arise means to come up, of a problem.',
      errorTags: ['esp-trend-vocabulary', 'irregular-verb'],
      level: 'B2',
    },
    {
      id: 'e1-012',
      type: 'choice',
      prompt: 'The chart ___ the distribution of students by faculty.',
      answers: ['shows', 'says', 'tells', 'explains to'],
      options: ['shows', 'says', 'tells', 'explains to'],
      explanation: 'A chart shows, illustrates or represents. Say and tell are for people.',
      errorTags: ['esp-trend-vocabulary'],
      level: 'B1',
    },
    {
      id: 'e1-013',
      type: 'correct',
      prompt: 'There was a strong rise of housing prices.',
      answers: ['There was a sharp rise in housing prices.', 'There was a steep rise in housing prices.'],
      explanation: 'The noun structure is "a + adjective + noun + IN", and "sharp" is the collocation, not "strong".',
      errorTags: ['esp-structure', 'preposition'],
      level: 'B2',
    },
    {
      id: 'e1-014',
      type: 'correct',
      prompt: 'Prices raised slightly in the first half of the year.',
      answers: ['Prices rose slightly in the first half of the year.'],
      explanation: 'Prices go up by themselves, so the intransitive "rise".',
      errorTags: ['esp-trend-vocabulary', 'irregular-verb'],
      level: 'B2',
    },
    {
      id: 'e1-015',
      type: 'rewrite',
      prompt: 'Il grafico mostra un aumento costante tra il 2019 e il 2023.',
      answers: [
        'The chart shows a steady increase between 2019 and 2023.',
        'The graph shows a steady rise between 2019 and 2023.',
      ],
      explanation: '"Steady" is constant and regular. Its opposite is sharp or sudden.',
      errorTags: ['esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-016',
      type: 'rewrite',
      prompt: 'Nel complesso, la tendenza è positiva.',
      answers: ['Overall, the trend is positive.', 'On the whole, the trend is positive.'],
      explanation: 'Useful openers for a chart comment: Overall, On the whole, Broadly speaking.',
      errorTags: ['esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-017',
      type: 'rewrite',
      prompt: 'Il valore più alto è stato raggiunto a marzo.',
      answers: ['The highest value was reached in March.', 'Values peaked in March.', 'The peak was reached in March.'],
      explanation: 'The passive is the natural voice here, and "peak" gives you a shorter version.',
      errorTags: ['passive', 'esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'e1-018',
      type: 'build',
      prompt: 'there/be/a slight increase/in housing prices/last year',
      answers: ['There was a slight increase in housing prices last year.'],
      explanation: 'Structure A: there + be + adjective + noun + in.',
      errorTags: ['esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-019',
      type: 'build',
      prompt: 'housing prices/increase/slightly/last year',
      answers: ['Housing prices increased slightly last year.'],
      explanation: 'Structure B: noun + verb + adverb. The same fact, said the other way.',
      errorTags: ['esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-020',
      type: 'transform',
      prompt: 'There was a gradual rise in the price of oil.',
      keyword: 'ROSE',
      given: 'The price of oil',
      answers: ['The price of oil rose gradually.'],
      explanation: 'Switching between the two structures is exactly what the exam asks for.',
      errorTags: ['esp-structure'],
      level: 'B2',
    },
    {
      id: 'e1-021',
      type: 'transform',
      prompt: 'Coffee prices dropped sharply this year.',
      keyword: 'DROP',
      given: 'There has been a sharp',
      answers: ['There has been a sharp drop in coffee prices this year.'],
      explanation: 'The year is not over, so the present perfect. And the noun takes "in".',
      errorTags: ['esp-structure', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'e1-022',
      type: 'form',
      prompt: 'The market showed a remarkable ___ in the third quarter.',
      root: 'IMPROVE',
      answers: ['improvement'],
      explanation: 'improve becomes improvement, one of the neutral nouns for an upward trend.',
      errorTags: ['word-formation', 'esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'esp-001',
      type: 'vocab',
      prompt: 'GRAFICO A TORTA',
      answers: ['pie chart', 'a pie chart'],
      explanation: "Bar chart, line graph, scatter plot are the other three you need.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'esp-002',
      type: 'vocab',
      prompt: 'AUMENTARE BRUSCAMENTE (di un valore)',
      answers: ['to soar', 'soar', 'to surge', 'surge', 'to rocket', 'rocket'],
      explanation: "Scale of intensity: rise or increase (neutral), then climb, then soar, surge, rocket (strong).",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-003',
      type: 'vocab',
      prompt: 'CROLLARE (di un mercato)',
      answers: ['to plummet', 'plummet', 'to plunge', 'plunge', 'to collapse', 'collapse'],
      explanation: "Scale downwards: fall or decrease (neutral), then decline, drop, plummet, plunge, collapse.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-004',
      type: 'vocab',
      prompt: 'RIMANERE STABILE',
      answers: [
        'to remain stable',
        'remain stable',
        'to level off',
        'level off',
        'to plateau',
        'plateau',
      ],
      explanation: "\"To level off\" is the verb you want when the curve flattens after a climb.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-005',
      type: 'vocab',
      prompt: 'OSCILLARE / FLUTTUARE',
      answers: ['to fluctuate', 'fluctuate'],
      explanation: "The noun is \"fluctuation\", the adjective \"volatile\", a golden word in finance.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-011',
      type: 'rewrite',
      prompt: 'Il grafico mostra un aumento costante tra il 2019 e il 2023.',
      answers: [
        'The chart shows a steady increase between 2019 and 2023.',
        'The graph shows a steady rise between 2019 and 2023.',
      ],
      explanation: "\"Steady\" means constant and regular. Its opposite is \"sharp\" or \"sudden\".",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-012',
      type: 'rewrite',
      prompt: 'I prezzi sono saliti leggermente nella prima metà dell\'anno.',
      answers: [
        'Prices rose slightly in the first half of the year.',
        'Prices increased slightly in the first half of the year.',
      ],
      explanation: "Adverbs worth keeping: slightly, gradually, steadily, sharply, dramatically. They go after the verb.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-013',
      type: 'rewrite',
      prompt: 'Nel complesso, il trend è positivo.',
      answers: ['Overall, the trend is positive.', 'On the whole, the trend is positive.'],
      explanation: "Useful openers for commenting on a chart: Overall, On the whole, Broadly speaking.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-014',
      type: 'rewrite',
      prompt: 'Il valore più alto è stato raggiunto a marzo.',
      answers: [
        'The highest value was reached in March.',
        'The peak was reached in March.',
        'Values peaked in March.',
      ],
      explanation: "\"Peak\" works as a noun (the highest point) and as a verb (to reach the top). The low point is the \"trough\".",
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'esp-019',
      type: 'vocab',
      prompt: 'ASSE ORIZZONTALE / ASSE VERTICALE',
      answers: ['horizontal axis and vertical axis', 'x-axis and y-axis'],
      explanation: "The plural of \"axis\" is \"axes\". The wording on it is the \"label\", and the key is the \"legend\".",
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'esp-020',
      type: 'vocab',
      prompt: 'MEDIA (aritmetica)',
      answers: ['average', 'mean', 'the mean'],
      explanation: "In statistics: mean, median, mode, range.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-021',
      type: 'vocab',
      prompt: 'TASSO DI CRESCITA',
      answers: ['growth rate', 'the growth rate'],
      explanation: "Useful family: interest rate, exchange rate, unemployment rate, inflation rate.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-reading-001',
      type: 'reading',
      prompt: 'Which trend is described in the final sentence?',
      passage: { heading: 'Subscription growth slows', body: 'A streaming service added 1.2 million subscribers in the first quarter, compared with 1.8 million in the previous quarter. The company said that total subscriptions still reached a record level. Analysts noted that growth had slowed, but that the overall customer base continued to expand.' },
      answers: ['Growth continued, but at a slower rate.'],
      options: ['Growth continued, but at a slower rate.', 'The customer base fell to a record low.', 'Subscriptions stopped changing.', 'The company lost 1.2 million customers.'],
      explanation: 'The total continued to grow, while the number added each quarter became smaller.',
      errorTags: ['esp-trend-vocabulary'], level: 'B2',
    },
  ],
};
