import type { Unit } from '../types';

export const e2DataTenses: Unit = {
  id: 'e2',
  stage: 'esp',
  order: 2,
  title: 'Tenses and structures for describing data',
  summary: 'Which tense a chart needs, and the two structures to alternate.',
  level: 'B2',
  errorTags: ['esp-structure', 'passive'],
  lesson: {
    rule: 'Describing a chart uses two structures, one with "there + be + adjective + noun + in" and one with "noun + verb + adverb", and the tense is chosen by the same rules as anywhere else in English.',
    schema: [
      { label: 'Structure A', value: 'There was a slight increase in housing prices' },
      { label: 'Structure B', value: 'Housing prices increased slightly' },
      { label: 'Finished, dated period', value: 'past simple: in 2023 there was a rise' },
      { label: 'Unfinished period, up to now', value: 'present perfect: there has been a drop since January' },
      { label: 'Happening as we speak', value: 'present continuous: prices are rising at the moment' },
      { label: 'Sequenced before another past', value: 'past perfect: before the crash there had been an increase' },
      { label: 'Projection', value: 'will, will be rising, will have risen by 2030' },
    ],
    examples: [
      {
        wrong: 'In 2023 there has been a significant rise in oil prices.',
        right: 'In 2023 there was a significant rise in oil prices.',
        note: 'A named, finished year takes the past simple.',
      },
      {
        wrong: 'Since January the price of coffee dropped.',
        right: 'Since January the price of coffee has dropped.',
        note: '"Since" opens a period running up to now.',
      },
      {
        wrong: 'From this graph you can see that visitor numbers rise at the moment.',
        right: 'From this graph you can see that visitor numbers are rising at the moment.',
        note: 'Happening now, so the present continuous.',
      },
    ],
    traps: [
      'Structure A only uses the verb "be", so it has no continuous form. Structure B does.',
      'The simple form focuses on the time frame, the continuous on the action: "has dropped since January" versus "has been dropping since January".',
      'The passive is the normal voice for method: the data were collected through a questionnaire.',
      'Modals work with both structures: there may have been a rise; prices may have risen.',
    ],
  },
  cards: [
    {
      id: 'e2-001',
      type: 'fill',
      prompt: 'In 2023 there ___ (be) a significant rise in the price of oil.',
      answers: ['was'],
      explanation: 'A named, finished year takes the past simple.',
      errorTags: ['esp-structure', 'past-simple'],
      level: 'B2',
    },
    {
      id: 'e2-002',
      type: 'fill',
      prompt: 'There ___ (be) a sharp drop in the price of coffee since the beginning of the year.',
      answers: ['has been'],
      explanation: '"Since" opens a period that reaches the present.',
      errorTags: ['esp-structure', 'for-since'],
      level: 'B2',
    },
    {
      id: 'e2-003',
      type: 'fill',
      prompt: 'Before the sinking of the Titanic, there ___ (be) an increase in cruise-liner tourism.',
      answers: ['had been'],
      explanation: 'Earlier than another past event: past perfect.',
      errorTags: ['esp-structure', 'narrative-tense'],
      level: 'B2',
    },
    {
      id: 'e2-004',
      type: 'fill',
      prompt: 'From this graph you can see that the number of visitors ___ (rise) at the moment.',
      answers: ['is rising'],
      explanation: 'Ongoing as we speak: present continuous.',
      errorTags: ['esp-structure', 'present-simple-vs-continuous'],
      level: 'B2',
    },
    {
      id: 'e2-005',
      type: 'fill',
      prompt: 'The price of coffee ___ (drop) since January, and it is still falling.',
      answers: ['has been dropping'],
      explanation: 'The continuous puts the focus on the action, which is not over.',
      errorTags: ['esp-structure', 'present-perfect-continuous'],
      level: 'B2',
    },
    {
      id: 'e2-006',
      type: 'fill',
      prompt: 'The price of oil ___ (rise) gradually while that of gas remained stable.',
      answers: ['was rising'],
      explanation: 'Two trends side by side in the past: the continuous.',
      errorTags: ['esp-structure', 'narrative-tense'],
      level: 'B2',
    },
    {
      id: 'e2-007',
      type: 'fill',
      prompt: 'By June 2030 car sales ___ (rise) by six per cent.',
      answers: ['will have risen'],
      explanation: '"By" plus a future date: future perfect.',
      errorTags: ['esp-structure', 'future-form'],
      level: 'B2',
    },
    {
      id: 'e2-008',
      type: 'fill',
      prompt: 'The blue line ___ (represent) the control group.',
      answers: ['represents'],
      explanation: 'What is in the chart is a permanent fact of the figure: present simple.',
      errorTags: ['esp-structure'],
      level: 'B1',
    },
    {
      id: 'e2-009',
      type: 'fill',
      prompt: 'Between 2015 and 2018 the index ___ (remain) broadly unchanged.',
      answers: ['remained'],
      explanation: 'A closed period: past simple. "Broadly unchanged" means essentially flat.',
      errorTags: ['esp-structure', 'past-simple'],
      level: 'B2',
    },
    {
      id: 'e2-010',
      type: 'fill',
      prompt: 'The data ___ (collect) through a questionnaire.',
      answers: ['were collected', 'was collected'],
      explanation: 'The passive is the normal voice for method. In academic English "data" takes a plural verb.',
      errorTags: ['passive', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'e2-011',
      type: 'choice',
      prompt: 'The figures ___ that inflation is slowing down.',
      answers: ['suggest', 'suggests', 'is suggesting', 'suggesting'],
      options: ['suggest', 'suggests', 'is suggesting', 'suggesting'],
      explanation: '"Figures" is plural, so no -s on the verb.',
      errorTags: ['esp-numbers'],
      level: 'B1',
    },
    {
      id: 'e2-012',
      type: 'choice',
      prompt: 'There ___ a market crash unless we act quickly.',
      answers: ['is going to be', 'will be being', 'is been', 'has been'],
      options: ['is going to be', 'will be being', 'is been', 'has been'],
      explanation: 'A prediction with visible evidence, and "unless" never takes the future.',
      errorTags: ['esp-structure', 'future-time-clause'],
      level: 'B2',
    },
    {
      id: 'e2-013',
      type: 'choice',
      prompt: 'There ___ a rise in oil prices last quarter, judging by these numbers.',
      answers: ['may have been', 'may be', 'may been', 'may have'],
      options: ['may have been', 'may be', 'may been', 'may have'],
      explanation: 'Speculating about past data: modal plus have been.',
      errorTags: ['esp-structure', 'deduction'],
      level: 'B2',
    },
    {
      id: 'e2-014',
      type: 'correct',
      prompt: 'The datas shows a clear trend.',
      answers: ['The data show a clear trend.', 'The data shows a clear trend.'],
      explanation: '"Datas" does not exist in any register. In academic English "data" takes a plural verb.',
      errorTags: ['uncountable', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e2-015',
      type: 'correct',
      prompt: 'In the graph we can see that the sales are increased of 10%.',
      answers: ['The graph shows that sales increased by 10%.'],
      explanation: 'Three mistakes: a wrong passive, "of" instead of "by", and an article before a general plural.',
      errorTags: ['passive', 'preposition', 'article'],
      level: 'B2',
    },
    {
      id: 'e2-016',
      type: 'correct',
      prompt: 'The sample consisted in 240 undergraduate students.',
      answers: ['The sample consisted of 240 undergraduate students.'],
      explanation: 'consist OF. Italian "consistere in" leads straight to the mistake.',
      errorTags: ['preposition'],
      level: 'B2',
    },
    {
      id: 'e2-017',
      type: 'rewrite',
      prompt: 'I dati sono stati raccolti tramite un questionario.',
      answers: ['The data were collected through a questionnaire.', 'The data was collected through a questionnaire.'],
      explanation: 'The passive keeps the focus on the method, not on who applied it.',
      errorTags: ['passive', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'e2-018',
      type: 'rewrite',
      prompt: 'Il mercato è sceso del 2% questa settimana.',
      answers: ['The market has fallen by 2% this week.', 'The market has dropped by 2% this week.'],
      explanation: '"This week" is still open, so the present perfect.',
      errorTags: ['esp-structure', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'e2-019',
      type: 'rewrite',
      prompt: 'Vale la pena notare che il campione era piuttosto piccolo.',
      answers: [
        'It is worth noting that the sample was rather small.',
        "It's worth noting that the sample was quite small.",
      ],
      explanation: '"It is worth + -ing" is the formula for discussing the limits of a study.',
      errorTags: ['gerund-vs-infinitive', 'esp-structure'],
      level: 'C1',
    },
    {
      id: 'e2-020',
      type: 'transform',
      prompt: 'The number of museum visitors usually rises before Christmas.',
      keyword: 'THERE',
      given: 'Before Christmas',
      answers: [
        'Before Christmas there is usually a rise in the number of museum visitors.',
        'Before Christmas there is normally a rise in the number of museum visitors.',
      ],
      explanation: 'Moving from structure B to structure A, the standard exam transformation.',
      errorTags: ['esp-structure'],
      level: 'B2',
    },
    {
      id: 'e2-021',
      type: 'build',
      prompt: 'cruise-liner tourism/rise/before the sinking of the Titanic',
      answers: [
        'Cruise-liner tourism had risen before the sinking of the Titanic.',
        'Cruise-liner tourism had been rising before the sinking of the Titanic.',
      ],
      explanation: 'The simple form focuses on the time, the continuous on the action.',
      errorTags: ['esp-structure', 'narrative-tense'],
      level: 'C1',
    },
    {
      id: 'e2-022',
      type: 'form',
      prompt: 'The two data sets show a clear ___.',
      root: 'CORRELATE',
      answers: ['correlation'],
      explanation: 'correlate becomes correlation. Note "correlation between".',
      errorTags: ['word-formation', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'esp-006',
      type: 'choice',
      prompt: 'Sales increased ___ 15% in the second quarter.',
      answers: ['by', 'of', 'with', 'for'],
      options: ['by', 'of', 'with', 'for'],
      explanation: "The size of the change takes \"by\". The level reached takes \"to\": \"rose to 40%\".",
      errorTags: ['preposition'],
      level: 'B2',
    },
    {
      id: 'esp-007',
      type: 'choice',
      prompt: 'There was a sharp ___ in unemployment between 2020 and 2021.',
      answers: ['rise', 'raise', 'arise', 'rising'],
      options: ['rise', 'raise', 'arise', 'rising'],
      explanation: "\"Rise\" is the noun and the intransitive verb: it goes up by itself. \"Raise\" is transitive: you lift something. \"Arise\" means to come up, of a problem.",
      errorTags: ['false-friend', 'irregular-verb'],
      level: 'B2',
    },
    {
      id: 'esp-008',
      type: 'choice',
      prompt: 'The chart ___ the distribution of students by faculty.',
      answers: ['shows', 'says', 'tells', 'explains to'],
      options: ['shows', 'says', 'tells', 'explains to'],
      explanation: "A chart \"shows\", \"illustrates\" or \"represents\". \"Say\" and \"tell\" are for people.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'esp-009',
      type: 'choice',
      prompt: 'Roughly one ___ of the sample was under 25.',
      answers: ['third', 'three', 'thirds', 'tierce'],
      options: ['third', 'three', 'thirds', 'tierce'],
      explanation: "Fractions take the ordinal: one third, two thirds, a quarter, three quarters.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'esp-010',
      type: 'choice',
      prompt: 'The figures ___ that inflation is slowing down.',
      answers: ['suggest', 'suggests', 'is suggesting', 'suggesting'],
      options: ['suggest', 'suggests', 'is suggesting', 'suggesting'],
      explanation: "\"Figures\" is plural, so no -s on the verb. It is the most frequent slip in written reports.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'esp-015',
      type: 'rewrite',
      prompt: 'I dati sono stati raccolti tramite un questionario.',
      answers: [
        'The data were collected through a questionnaire.',
        'The data was collected through a questionnaire.',
      ],
      explanation: "The passive is the normal voice of academic writing: what counts is the method, not who applied it.",
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'esp-016',
      type: 'fill',
      prompt: 'The blue line ___ (represent) the control group.',
      answers: ['represents'],
      explanation: "Present simple to describe what is in the chart: it is a permanent fact of the figure.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'esp-017',
      type: 'fill',
      prompt: 'Between 2015 and 2018 the index ___ (remain) broadly unchanged.',
      answers: ['remained'],
      explanation: "A closed, finished period: past simple. \"Broadly unchanged\" means essentially flat.",
      errorTags: ['present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'esp-018',
      type: 'fill',
      prompt: 'Since January the rate ___ (fall) by two percentage points.',
      answers: ['has fallen'],
      explanation: "Mind the vocabulary: \"percentage points\" is not \"per cent\". From 6% to 4% is a fall of 2 points, but of 33 per cent.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'C1',
    },
    {
      id: 'esp-022',
      type: 'choice',
      prompt: 'Compared ___ last year, revenues are up by 8%.',
      answers: ['with', 'at', 'from', 'than'],
      options: ['with', 'at', 'from', 'than'],
      explanation: "\"Compared with\" and \"compared to\" are both fine. \"Compared than\" never is.",
      errorTags: ['preposition'],
      level: 'B2',
    },
    {
      id: 'esp-023',
      type: 'choice',
      prompt: 'The sample ___ of 240 undergraduate students.',
      answers: ['consisted', 'consisted in', 'was consisting', 'consists in'],
      options: ['consisted', 'consisted in', 'was consisting', 'consists in'],
      explanation: "\"Consist OF\" means to be made up of. Italian \"consistere in\" leads straight to the mistake.",
      errorTags: ['preposition', 'false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-024',
      type: 'correct',
      prompt: 'The datas shows a clear trend.',
      answers: ['The data show a clear trend.', 'The data shows a clear trend.'],
      explanation: "\"Datas\" does not exist in any register. \"Data\" is already the plural of \"datum\", and in academic English it takes a plural verb.",
      errorTags: ['uncountable'],
      level: 'B2',
    },
    {
      id: 'esp-025',
      type: 'correct',
      prompt: 'In the graph we can see that the sales are increased of 10%.',
      answers: ['The graph shows that sales increased by 10%.'],
      explanation: "Three mistakes: \"are increased\" (wrong passive, increase is intransitive here), \"of\" instead of \"by\", and the article in front of \"sales\" used in a general sense.",
      errorTags: ['passive', 'preposition', 'article'],
      level: 'B2',
    },
    {
      id: 'esp-026',
      type: 'rewrite',
      prompt: 'Vale la pena notare che il campione era piuttosto piccolo.',
      answers: [
        'It is worth noting that the sample was rather small.',
        "It's worth noting that the sample was quite small.",
      ],
      explanation: "\"It is worth + -ing\" is a formula to keep ready for discussing the limitations of a study.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'C1',
    },
  ],
};
