import type { Unit } from '../types';

export const e3Numbers: Unit = {
  id: 'e3',
  stage: 'esp',
  order: 3,
  title: 'Numbers, proportions and finance vocabulary',
  summary: 'Saying figures correctly, and the words the exam puts in the word box.',
  level: 'B2',
  errorTags: ['esp-numbers', 'uncountable', 'false-friend'],
  lesson: {
    rule: 'English counts in a fixed set of words: figures for the raw numbers, percentage for a share in per cent, proportion for a share of a whole, and fractions always take the ordinal.',
    schema: [
      { label: 'The raw numbers', value: 'figures: figures for the gallery went down' },
      { label: 'A share in per cent', value: 'percentage: the percentage of students rose' },
      { label: 'A share of a whole', value: 'proportion: the proportion of tourists' },
      { label: 'Fractions', value: 'ordinals: one third, two thirds, a quarter, three quarters' },
      { label: 'Approximation', value: 'roughly, approximately, just over, just under, around' },
      { label: 'Superlative emphasis', value: 'by far: by far the most popular attraction' },
      { label: 'Across a period', value: 'over: over a thirty-year period' },
    ],
    examples: [
      {
        wrong: 'The rate fell by two per cents.',
        right: 'The rate fell by two percentage points.',
        note: 'From 6% to 4% is a fall of 2 points, but of 33 per cent. They are different numbers.',
      },
      {
        wrong: 'Roughly one three of the sample was under 25.',
        right: 'Roughly one third of the sample was under 25.',
        note: 'Fractions take the ordinal.',
      },
      {
        wrong: 'The datas were collected in 2024.',
        right: 'The data were collected in 2024.',
        note: 'data, information, research, news and advice have no plural.',
      },
    ],
    traps: [
      '"Percentage" needs a figure in per cent; "proportion" describes a share without one.',
      '"Figures" is always plural and takes a plural verb.',
      '"Billion" in modern English is a thousand million, the same as Italian "miliardo", not "bilione".',
      'Decimals use a point and thousands use a comma: 1,250.75.',
    ],
  },
  cards: [
    {
      id: 'e3-001',
      type: 'box',
      prompt: 'The graph shows information about the ___ of tourists who visited Brighton attractions.',
      options: ['proportion', 'figures', 'percentage', 'graph', 'over'],
      answers: ['proportion'],
      explanation: '"Proportion of" is a share of a whole, with no figure attached.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-002',
      type: 'box',
      prompt: 'The chart covers a thirty-year period, ___ three decades.',
      options: ['over', 'by far', 'percentage', 'figures'],
      answers: ['over'],
      explanation: '"Over" spans a period of time.',
      errorTags: ['esp-numbers', 'preposition'],
      level: 'B2',
    },
    {
      id: 'e3-003',
      type: 'box',
      prompt: 'The Pavilion was ___ the most popular attraction in the city.',
      options: ['by far', 'over', 'proportion', 'percentage'],
      answers: ['by far'],
      explanation: '"By far" strengthens a superlative.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-004',
      type: 'box',
      prompt: 'Both attractions witnessed a rise in the ___ of tourists.',
      options: ['percentage', 'figures', 'by far', 'over'],
      answers: ['percentage'],
      explanation: '"Percentage of" when the share is expressed in per cent.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-005',
      type: 'box',
      prompt: '___ for the Festival and the Art Gallery went down significantly.',
      options: ['Figures', 'Percentage', 'Proportion', 'Graph'],
      answers: ['Figures'],
      explanation: '"Figures" are the raw numbers, and the word is plural.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-006',
      type: 'choice',
      prompt: 'Roughly one ___ of the sample was under 25.',
      answers: ['third', 'three', 'thirds', 'tierce'],
      options: ['third', 'three', 'thirds', 'tierce'],
      explanation: 'Fractions use the ordinal: one third, two thirds, a quarter.',
      errorTags: ['esp-numbers', 'word-formation'],
      level: 'B1',
    },
    {
      id: 'e3-007',
      type: 'choice',
      prompt: 'Compared ___ last year, revenues are up by 8%.',
      answers: ['with', 'at', 'from', 'than'],
      options: ['with', 'at', 'from', 'than'],
      explanation: '"Compared with" and "compared to" are both fine. "Compared than" never is.',
      errorTags: ['preposition', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-008',
      type: 'fill',
      prompt: 'Since January the rate has fallen by two percentage ___.',
      answers: ['points'],
      explanation: 'The difference between two percentages is measured in points, not per cent.',
      errorTags: ['esp-numbers'],
      level: 'C1',
    },
    {
      id: 'e3-009',
      type: 'vocab',
      prompt: 'MEDIA, MEDIANA, MODA (in statistica)',
      answers: ['mean, median, mode', 'the mean, the median, the mode', 'average, median, mode'],
      explanation: 'The everyday word for the mean is "average". The spread is the range.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-010',
      type: 'vocab',
      prompt: 'TASSO DI CRESCITA',
      answers: ['growth rate', 'the growth rate'],
      explanation: 'Useful family: interest rate, exchange rate, unemployment rate, inflation rate.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-011',
      type: 'vocab',
      prompt: 'AZIONI (di una società)',
      answers: ['shares', 'stocks', 'shares or stocks'],
      explanation: 'Shares in British English, stocks in American. A shareholder owns them.',
      errorTags: ['false-friend', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-012',
      type: 'vocab',
      prompt: 'FATTURATO',
      answers: ['turnover', 'revenue', 'revenues'],
      explanation: '"Turnover" is British; "revenue" works everywhere. Profit is what is left afterwards.',
      errorTags: ['false-friend', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-013',
      type: 'vocab',
      prompt: 'UN MILIARDO',
      answers: ['a billion', 'one billion', 'billion'],
      explanation: 'Modern English "billion" is a thousand million, which is the Italian miliardo.',
      errorTags: ['false-friend', 'esp-numbers'],
      level: 'B1',
    },
    {
      id: 'e3-014',
      type: 'vocab',
      prompt: 'PATRIMONIO / ATTIVI (di una persona o azienda)',
      answers: ['assets', 'the assets'],
      explanation: 'Assets on one side, liabilities on the other.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-015',
      type: 'correct',
      prompt: 'The unemployment is at the 7 per cent.',
      answers: ['Unemployment is at 7 per cent.'],
      explanation: 'No article before an abstract noun, and none before a percentage.',
      errorTags: ['article', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-016',
      type: 'correct',
      prompt: 'The turnover of the company is growth every year.',
      answers: ['The turnover of the company grows every year.', "The company's turnover grows every year."],
      explanation: '"Growth" is the noun, "grow" the verb. And the possessive with a company is neater.',
      errorTags: ['word-formation', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-017',
      type: 'rewrite',
      prompt: 'Poco più di un quarto degli intervistati ha risposto di sì.',
      answers: [
        'Just over a quarter of respondents said yes.',
        'Just over one quarter of the respondents answered yes.',
      ],
      explanation: '"Just over" and "just under" are the standard approximations.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-018',
      type: 'rewrite',
      prompt: 'Le azioni sono salite del 3% rispetto alla settimana scorsa.',
      answers: [
        'Shares have risen by 3% compared with last week.',
        'Shares are up 3% compared to last week.',
      ],
      explanation: '"by" for the size of the change, "compared with" for the benchmark.',
      errorTags: ['esp-numbers', 'preposition'],
      level: 'B2',
    },
    {
      id: 'e3-019',
      type: 'form',
      prompt: 'The study relies on a small but ___ sample.',
      root: 'REPRESENT',
      answers: ['representative'],
      explanation: 'represent becomes representative.',
      errorTags: ['word-formation', 'esp-numbers'],
      level: 'B2',
    },
    {
      id: 'e3-020',
      type: 'form',
      prompt: 'Market ___ has increased since the announcement.',
      root: 'VOLATILE',
      answers: ['volatility'],
      explanation: 'volatile becomes volatility, a key word in finance.',
      errorTags: ['word-formation', 'esp-numbers'],
      level: 'C1',
    },
  ],
};
