import type { Unit } from '../types';

export const f1Present: Unit = {
  id: 'f1',
  stage: 'foundations',
  order: 1,
  title: 'Present simple and present continuous',
  summary: 'What you do in general, and what is happening right now.',
  level: 'A2',
  errorTags: ['present-simple-vs-continuous', 'state-verbs'],
  lesson: {
    rule: 'The present simple is for what happens regularly or is always true; the present continuous is for what is happening now or around now, and state verbs never take the continuous.',
    schema: [
      { label: 'Habits, routines, general truths', value: 'present simple: I work in Cagliari' },
      { label: 'Timetables and schedules', value: 'present simple: the train leaves at six' },
      { label: 'Happening right now', value: 'present continuous: I am studying' },
      { label: 'Temporary, around now', value: 'present continuous: I am living with my parents' },
      { label: 'Third person singular', value: 'add -s: he works, she studies, it goes' },
      { label: 'State verbs (never -ing)', value: 'know, like, love, hate, want, need, believe, belong, seem, understand, prefer' },
    ],
    examples: [
      {
        wrong: 'I am knowing the answer.',
        right: 'I know the answer.',
        note: '"Know" is a state verb, so it has no -ing form at all.',
      },
      {
        wrong: 'Every morning I am taking the bus.',
        right: 'Every morning I take the bus.',
        note: 'A routine takes the present simple, whatever Italian does.',
      },
      {
        wrong: 'She work in a bank.',
        right: 'She works in a bank.',
        note: 'Third person singular always takes -s. It is the most common slip of all.',
      },
    ],
    traps: [
      'Italian uses the simple present for both ("studio" can mean I study and I am studying), so you have to decide each time which one English wants.',
      'The -s of the third person disappears in questions and negatives: does she work, she does not work, never "does she works".',
      'Some verbs change meaning with -ing: "I think it is fine" is an opinion, "I am thinking about it" is an activity.',
    ],
  },
  cards: [
    {
      id: 'f1-001',
      type: 'choice',
      prompt: 'Most children ___ enough green vegetables.',
      answers: ["don't eat", "eatn't", 'not eat', 'are not eat'],
      options: ["don't eat", "eatn't", 'not eat', 'are not eat'],
      explanation: 'Negative present simple: do or does plus not plus the bare verb.',
      errorTags: ['negative-form', 'present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-002',
      type: 'choice',
      prompt: 'In this picture the woman ___ on a couch.',
      answers: ['is sitting', 'sits', 'sitting', 'sit'],
      options: ['is sitting', 'sits', 'sitting', 'sit'],
      explanation: 'Describing what is happening in a picture, right now, takes the present continuous.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-003',
      type: 'fill',
      prompt: 'My sister ___ (work) for a bank in Milan.',
      answers: ['works'],
      explanation: 'A permanent job is a general truth: present simple, third person -s.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-004',
      type: 'fill',
      prompt: 'Be quiet, the baby ___ (sleep).',
      answers: ['is sleeping'],
      explanation: 'Happening at this exact moment: present continuous.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-005',
      type: 'fill',
      prompt: 'The lecture ___ (start) at nine every Tuesday.',
      answers: ['starts'],
      explanation: 'A timetable takes the present simple, even though it is about the future.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'B1',
    },
    {
      id: 'f1-006',
      type: 'fill',
      prompt: 'I ___ (not understand) this chapter at all.',
      answers: ["don't understand", 'do not understand'],
      explanation: '"Understand" is a state verb, so no continuous form even though you mean right now.',
      errorTags: ['state-verbs', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'f1-007',
      type: 'correct',
      prompt: 'I am wanting a coffee.',
      answers: ['I want a coffee.'],
      explanation: '"Want" is a state verb. Same family: need, like, love, hate, prefer.',
      errorTags: ['state-verbs'],
      level: 'A2',
    },
    {
      id: 'f1-008',
      type: 'correct',
      prompt: 'He go to the gym three times a week.',
      answers: ['He goes to the gym three times a week.'],
      explanation: 'Third person singular takes -s, and verbs ending in -o take -es: goes, does.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-009',
      type: 'correct',
      prompt: 'Does she works on Saturdays?',
      answers: ['Does she work on Saturdays?'],
      explanation: 'Once "does" carries the tense, the main verb goes back to its bare form.',
      errorTags: ['question-form'],
      level: 'A2',
    },
    {
      id: 'f1-010',
      type: 'correct',
      prompt: 'This year I am studying statistics, and I am liking it.',
      answers: ['This year I am studying statistics, and I like it.'],
      explanation: '"Study" is fine in the continuous for a temporary period. "Like" is a state verb and stays simple.',
      errorTags: ['state-verbs'],
      level: 'B1',
    },
    {
      id: 'f1-011',
      type: 'choice',
      prompt: 'What ___ you ___ about?',
      answers: ['are / thinking', 'do / think', 'are / think', 'do / thinking'],
      options: ['are / thinking', 'do / think', 'are / think', 'do / thinking'],
      explanation: '"Think about" is a mental activity, so the continuous works. "Think that" is an opinion and stays simple.',
      errorTags: ['state-verbs', 'question-form'],
      level: 'B1',
    },
    {
      id: 'f1-012',
      type: 'choice',
      prompt: 'This soup ___ delicious.',
      answers: ['tastes', 'is tasting', 'taste', 'is taste'],
      options: ['tastes', 'is tasting', 'taste', 'is taste'],
      explanation: 'Verbs of the senses describing a quality stay simple: it tastes, it smells, it looks.',
      errorTags: ['state-verbs'],
      level: 'B1',
    },
    {
      id: 'f1-013',
      type: 'rewrite',
      prompt: 'Lavoro in una banca.',
      answers: ['I work in a bank.', 'I work at a bank.'],
      explanation: 'A permanent situation takes the present simple.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-014',
      type: 'rewrite',
      prompt: 'In questo momento sto scrivendo la tesi.',
      answers: ['At the moment I am writing my thesis.', "I'm writing my thesis at the moment."],
      explanation: 'Happening around now: present continuous.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'B1',
    },
    {
      id: 'f1-015',
      type: 'rewrite',
      prompt: 'Non mi piace il pesce.',
      answers: ["I don't like fish.", 'I do not like fish.'],
      explanation: 'The English subject is the person, not the thing: not "fish does not like me".',
      errorTags: ['state-verbs', 'false-friend'],
      level: 'A2',
    },
    {
      id: 'f1-016',
      type: 'build',
      prompt: 'she/not/usually/take/the bus',
      answers: ["She doesn't usually take the bus.", 'She does not usually take the bus.'],
      explanation: 'Adverbs of frequency go between the auxiliary and the main verb.',
      errorTags: ['word-order', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'f1-017',
      type: 'build',
      prompt: 'what time/you/finish/work/on Fridays?',
      answers: ['What time do you finish work on Fridays?'],
      explanation: 'A question about a routine needs the auxiliary "do" before the subject.',
      errorTags: ['question-form'],
      level: 'A2',
    },
    {
      id: 'f1-018',
      type: 'build',
      prompt: 'the market/open/at 9 a.m./every day',
      answers: ['The market opens at 9 a.m. every day.'],
      explanation: 'Opening hours are a timetable: present simple.',
      errorTags: ['present-simple-vs-continuous'],
      level: 'A2',
    },
    {
      id: 'f1-019',
      type: 'choice',
      prompt: 'She ___ to the radio while she cooks.',
      answers: ['listens', 'hears', 'is hearing', 'listen'],
      options: ['listens', 'hears', 'is hearing', 'listen'],
      explanation: '"Listen to" is deliberate, "hear" happens to you. Italian "sentire" covers both.',
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'f1-020',
      type: 'fill',
      prompt: 'Prices ___ (rise) quickly at the moment.',
      answers: ['are rising'],
      explanation: 'A trend in progress right now takes the present continuous, and this is exactly how a chart is described.',
      errorTags: ['present-simple-vs-continuous', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'f1-021',
      type: 'form',
      prompt: 'Her ___ of the topic is excellent.',
      root: 'KNOW',
      answers: ['knowledge'],
      explanation: 'know becomes knowledge, an uncountable noun: never "knowledges".',
      errorTags: ['word-formation', 'uncountable'],
      level: 'B1',
    },
    {
      id: 'f1-022',
      type: 'transform',
      prompt: 'I never drink coffee in the evening.',
      keyword: 'DO',
      given: 'I',
      answers: ["I don't ever drink coffee in the evening.", 'I do not ever drink coffee in the evening.'],
      explanation: 'never equals not ever: the negative moves onto the auxiliary, and "ever" stays after it.',
      errorTags: ['negative-form'],
      level: 'B1',
    },
    {
      id: 'f1-023',
      type: 'correct',
      prompt: 'Where you work?',
      answers: ['Where do you work?'],
      explanation: 'English questions need an auxiliary; Italian gets by with intonation alone.',
      errorTags: ['question-form'],
      level: 'A2',
    },
    {
      id: 'f1-024',
      type: 'vocab',
      prompt: 'FREQUENTARE UN CORSO',
      answers: ['to attend a course', 'attend a course', 'to take a course', 'take a course'],
      explanation: '"Frequent" as a verb means to visit a place often. For a course you attend or take it.',
      errorTags: ['false-friend'],
      level: 'B1',
    },
    { id: 'f1-025', type: 'choice', prompt: 'My parents usually ___ dinner at home.', answers: ['have'], options: ['have', 'are having', 'has', 'having'], explanation: 'Usually signals a routine, so use the present simple.', errorTags: ['present-simple-vs-continuous'], level: 'A2' },
    { id: 'f1-026', type: 'choice', prompt: 'Why ___ you ___ at me?', answers: ['are / looking'], options: ['are / looking', 'do / look', 'are / look', 'do / looking'], explanation: 'This is happening now, so use are + verb-ing.', errorTags: ['present-simple-vs-continuous', 'question-form'], level: 'A2' },
    { id: 'f1-027', type: 'choice', prompt: 'The university library ___ at 8 p.m. every weekday.', answers: ['closes'], options: ['closes', 'is closing', 'close', 'is close'], explanation: 'A regular timetable uses the present simple.', errorTags: ['present-simple-vs-continuous'], level: 'B1' },
    { id: 'f1-028', type: 'choice', prompt: 'I ___ what you mean.', answers: ['understand'], options: ['understand', 'am understanding', 'understands', 'understanding'], explanation: 'Understand is a state verb and normally does not take -ing.', errorTags: ['state-verbs'], level: 'A2' },
    { id: 'f1-029', type: 'choice', prompt: 'Look! The train ___.', answers: ['is arriving'], options: ['is arriving', 'arrives', 'arrive', 'is arrive'], explanation: 'Look signals an action in progress now.', errorTags: ['present-simple-vs-continuous'], level: 'A2' },
    { id: 'f1-030', type: 'choice', prompt: 'He never ___ his keys at home.', answers: ['forgets'], options: ['forgets', 'is forgetting', 'forget', 'does forget'], explanation: 'Never describes a habitual pattern; he needs third-person -s.', errorTags: ['present-simple-vs-continuous'], level: 'A2' },
    { id: 'f1-031', type: 'choice', prompt: 'This month we ___ a new project at work.', answers: ['are developing'], options: ['are developing', 'develop', 'develops', 'are develop'], explanation: 'This month is a temporary period around now.', errorTags: ['present-simple-vs-continuous'], level: 'B1' },
    { id: 'f1-032', type: 'choice', prompt: '___ your sister ___ any languages?', answers: ['Does / speak'], options: ['Does / speak', 'Is / speaking', 'Do / speaks', 'Does / speaks'], explanation: 'Questions about ability or general facts use does + bare infinitive.', errorTags: ['question-form'], level: 'A2' },
    { id: 'f1-033', type: 'choice', prompt: 'The price of fuel ___ every week at the moment.', answers: ['is changing'], options: ['is changing', 'changes', 'change', 'is change'], explanation: 'A changing trend in progress takes the continuous.', errorTags: ['present-simple-vs-continuous', 'esp-structure'], level: 'B2' },
    { id: 'f1-034', type: 'choice', prompt: 'She ___ to work by bus because her car is in the garage this week.', answers: ['is going'], options: ['is going', 'goes', 'go', 'is go'], explanation: 'This week makes the arrangement temporary, so use the continuous.', errorTags: ['present-simple-vs-continuous'], level: 'B1' },
    { id: 'f1-035', type: 'choice', prompt: 'Water ___ at 100°C.', answers: ['boils'], options: ['boils', 'is boiling', 'boil', 'does boil'], explanation: 'Scientific facts use the present simple.', errorTags: ['present-simple-vs-continuous'], level: 'B1' },
    { id: 'f1-036', type: 'choice', prompt: 'I ___ coffee today because I am trying to sleep better.', answers: ["am not drinking"], options: ["am not drinking", "don't drink", "doesn't drink", "not drinking"], explanation: 'Today is a temporary choice, so use the negative present continuous.', errorTags: ['present-simple-vs-continuous', 'negative-form'], level: 'B1' },
  ],
};
