import type { Unit } from '../types';

export const f2PastSimple: Unit = {
  id: 'f2',
  stage: 'foundations',
  order: 2,
  title: 'Past simple and irregular verbs',
  summary: 'The finished past: the tense the exam keeps coming back to.',
  level: 'A2',
  errorTags: ['past-simple', 'irregular-verb'],
  lesson: {
    rule: 'Use the past simple whenever you know, or imply, when something happened, and remember that once "did" appears the main verb goes back to its bare form.',
    schema: [
      { label: 'Regular verbs', value: 'add -ed: worked, studied, stopped' },
      { label: 'Irregular verbs', value: 'second column: go/went, see/saw, buy/bought' },
      { label: 'Question', value: 'did + subject + bare verb: did you go?' },
      { label: 'Negative', value: "did not + bare verb: I didn't go" },
      { label: 'Verb to be', value: 'was / were, with no "did": was he late?' },
      { label: 'Typical time words', value: 'yesterday, last week, in 2008, two hours ago, when...?' },
    ],
    examples: [
      {
        wrong: 'Did you went to the lecture?',
        right: 'Did you go to the lecture?',
        note: '"Did" already carries the past, so the verb stays bare.',
      },
      {
        wrong: 'I didn\'t saw him.',
        right: "I didn't see him.",
        note: 'Same rule in the negative.',
      },
      {
        wrong: 'He selled his car.',
        right: 'He sold his car.',
        note: 'Irregular verbs have to be memorised; there is no shortcut.',
      },
    ],
    traps: [
      'The third column is the past participle, not the past simple: "I have seen", but "I saw".',
      '"Was" and "were" never take "did": "did you were" does not exist.',
      'The -ed ending has three pronunciations: /t/ in worked, /d/ in played, /id/ in wanted.',
      'A question starting with "when" always takes the past simple, never the present perfect.',
    ],
  },
  cards: [
    {
      id: 'f2-001',
      type: 'choice',
      prompt: 'After years as an assistant, Alicia finally ___ a teacher.',
      answers: ['became', 'become', 'did became', 'has became'],
      options: ['became', 'become', 'did became', 'has became'],
      explanation: 'become / became / become. The past simple is the second column.',
      errorTags: ['irregular-verb', 'past-simple'],
      level: 'A2',
    },
    {
      id: 'f2-002',
      type: 'choice',
      prompt: "Vincent ___ his house yesterday. He's moving to Mexico.",
      answers: ['sold', 'has sold', 'selled', 'did sell'],
      options: ['sold', 'has sold', 'selled', 'did sell'],
      explanation: '"Yesterday" fixes the moment, so past simple. sell / sold / sold.',
      errorTags: ['past-simple', 'irregular-verb', 'time-adverbial'],
      level: 'A2',
    },
    {
      id: 'f2-003',
      type: 'fill',
      prompt: 'They ___ (leave) the office at seven last night.',
      answers: ['left'],
      explanation: 'leave / left / left.',
      errorTags: ['irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-004',
      type: 'fill',
      prompt: 'She ___ (not come) to the meeting on Monday.',
      answers: ["didn't come", 'did not come'],
      explanation: 'The negative uses did not plus the bare verb, never "did not came".',
      errorTags: ['negative-form', 'past-simple'],
      level: 'A2',
    },
    {
      id: 'f2-005',
      type: 'fill',
      prompt: '___ the results ___ (be) ready last Friday?',
      answers: ['Were / ready', 'Were the results ready'],
      hint: 'The verb is "be", so there is no "did".',
      explanation: '"Be" makes its own question by moving to the front: was, were.',
      errorTags: ['question-form', 'past-simple'],
      level: 'A2',
    },
    {
      id: 'f2-006',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO THINK',
      answers: ['thought, thought', 'thought thought', 'thought / thought'],
      explanation: 'think / thought / thought. Same pattern as buy, bring, catch, teach.',
      errorTags: ['irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-007',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO WRITE',
      answers: ['wrote, written', 'wrote written', 'wrote / written'],
      explanation: 'write / wrote / written. Never "has wrote".',
      errorTags: ['irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-008',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO RISE',
      answers: ['rose, risen', 'rose risen', 'rose / risen'],
      explanation: 'rise / rose / risen, intransitive. Do not confuse it with raise / raised / raised, which is transitive.',
      errorTags: ['irregular-verb', 'esp-trend-vocabulary'],
      level: 'B1',
    },
    {
      id: 'f2-009',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO FALL',
      answers: ['fell, fallen', 'fell fallen', 'fell / fallen'],
      explanation: 'fall / fell / fallen. Essential for describing charts.',
      errorTags: ['irregular-verb', 'esp-trend-vocabulary'],
      level: 'B1',
    },
    {
      id: 'f2-010',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO SPEND',
      answers: ['spent, spent', 'spent spent', 'spent / spent'],
      explanation: 'spend / spent / spent. Same shape as send, lend, build.',
      errorTags: ['irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-011',
      type: 'correct',
      prompt: 'Did you saw the email I sent?',
      answers: ['Did you see the email I sent?'],
      explanation: 'After "did" the verb is bare.',
      errorTags: ['question-form', 'past-simple'],
      level: 'A2',
    },
    {
      id: 'f2-012',
      type: 'correct',
      prompt: 'I was go to the bank this morning.',
      answers: ['I went to the bank this morning.'],
      explanation: 'The past simple of "go" is one word, "went". No auxiliary in a positive statement.',
      errorTags: ['past-simple', 'irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-013',
      type: 'correct',
      prompt: 'He teached us statistics last year.',
      answers: ['He taught us statistics last year.'],
      explanation: 'teach / taught / taught.',
      errorTags: ['irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-014',
      type: 'build',
      prompt: 'we/not/understand/the lecture/last week',
      answers: ["We didn't understand the lecture last week.", 'We did not understand the lecture last week.'],
      explanation: 'A finished period, so past simple; the negative goes on the auxiliary.',
      errorTags: ['negative-form', 'past-simple'],
      level: 'B1',
    },
    {
      id: 'f2-015',
      type: 'build',
      prompt: 'where/you/go/for dinner/last night?',
      answers: ['Where did you go for dinner last night?'],
      explanation: 'Question word, then auxiliary, then subject, then bare verb.',
      errorTags: ['question-form'],
      level: 'A2',
    },
    {
      id: 'f2-016',
      type: 'build',
      prompt: 'the index/fall/sharply/in 2022',
      answers: ['The index fell sharply in 2022.'],
      explanation: 'An explicit year closes the time frame: past simple, with the adverb after the verb.',
      errorTags: ['past-simple', 'esp-structure'],
      level: 'B2',
    },
    {
      id: 'f2-017',
      type: 'rewrite',
      prompt: 'Ieri ho parlato con il mio relatore.',
      answers: ['Yesterday I spoke to my supervisor.', 'I spoke to my supervisor yesterday.', 'I talked to my supervisor yesterday.'],
      explanation: 'Italian uses a compound past, English the simple past, because "yesterday" closes the time frame. A thesis supervisor is a "supervisor".',
      errorTags: ['past-simple', 'time-adverbial', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'f2-018',
      type: 'rewrite',
      prompt: 'Quando hai iniziato la magistrale?',
      answers: ["When did you start your master's?", "When did you start your master's degree?"],
      explanation: 'A "when" question takes the past simple. "Master" alone is not the degree in English.',
      errorTags: ['question-form', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'f2-019',
      type: 'rewrite',
      prompt: 'Non ho capito la domanda.',
      answers: ["I didn't understand the question.", 'I did not understand the question.'],
      explanation: 'A finished moment just now takes the past simple in ordinary speech.',
      errorTags: ['negative-form', 'past-simple'],
      level: 'A2',
    },
    {
      id: 'f2-020',
      type: 'choice',
      prompt: 'The company ___ three new analysts last month.',
      answers: ['hired', 'has hired', 'was hiring', 'hire'],
      options: ['hired', 'has hired', 'was hiring', 'hire'],
      explanation: '"Last month" is a closed period: past simple.',
      errorTags: ['past-simple', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'f2-021',
      type: 'transform',
      prompt: 'It was not necessary for us to pay in advance.',
      keyword: 'HAVE',
      given: 'We',
      answers: ["We didn't have to pay in advance.", 'We did not have to pay in advance.'],
      explanation: '"Not necessary" is "did not have to" in the past. Not the same as "mustn\'t", which is a prohibition.',
      errorTags: ['obligation', 'past-simple'],
      level: 'B2',
    },
    {
      id: 'f2-022',
      type: 'form',
      prompt: 'The project was a complete ___.',
      root: 'FAIL',
      answers: ['failure'],
      explanation: 'fail becomes failure. Word formation is a fixed section of the written exam.',
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'f2-023',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO BUY',
      answers: ['bought, bought', 'bought bought', 'bought / bought'],
      explanation: 'buy / bought / bought.',
      errorTags: ['irregular-verb'],
      level: 'A2',
    },
    {
      id: 'f2-024',
      type: 'vocab',
      prompt: 'Past simple e participio di: TO GROW',
      answers: ['grew, grown', 'grew grown', 'grew / grown'],
      explanation: 'grow / grew / grown. The noun is "growth", as in "growth rate".',
      errorTags: ['irregular-verb', 'esp-trend-vocabulary'],
      level: 'B1',
    },
  ],
};
