import type { Unit } from '../types';

export const f3Questions: Unit = {
  id: 'f3',
  stage: 'foundations',
  order: 3,
  title: 'Questions, negatives and auxiliaries',
  summary: 'The machinery every other tense is built on.',
  level: 'A2',
  errorTags: ['question-form', 'negative-form', 'word-order'],
  lesson: {
    rule: 'English builds questions and negatives with an auxiliary, and whichever auxiliary you use carries the tense, so the main verb always goes back to its bare form.',
    schema: [
      { label: 'Present simple', value: 'do / does: does she work? she does not work' },
      { label: 'Past simple', value: 'did: did she work? she did not work' },
      { label: 'Continuous', value: 'be: is she working? she is not working' },
      { label: 'Perfect', value: 'have: has she worked? she has not worked' },
      { label: 'Modals', value: 'the modal itself: can she work? she cannot work' },
      { label: 'Question word order', value: 'wh- + auxiliary + subject + verb' },
      { label: 'Subject questions', value: 'no auxiliary: who wrote this? what happened?' },
    ],
    examples: [
      {
        wrong: 'Where you live?',
        right: 'Where do you live?',
        note: 'Italian can ask with intonation alone. English needs the auxiliary.',
      },
      {
        wrong: 'Why she is late?',
        right: 'Why is she late?',
        note: 'The auxiliary comes before the subject, not after it.',
      },
      {
        wrong: "I don't have never been there.",
        right: 'I have never been there.',
        note: 'English allows one negative per clause. "Never" is already negative.',
      },
    ],
    traps: [
      'The double negative is normal in Italian and wrong in English: "non ho visto nessuno" is "I saw nobody" or "I did not see anybody".',
      'In a subject question there is no auxiliary: "Who called you?", not "Who did call you?".',
      'Short answers repeat the auxiliary, not the verb: "Do you smoke?" "No, I don\'t".',
      'Question tags flip the polarity: "You are coming, aren\'t you?".',
    ],
  },
  cards: [
    {
      id: 'f3-001',
      type: 'correct',
      prompt: 'Why she is always late?',
      answers: ['Why is she always late?'],
      explanation: 'In a question the auxiliary goes before the subject.',
      errorTags: ['question-form', 'word-order'],
      level: 'A2',
    },
    {
      id: 'f3-002',
      type: 'correct',
      prompt: "I didn't saw nobody at the office.",
      answers: ["I didn't see anybody at the office.", 'I saw nobody at the office.'],
      explanation: 'Two problems: the bare verb after "did", and only one negative per clause.',
      errorTags: ['negative-form', 'question-form'],
      level: 'B1',
    },
    {
      id: 'f3-003',
      type: 'choice',
      prompt: '___ wrote this report?',
      answers: ['Who', 'Who did', 'Whom did', 'Who does'],
      options: ['Who', 'Who did', 'Whom did', 'Who does'],
      explanation: 'When the question word is the subject there is no auxiliary at all.',
      errorTags: ['question-form'],
      level: 'B1',
    },
    {
      id: 'f3-004',
      type: 'choice',
      prompt: 'You have already sent it, ___?',
      answers: ["haven't you", "didn't you", "don't you", 'have you'],
      options: ["haven't you", "didn't you", "don't you", 'have you'],
      explanation: 'A question tag repeats the auxiliary and flips the polarity.',
      errorTags: ['question-form'],
      level: 'B2',
    },
    {
      id: 'f3-005',
      type: 'fill',
      prompt: '___ your colleagues ___ (speak) English at work?',
      answers: ['Do / speak', 'Do your colleagues speak'],
      explanation: 'Present simple question: do plus subject plus bare verb.',
      errorTags: ['question-form'],
      level: 'A2',
    },
    {
      id: 'f3-006',
      type: 'fill',
      prompt: 'He ___ (not can) come to the meeting yesterday.',
      answers: ["couldn't", 'could not'],
      hint: 'Modals have no "did".',
      explanation: 'A modal makes its own negative. "Didn\'t can" does not exist.',
      errorTags: ['modal', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'f3-007',
      type: 'build',
      prompt: 'you/eat/anything/today?',
      answers: ['Have you eaten anything today?'],
      explanation: '"Today" is an unfinished period, so the present perfect. In questions and negatives use "anything", not "something".',
      errorTags: ['question-form', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'f3-008',
      type: 'build',
      prompt: 'how long/it/take/to get there?',
      answers: ['How long does it take to get there?'],
      explanation: '"It takes" is the fixed expression for how long something lasts.',
      errorTags: ['question-form'],
      level: 'B1',
    },
    {
      id: 'f3-009',
      type: 'build',
      prompt: 'what/happen/at the end of the meeting?',
      answers: ['What happened at the end of the meeting?'],
      explanation: '"What" is the subject here, so no auxiliary: "what happened", not "what did happen".',
      errorTags: ['question-form'],
      level: 'B1',
    },
    {
      id: 'f3-010',
      type: 'rewrite',
      prompt: 'Non conosco nessuno qui.',
      answers: ["I don't know anybody here.", "I don't know anyone here.", 'I know nobody here.'],
      explanation: 'One negative only. Either "don\'t know anybody" or "know nobody".',
      errorTags: ['negative-form'],
      level: 'B1',
    },
    {
      id: 'f3-011',
      type: 'rewrite',
      prompt: 'Di cosa stai parlando?',
      answers: ['What are you talking about?'],
      explanation: 'English leaves the preposition at the end. "About what are you talking" is not natural.',
      errorTags: ['question-form', 'preposition'],
      level: 'B1',
    },
    {
      id: 'f3-012',
      type: 'rewrite',
      prompt: 'Non me lo ha mai detto.',
      answers: ['He has never told me.', 'She has never told me.', "He's never told me."],
      explanation: '"Never" already carries the negative, so the auxiliary stays positive.',
      errorTags: ['negative-form'],
      level: 'B1',
    },
    {
      id: 'f3-013',
      type: 'correct',
      prompt: 'Do you can send me the file?',
      answers: ['Can you send me the file?'],
      explanation: 'A modal never takes another auxiliary in front of it.',
      errorTags: ['modal', 'question-form'],
      level: 'A2',
    },
    {
      id: 'f3-014',
      type: 'correct',
      prompt: 'She is agree with us.',
      answers: ['She agrees with us.'],
      explanation: '"Agree" is a verb in English, not an adjective. Italian "essere d\'accordo" causes this one.',
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'f3-015',
      type: 'choice',
      prompt: 'A: Do you work on Saturdays? B: No, ___.',
      answers: ["I don't", "I do not work", 'I am not', 'I work not'],
      options: ["I don't", "I do not work", 'I am not', 'I work not'],
      explanation: 'A short answer repeats the auxiliary only.',
      errorTags: ['question-form'],
      level: 'A2',
    },
    {
      id: 'f3-016',
      type: 'choice',
      prompt: '___ many people at the presentation?',
      answers: ['Were there', 'There were', 'Was there', 'Did there be'],
      options: ['Were there', 'There were', 'Was there', 'Did there be'],
      explanation: '"There is / there are" makes its own question by inversion, and "people" is plural.',
      errorTags: ['question-form', 'quantifier'],
      level: 'B1',
    },
    {
      id: 'f3-017',
      type: 'transform',
      prompt: 'Nobody has explained the procedure to me.',
      keyword: 'BEEN',
      given: 'I have not',
      answers: ['I have not been told the procedure.', 'I have not been explained the procedure.'],
      explanation: 'When the doer is unknown or irrelevant, English reaches for the passive instead of a vague "they".',
      errorTags: ['passive', 'negative-form'],
      level: 'B2',
    },
    {
      id: 'f3-018',
      type: 'form',
      prompt: 'His ___ to answer the question surprised everyone.',
      root: 'REFUSE',
      answers: ['refusal'],
      explanation: 'refuse becomes refusal, like propose and proposal, arrive and arrival.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'f3-019',
      type: 'fill',
      prompt: 'There ___ (not be) any milk in the fridge.',
      answers: ["isn't", 'is not'],
      explanation: '"Milk" is uncountable, so it takes a singular verb and "any" in the negative.',
      errorTags: ['uncountable', 'quantifier'],
      level: 'A2',
    },
    {
      id: 'f3-020',
      type: 'build',
      prompt: 'why/you/not tell/me/earlier?',
      answers: ["Why didn't you tell me earlier?", 'Why did you not tell me earlier?'],
      explanation: 'Question word, auxiliary with the negative, subject, bare verb.',
      errorTags: ['question-form', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'f3-021',
      type: 'vocab',
      prompt: 'CHIEDERE UNA DOMANDA',
      answers: ['to ask a question', 'ask a question'],
      explanation: 'Questions are asked, never "made". "Make a question" is a calque of Italian "fare una domanda".',
      errorTags: ['do-vs-make'],
      level: 'A2',
    },
    {
      id: 'f3-022',
      type: 'correct',
      prompt: 'How many time do you need?',
      answers: ['How much time do you need?'],
      explanation: '"Time" here is uncountable, so "how much". "How many times" would mean how often.',
      errorTags: ['quantifier', 'uncountable'],
      level: 'B1',
    },
  ],
};
