import type { Unit } from '../types';

export const f4Articles: Unit = {
  id: 'f4',
  stage: 'foundations',
  order: 4,
  title: 'Articles, countables and quantifiers',
  summary: 'The small words that give an Italian away immediately.',
  level: 'B1',
  errorTags: ['article', 'uncountable', 'quantifier'],
  lesson: {
    rule: 'English drops the article in front of anything meant in general, and a group of everyday nouns that are plural in Italian are uncountable in English.',
    schema: [
      { label: 'General meaning', value: 'no article: Life is hard. Money matters.' },
      { label: 'One of many, first mention', value: 'a / an: I read a paper about it' },
      { label: 'Specific, already known', value: 'the: the paper you sent me' },
      { label: 'Uncountable, no plural', value: 'information, advice, news, research, knowledge, furniture, money' },
      { label: 'Countable quantity', value: 'many, few, a few, how many' },
      { label: 'Uncountable quantity', value: 'much, little, a little, how much' },
      { label: 'Either', value: 'some, any, a lot of, plenty of' },
    ],
    examples: [
      {
        wrong: 'The life is hard for a student.',
        right: 'Life is hard for a student.',
        note: 'No article before an abstract noun used in general.',
      },
      {
        wrong: 'He gave me some useful informations.',
        right: 'He gave me some useful information.',
        note: '"Information" has no plural. To count it: two pieces of information.',
      },
      {
        wrong: 'I have a few money left.',
        right: 'I have a little money left.',
        note: '"Money" is uncountable, so it takes "little", not "few".',
      },
    ],
    traps: [
      'Italian keeps the article where English drops it: "la vita", "il denaro", "gli italiani sono..." all lose it in English.',
      '"News" looks plural but takes a singular verb: "the news is good".',
      '"A few" means some, "few" means almost none. The article changes the whole message.',
      '"Some" in positive sentences, "any" in questions and negatives, with one exception: "any" in a positive means "whichever you like".',
    ],
  },
  cards: [
    {
      id: 'f4-001',
      type: 'choice',
      prompt: "We haven't got ___ milk in the fridge.",
      answers: ['any', 'some', 'the', 'a'],
      options: ['any', 'some', 'the', 'a'],
      explanation: 'Negative sentence with an uncountable noun: "any".',
      errorTags: ['quantifier', 'uncountable'],
      level: 'A2',
    },
    {
      id: 'f4-002',
      type: 'choice',
      prompt: 'I need more ___ before I decide.',
      answers: ['information', 'informations', 'an information', 'informations about'],
      options: ['information', 'informations', 'an information', 'informations about'],
      explanation: 'Uncountable: no plural and no "a".',
      errorTags: ['uncountable'],
      level: 'B1',
    },
    {
      id: 'f4-003',
      type: 'choice',
      prompt: 'She gave me a very useful piece of ___.',
      answers: ['advice', 'advices', 'advise', 'an advice'],
      options: ['advice', 'advices', 'advise', 'an advice'],
      explanation: '"Advice" is the noun, "advise" the verb, and it is uncountable.',
      errorTags: ['uncountable', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'f4-004',
      type: 'choice',
      prompt: 'The ___ from the markets ___ encouraging this morning.',
      answers: ['news / is', 'news / are', 'new / is', 'newses / are'],
      options: ['news / is', 'news / are', 'new / is', 'newses / are'],
      explanation: '"News" ends in -s but is uncountable and singular.',
      errorTags: ['uncountable'],
      level: 'B1',
    },
    {
      id: 'f4-005',
      type: 'correct',
      prompt: 'The Italians drink a lot of the coffee.',
      answers: ['Italians drink a lot of coffee.'],
      explanation: 'Two articles too many: a whole nationality and a substance in general take none.',
      errorTags: ['article'],
      level: 'B1',
    },
    {
      id: 'f4-006',
      type: 'correct',
      prompt: 'I am studying the economics at the university.',
      answers: ['I am studying economics at university.'],
      explanation: 'Subjects take no article, and "at university" means as a student, without "the".',
      errorTags: ['article'],
      level: 'B1',
    },
    {
      id: 'f4-007',
      type: 'correct',
      prompt: 'He did a lot of researches on the topic.',
      answers: ['He did a lot of research on the topic.'],
      explanation: '"Research" is uncountable. To count: two research projects, two studies.',
      errorTags: ['uncountable'],
      level: 'B2',
    },
    {
      id: 'f4-008',
      type: 'fill',
      prompt: 'How ___ students are enrolled this year?',
      answers: ['many'],
      explanation: '"Students" is countable, so "many".',
      errorTags: ['quantifier'],
      level: 'A2',
    },
    {
      id: 'f4-009',
      type: 'fill',
      prompt: 'How ___ time do we have left?',
      answers: ['much'],
      explanation: '"Time" as a quantity is uncountable, so "much".',
      errorTags: ['quantifier', 'uncountable'],
      level: 'A2',
    },
    {
      id: 'f4-010',
      type: 'choice',
      prompt: 'Very ___ people understood the question, only two or three.',
      answers: ['few', 'a few', 'little', 'a little'],
      options: ['few', 'a few', 'little', 'a little'],
      explanation: '"Few" stresses how small the number is. "A few" would mean some, which sounds positive.',
      errorTags: ['quantifier'],
      level: 'B2',
    },
    {
      id: 'f4-011',
      type: 'choice',
      prompt: 'There is ___ hope of finishing on time, so let us keep going.',
      answers: ['a little', 'little', 'few', 'a few'],
      options: ['a little', 'little', 'few', 'a few'],
      explanation: 'With the article it means some hope. Without it, almost none.',
      errorTags: ['quantifier'],
      level: 'B2',
    },
    {
      id: 'f4-012',
      type: 'rewrite',
      prompt: 'Il tempo è denaro.',
      answers: ['Time is money.'],
      explanation: 'Two abstract nouns in general: no articles at all.',
      errorTags: ['article'],
      level: 'A2',
    },
    {
      id: 'f4-013',
      type: 'rewrite',
      prompt: 'La disoccupazione è aumentata.',
      answers: ['Unemployment has risen.', 'Unemployment has increased.'],
      explanation: 'An abstract economic noun takes no article.',
      errorTags: ['article', 'esp-trend-vocabulary'],
      level: 'B2',
    },
    {
      id: 'f4-014',
      type: 'rewrite',
      prompt: 'Ho pochi soldi ma molto tempo.',
      answers: ['I have little money but a lot of time.', 'I have little money but plenty of time.'],
      explanation: 'Both nouns are uncountable, so "little" and "a lot of", never "few" or "many".',
      errorTags: ['quantifier', 'uncountable'],
      level: 'B1',
    },
    {
      id: 'f4-015',
      type: 'build',
      prompt: 'most paper/make/from wood',
      answers: ['Most paper is made from wood.'],
      explanation: 'Uncountable "paper" plus the passive, where Italian would use the impersonal "si fa".',
      errorTags: ['passive', 'uncountable', 'article'],
      level: 'B1',
    },
    {
      id: 'f4-016',
      type: 'build',
      prompt: 'there/be/too much/furniture/in this office',
      answers: ['There is too much furniture in this office.'],
      explanation: '"Furniture" is uncountable: singular verb and "much".',
      errorTags: ['uncountable', 'quantifier'],
      level: 'B1',
    },
    {
      id: 'f4-017',
      type: 'transform',
      prompt: 'We do not have many students this year.',
      keyword: 'FEW',
      given: 'We have',
      answers: ['We have few students this year.', 'We have very few students this year.'],
      explanation: '"Few" carries the negative meaning on its own, so the verb turns positive.',
      errorTags: ['quantifier', 'negative-form'],
      level: 'B2',
    },
    {
      id: 'f4-018',
      type: 'form',
      prompt: 'The report contains a lot of statistical ___.',
      root: 'INFORM',
      answers: ['information'],
      explanation: 'inform becomes information, and it stays singular.',
      errorTags: ['word-formation', 'uncountable'],
      level: 'B1',
    },
    {
      id: 'f4-019',
      type: 'box',
      prompt: 'The ___ of students who passed rose by 5%.',
      options: ['proportion', 'figures', 'percentage', 'amount'],
      answers: ['percentage'],
      explanation: '"Percentage" goes with a figure expressed in per cent. "Proportion" is a share, "figures" are raw numbers.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'f4-020',
      type: 'box',
      prompt: '___ for the Art Gallery went down significantly.',
      options: ['Figures', 'Percentage', 'Proportion', 'Graph'],
      answers: ['Figures'],
      explanation: '"Figures" means the numbers themselves, and it is plural.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'f4-021',
      type: 'correct',
      prompt: 'I have been in the Spain three times.',
      answers: ['I have been to Spain three times.'],
      explanation: 'Country names take no article, and you go "to" a place, not "in" it, with "been".',
      errorTags: ['article', 'preposition', 'been-vs-gone'],
      level: 'B1',
    },
    {
      id: 'f4-022',
      type: 'vocab',
      prompt: 'UN CONSIGLIO (uno solo)',
      answers: ['a piece of advice', 'one piece of advice'],
      explanation: 'Uncountable nouns are counted with "a piece of": a piece of advice, a piece of news, a piece of furniture.',
      errorTags: ['uncountable'],
      level: 'B1',
    },
  ],
};
