import type { Unit } from '../types';

export const f5WordOrder: Unit = {
  id: 'f5',
  stage: 'foundations',
  order: 5,
  title: 'Word order, adjectives and prepositions',
  summary: 'Where each piece of an English sentence has to sit.',
  level: 'B1',
  errorTags: ['word-order', 'adjective-order', 'preposition'],
  lesson: {
    rule: 'English word order is fixed: subject, verb, object, and nothing may come between the verb and its object; adjectives always go before the noun and never take a plural.',
    schema: [
      { label: 'Basic order', value: 'subject + verb + object: I read the report' },
      { label: 'Then manner, place, time', value: 'I read it carefully at home last night' },
      { label: 'Adjective', value: 'always before the noun, never plural: two red cars' },
      { label: 'Adverbs of frequency', value: 'before the main verb, after "be": I always work, I am always late' },
      { label: 'Fixed prepositions', value: 'depend on, interested in, good at, afraid of, rely on, consist of' },
      { label: 'Time', value: 'at 6 o\'clock, on Monday, in June, in 2026' },
    ],
    examples: [
      {
        wrong: 'She has a car red.',
        right: 'She has a red car.',
        note: 'The adjective comes first, with no exceptions.',
      },
      {
        wrong: 'I like very much this book.',
        right: 'I like this book very much.',
        note: 'Nothing separates the verb from its object.',
      },
      {
        wrong: 'It depends from the market.',
        right: 'It depends on the market.',
        note: 'Prepositions are fixed by the word, not translated.',
      },
    ],
    traps: [
      'Italian puts the adjective after the noun, so "a car red" feels natural and is always wrong.',
      'Adjectives never agree: "two reds cars" does not exist.',
      'Several adjectives follow an order: opinion, size, age, shape, colour, origin, material. A nice big old round brown Italian wooden table.',
      'Prepositions must be learnt with the word: interested IN, good AT, afraid OF, married TO, arrive IN a city but AT a station.',
    ],
  },
  cards: [
    {
      id: 'f5-001',
      type: 'correct',
      prompt: 'I bought a jacket blue yesterday.',
      answers: ['I bought a blue jacket yesterday.'],
      explanation: 'Adjective before the noun.',
      errorTags: ['adjective-order'],
      level: 'A2',
    },
    {
      id: 'f5-002',
      type: 'correct',
      prompt: 'They are two students italians.',
      answers: ['They are two Italian students.'],
      explanation: 'Adjective before the noun, no plural on the adjective, and nationalities take a capital letter.',
      errorTags: ['adjective-order'],
      level: 'A2',
    },
    {
      id: 'f5-003',
      type: 'correct',
      prompt: 'I like very much this course.',
      answers: ['I like this course very much.', 'I really like this course.'],
      explanation: 'The object follows the verb immediately.',
      errorTags: ['word-order'],
      level: 'B1',
    },
    {
      id: 'f5-004',
      type: 'correct',
      prompt: 'He speaks very well English.',
      answers: ['He speaks English very well.'],
      explanation: 'Same rule: the adverb of manner goes after the object.',
      errorTags: ['word-order'],
      level: 'B1',
    },
    {
      id: 'f5-005',
      type: 'choice',
      prompt: 'The result ___ the sample size.',
      answers: ['depends on', 'depends from', 'depends of', 'depends by'],
      options: ['depends on', 'depends from', 'depends of', 'depends by'],
      explanation: 'Fixed preposition: depend ON.',
      errorTags: ['preposition'],
      level: 'B1',
    },
    {
      id: 'f5-006',
      type: 'choice',
      prompt: 'She is very good ___ explaining difficult ideas.',
      answers: ['at', 'in', 'on', 'to'],
      options: ['at', 'in', 'on', 'to'],
      explanation: 'good AT, and after a preposition the verb takes -ing.',
      errorTags: ['preposition', 'preposition-plus-gerund'],
      level: 'B1',
    },
    {
      id: 'f5-007',
      type: 'choice',
      prompt: 'The sample ___ 240 undergraduates.',
      answers: ['consists of', 'consists in', 'consists on', 'consists by'],
      options: ['consists of', 'consists in', 'consists on', 'consists by'],
      explanation: 'consist OF. Italian "consistere in" leads straight to the mistake.',
      errorTags: ['preposition', 'false-friend'],
      level: 'B2',
    },
    {
      id: 'f5-008',
      type: 'fill',
      prompt: 'I am not interested ___ working abroad.',
      answers: ['in'],
      explanation: 'interested IN, and the preposition forces the -ing form.',
      errorTags: ['preposition'],
      level: 'B1',
    },
    {
      id: 'f5-009',
      type: 'fill',
      prompt: 'The meeting is ___ Monday ___ 10 a.m.',
      answers: ['on / at', 'on Monday at'],
      explanation: 'ON for days, AT for clock times, IN for months and years.',
      errorTags: ['preposition'],
      level: 'A2',
    },
    {
      id: 'f5-010',
      type: 'correct',
      prompt: 'We arrived to Cagliari at midnight.',
      answers: ['We arrived in Cagliari at midnight.'],
      explanation: 'You arrive IN a city or country, AT a station or building. Never "arrive to".',
      errorTags: ['preposition'],
      level: 'B1',
    },
    {
      id: 'f5-011',
      type: 'correct',
      prompt: 'She is married with a lawyer.',
      answers: ['She is married to a lawyer.'],
      explanation: 'married TO somebody, even though Italian says "con".',
      errorTags: ['preposition'],
      level: 'B1',
    },
    {
      id: 'f5-012',
      type: 'build',
      prompt: 'I/always/read/the newspaper/in the morning',
      answers: ['I always read the newspaper in the morning.'],
      explanation: 'An adverb of frequency goes before the main verb.',
      errorTags: ['word-order'],
      level: 'A2',
    },
    {
      id: 'f5-013',
      type: 'build',
      prompt: 'he/be/never/late/for a meeting',
      answers: ['He is never late for a meeting.'],
      explanation: 'With "be" the frequency adverb goes after the verb, not before.',
      errorTags: ['word-order'],
      level: 'B1',
    },
    {
      id: 'f5-014',
      type: 'rewrite',
      prompt: 'Ho letto un articolo molto interessante.',
      answers: ['I read a very interesting article.', "I've read a very interesting article."],
      explanation: 'Intensifier and adjective both before the noun.',
      errorTags: ['adjective-order'],
      level: 'B1',
    },
    {
      id: 'f5-015',
      type: 'rewrite',
      prompt: 'Dipende dal prezzo del petrolio.',
      answers: ['It depends on the price of oil.', 'It depends on oil prices.'],
      explanation: 'depend ON, and possession between things uses "of" or a compound noun.',
      errorTags: ['preposition'],
      level: 'B1',
    },
    {
      id: 'f5-016',
      type: 'choice',
      prompt: 'It is a ___ table.',
      answers: ['big old wooden', 'wooden old big', 'old wooden big', 'wooden big old'],
      options: ['big old wooden', 'wooden old big', 'old wooden big', 'wooden big old'],
      explanation: 'Adjective order: size, then age, then material.',
      errorTags: ['adjective-order'],
      level: 'B2',
    },
    {
      id: 'f5-017',
      type: 'transform',
      prompt: 'This topic interests me a lot.',
      keyword: 'INTERESTED',
      given: 'I am very',
      answers: ['I am very interested in this topic.'],
      explanation: 'The thing is "interesting", the person is "interested in".',
      errorTags: ['preposition', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'f5-018',
      type: 'correct',
      prompt: 'The lesson was very boring, I was very boring too.',
      answers: ['The lesson was very boring, and I was very bored too.'],
      explanation: '-ing describes the thing, -ed describes the person: boring lesson, bored student.',
      errorTags: ['adjective-order', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'f5-019',
      type: 'form',
      prompt: 'The results were highly ___.',
      root: 'SIGNIFY',
      answers: ['significant'],
      explanation: 'signify becomes significant, and the noun is significance.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'f5-020',
      type: 'fill',
      prompt: 'Sales increased ___ 15% in the second quarter.',
      answers: ['by'],
      explanation: 'The size of a change takes "by"; the level reached takes "to".',
      errorTags: ['preposition', 'esp-structure'],
      level: 'B2',
    },
  ],
};
