import type { Unit } from '../types';

export const f6FalseFriends: Unit = {
  id: 'f6',
  stage: 'foundations',
  order: 6,
  title: 'False friends and tricky words',
  summary: 'The words that look Italian and mean something else.',
  level: 'B1',
  errorTags: ['false-friend', 'uncountable', 'do-vs-make'],
  lesson: {
    rule: 'A word that looks like its Italian twin usually is not one: check the false friends before you trust them, because they are the mistakes that change your meaning rather than just your grammar.',
    schema: [
      { label: 'actually', value: 'in fact, not attualmente (which is currently)' },
      { label: 'eventually', value: 'in the end, not eventualmente (which is if necessary)' },
      { label: 'sensible', value: 'reasonable, not sensibile (which is sensitive)' },
      { label: 'argument', value: 'a dispute, not argomento (which is topic)' },
      { label: 'library', value: 'biblioteca, not libreria (which is bookshop)' },
      { label: 'educated', value: 'schooled, not educato (which is polite)' },
      { label: 'pretend', value: 'to fake, not pretendere (which is to demand or expect)' },
    ],
    examples: [
      {
        wrong: 'Actually I am working on my thesis.',
        right: 'Currently I am working on my thesis.',
        note: 'If you mean right now, "actually" says the opposite of what you think.',
      },
      {
        wrong: 'Can I make you a question?',
        right: 'Can I ask you a question?',
        note: 'Questions are asked, never made.',
      },
      {
        wrong: 'I have 25 years.',
        right: 'I am 25.',
        note: 'In English you ARE an age, you do not HAVE it.',
      },
    ],
    traps: [
      'The dangerous ones are not the words you do not know, but the ones you are sure about.',
      'do and make split the work: do a job, do homework, do research; make a decision, make a mistake, make an effort.',
      'Some false friends are also uncountable: advice, information, news.',
      'Academic vocabulary has its own: "argument" in an essay does mean a line of reasoning, but never a topic.',
    ],
  },
  cards: [
    {
      id: 'ff-001',
      type: 'vocab',
      prompt: 'ATTUALMENTE (in questo momento)',
      answers: ['currently', 'at the moment', 'at present'],
      explanation: "\"Actually\" does NOT mean attualmente: it means \"in fact\". It is the number one false friend for Italian speakers.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-002',
      type: 'vocab',
      prompt: 'EVENTUALMENTE (se dovesse servire)',
      answers: ['if necessary', 'possibly', 'if need be'],
      explanation: "\"Eventually\" means \"in the end, after a while\". An English speaker would understand the opposite of what you meant.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'ff-003',
      type: 'vocab',
      prompt: 'SENSIBILE (una persona che si commuove)',
      answers: ['sensitive'],
      explanation: "\"Sensible\" means level-headed, reasonable. Sensibile is \"sensitive\".",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-004',
      type: 'vocab',
      prompt: 'ARGOMENTO (di un testo, di una lezione)',
      answers: ['topic', 'subject'],
      explanation: "\"Argument\" is a dispute or a quarrel, not the subject being discussed.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-005',
      type: 'vocab',
      prompt: 'FABBRICA',
      answers: ['factory', 'plant'],
      explanation: "\"Fabric\" is cloth, material.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-006',
      type: 'vocab',
      prompt: 'CONFRONTARE (mettere a paragone)',
      answers: ['compare'],
      explanation: "\"To confront\" means to face somebody or something unpleasant.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'ff-007',
      type: 'vocab',
      prompt: 'EDUCATO (di buone maniere)',
      answers: ['polite'],
      explanation: "\"Educated\" means well schooled, having studied.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-008',
      type: 'vocab',
      prompt: 'LIBRERIA (il negozio dove compri i libri)',
      answers: ['bookshop', 'bookstore'],
      explanation: "\"Library\" is the biblioteca, where books are borrowed.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-009',
      type: 'vocab',
      prompt: 'MORBIDO',
      answers: ['soft'],
      explanation: "\"Morbid\" means gruesome, unhealthily dark.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-010',
      type: 'vocab',
      prompt: 'PRETENDERE (esigere)',
      answers: ['to demand', 'demand', 'to expect', 'expect'],
      explanation: "\"To pretend\" means to fake, to make believe.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'ff-011',
      type: 'vocab',
      prompt: 'ANNUNCIO PUBBLICITARIO',
      answers: ['advertisement', 'advert', 'ad'],
      explanation: "\"Advise\" is the verb, \"advice\" the noun. Three different words, easily mixed up.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'ff-012',
      type: 'vocab',
      prompt: 'ESIGENTE (un professore che chiede molto)',
      answers: ['demanding'],
      explanation: "\"Exigent\" is not current English. Say \"demanding\" or \"tough\".",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'ff-013',
      type: 'choice',
      prompt: 'I ___ you to read chapter four before the seminar.',
      answers: ['advise', 'advice', 'advertise', 'advis'],
      options: ['advise', 'advice', 'advertise', 'advis'],
      explanation: "\"Advise\" with an S is the verb, \"advice\" with a C is the noun, and it has no plural: never \"advices\".",
      errorTags: ['false-friend', 'uncountable'],
      level: 'B2',
    },
    {
      id: 'ff-014',
      type: 'choice',
      prompt: 'He gave me some very useful ___ about the exam.',
      answers: ['advice', 'advices', 'an advice', 'advise'],
      options: ['advice', 'advices', 'an advice', 'advise'],
      explanation: "\"Advice\" is uncountable: no plural, no article \"a\". To count it: \"a piece of advice\".",
      errorTags: ['uncountable', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-015',
      type: 'choice',
      prompt: 'I need more ___ before I can decide.',
      answers: ['information', 'informations', 'an information', 'informs'],
      options: ['information', 'informations', 'an information', 'informs'],
      explanation: "Like \"advice\", the words \"information\", \"news\", \"research\", \"knowledge\" and \"furniture\" have no plural in English.",
      errorTags: ['uncountable'],
      level: 'B1',
    },
    {
      id: 'ff-016',
      type: 'correct',
      prompt: 'The life is hard for a student.',
      answers: ['Life is hard for a student.'],
      explanation: "No article before an abstract or general noun: life, money, time, happiness. Italian puts one there, English does not.",
      errorTags: ['article'],
      level: 'B1',
    },
    {
      id: 'ff-017',
      type: 'correct',
      prompt: 'I have 25 years.',
      answers: ['I am 25.', 'I am 25 years old.'],
      explanation: "In English you ARE an age, you do not HAVE it: I am 25, she is 30.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-018',
      type: 'correct',
      prompt: 'It depends from the market.',
      answers: ['It depends on the market.'],
      explanation: "Fixed preposition: \"depend ON\". Others to learn by heart: interested in, good at, afraid of, rely on.",
      errorTags: ['preposition'],
      level: 'B1',
    },
    {
      id: 'ff-019',
      type: 'correct',
      prompt: 'Can I make you a question?',
      answers: ['Can I ask you a question?'],
      explanation: "Questions are asked, not made: ask a question. \"Make a question\" is a calque of Italian \"fare una domanda\".",
      errorTags: ['do-vs-make'],
      level: 'B1',
    },
    {
      id: 'ff-020',
      type: 'correct',
      prompt: 'I must to study tonight.',
      answers: ['I must study tonight.'],
      explanation: "After a modal (must, can, may, should, will) the verb takes the bare infinitive, with no \"to\".",
      errorTags: ['modal'],
      level: 'B1',
    },
    {
      id: 'ff-021',
      type: 'correct',
      prompt: 'She has a car red.',
      answers: ['She has a red car.'],
      explanation: "In English the adjective always comes BEFORE the noun, with no exceptions.",
      errorTags: ['adjective-order'],
      level: 'B1',
    },
    {
      id: 'ff-025',
      type: 'vocab',
      prompt: 'SCADENZA (di una consegna)',
      answers: ['deadline', 'due date'],
      explanation: "For food you say \"expiry date\" instead. Two different words for two contexts.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'ff-026',
      type: 'vocab',
      prompt: 'SOSTENERE UN ESAME',
      answers: ['to take an exam', 'take an exam', 'to sit an exam', 'sit an exam'],
      explanation: "\"To pass an exam\" means to succeed in it, not to sit it. You take an exam, or sit one in British English.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
  ],
};
