import type { Unit } from '../types';

export const x1Mock: Unit = {
  id: 'x1',
  stage: 'exam',
  order: 1,
  title: 'Exam practice',
  summary: 'The five sections of the written paper, mixed, exactly as they come up.',
  level: 'B2',
  errorTags: ['modal', 'conditional', 'reported-speech', 'esp-numbers', 'word-formation'],
  lesson: {
    rule: 'The written paper is half the mark and has five parts: multiple choice, sentence production from prompts, transformation around a keyword, an ESP gap fill from a word box, and word formation.',
    schema: [
      { label: 'Section 1', value: 'Multiple choice: grammar across the whole syllabus' },
      { label: 'Section 2', value: 'Write a correct sentence from the words given, adding and reordering' },
      { label: 'Section 3', value: 'Rewrite the sentence using the keyword, which cannot be changed' },
      { label: 'Section 4', value: 'ESP gap fill from a word box, with one extra word you will not need' },
      { label: 'Section 5', value: 'Word formation from a root given in capitals' },
      { label: 'The other half', value: 'Speaking: general conversation plus a presentation on a specialised text' },
    ],
    examples: [
      {
        wrong: 'They are thought that they moved to NYC.',
        right: 'They are thought to have moved to NYC.',
        note: 'In section 3 the keyword fixes the structure. Build the sentence around it.',
      },
      {
        wrong: 'He will not sue us unless we do not freeze his assets.',
        right: 'He will not sue us unless we freeze his assets.',
        note: '"Unless" already means "if not".',
      },
      {
        wrong: 'The proposal was rejected because of his behave.',
        right: 'The proposal was rejected because of his behaviour.',
        note: 'After a possessive the gap wants a noun.',
      },
    ],
    traps: [
      'In the transformation section the keyword must appear exactly as given, with no change at all.',
      'In the word box there is always one extra word. Do not force it in.',
      'In sentence production you may add words, but you may not change the ones you are given.',
      'Read what part of speech each word-formation gap needs before you write anything.',
    ],
  },
  cards: [
    {
      id: 'x1-001',
      type: 'choice',
      prompt: '___ we arrived at the beach we jumped into the sea.',
      answers: ['As soon as', 'Before', 'By the time', 'Until'],
      options: ['As soon as', 'Before', 'By the time', 'Until'],
      explanation: 'One action follows the other immediately.',
      errorTags: ['future-time-clause'],
      level: 'B2',
    },
    {
      id: 'x1-002',
      type: 'choice',
      prompt: 'I ___ for half an hour before the bus came.',
      answers: ['had been waiting', 'waited', 'have waited', 'was waiting'],
      options: ['had been waiting', 'waited', 'have waited', 'was waiting'],
      explanation: 'Duration running up to a past event: past perfect continuous.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'x1-003',
      type: 'choice',
      prompt: 'She ___ nervous because she ___ an interview before.',
      answers: [
        'was / had never had',
        'was / has never had',
        'is being / was never having',
        'has been / never had',
      ],
      options: [
        'was / had never had',
        'was / has never had',
        'is being / was never having',
        'has been / never had',
      ],
      explanation: 'A past story, so the earlier fact goes into the past perfect.',
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'x1-004',
      type: 'choice',
      prompt: 'Her father ___ retired by the time she ___.',
      answers: [
        'might have / graduates',
        'can have / will graduate',
        'has / graduated',
        'will have / will graduate',
      ],
      options: [
        'might have / graduates',
        'can have / will graduate',
        'has / graduated',
        'will have / will graduate',
      ],
      explanation: 'A guess about a future point, and "by the time" never takes the future.',
      errorTags: ['deduction', 'future-time-clause'],
      level: 'C1',
    },
    {
      id: 'x1-005',
      type: 'build',
      prompt: 'unlikely/the boss/be/be on time',
      answers: ['The boss is unlikely to be on time.', 'It is unlikely that the boss will be on time.'],
      explanation: 'Section 2 asks you to add words and reorder, but never to change the ones given.',
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'x1-006',
      type: 'build',
      prompt: 'say/Tom/get hungry/he',
      answers: ['Tom said he was getting hungry.', "Tom says he's getting hungry."],
      explanation: 'Reported speech pushes the tense back one step; the present version is also accepted.',
      errorTags: ['reported-speech', 'get'],
      level: 'B2',
    },
    {
      id: 'x1-007',
      type: 'build',
      prompt: 'from the window/the thieves/report/escape',
      answers: [
        'The thieves are reported to have escaped from the window.',
        'The thieves were reported to have escaped from the window.',
      ],
      explanation: 'The special passive with a past infinitive.',
      errorTags: ['reported-speech', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'x1-008',
      type: 'build',
      prompt: 'I/get/my PA/set up a meeting',
      answers: ['I got my PA to set up a meeting.', 'I will get my PA to set up a meeting.'],
      explanation: 'get + person + to + infinitive.',
      errorTags: ['get'],
      level: 'B2',
    },
    {
      id: 'x1-009',
      type: 'transform',
      prompt: 'Everyone knows they moved to NYC.',
      keyword: 'ARE',
      given: 'They',
      answers: ['They are known to have moved to NYC.'],
      explanation: 'The keyword fixes the passive; the move is earlier, so a past infinitive.',
      errorTags: ['reported-speech', 'past-infinitive'],
      level: 'C1',
    },
    {
      id: 'x1-010',
      type: 'transform',
      prompt: 'If we do not freeze his assets, he will sue us.',
      keyword: 'UNLESS',
      given: 'He will not sue us',
      answers: ['He will not sue us unless we freeze his assets.', "He won't sue us unless we freeze his assets."],
      explanation: '"Unless" absorbs the negative, so both halves flip.',
      errorTags: ['conditional', 'future-time-clause'],
      level: 'B2',
    },
    {
      id: 'x1-011',
      type: 'transform',
      prompt: 'She should finish her report by 12 p.m.',
      keyword: 'HAVE',
      given: 'At 12:05 she',
      answers: ['At 12:05 she should have finished her report.'],
      explanation: 'Expectation about a moment just past: should plus past infinitive.',
      errorTags: ['deduction', 'past-infinitive'],
      level: 'B2',
    },
    {
      id: 'x1-012',
      type: 'box',
      prompt: 'The graph shows information about the ___ of tourists who visited Brighton attractions.',
      options: ['proportion', 'over', 'by far', 'percentage', 'figures'],
      answers: ['proportion'],
      explanation: 'Section 4 always has one extra word in the box. Do not force it in.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'x1-013',
      type: 'box',
      prompt: 'The Pavilion was ___ the most popular attraction in the city.',
      options: ['by far', 'over', 'percentage', 'figures'],
      answers: ['by far'],
      explanation: '"By far" reinforces a superlative.',
      errorTags: ['esp-numbers'],
      level: 'B2',
    },
    {
      id: 'x1-014',
      type: 'form',
      prompt: 'The "ultimatum game" is a ___ Economics game involving two players.',
      root: 'BEHAVE',
      answers: ['behavioural', 'behavioral'],
      explanation: 'The gap sits before a noun, so it wants an adjective.',
      errorTags: ['word-formation'],
      level: 'C1',
    },
    {
      id: 'x1-015',
      type: 'form',
      prompt: 'The other player gets to accept or reject the ___.',
      root: 'PROPOSE',
      answers: ['proposal'],
      explanation: 'After "the" the gap wants a noun.',
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'x1-016',
      type: 'choice',
      prompt: 'This information is highly confidential, so you ___ discuss it with anyone.',
      answers: ["mustn't", "don't have to", 'are allowed to', 'should not have to'],
      options: ["mustn't", "don't have to", 'are allowed to', 'should not have to'],
      explanation: 'A prohibition, not an absence of obligation.',
      errorTags: ['obligation'],
      level: 'B2',
    },
    {
      id: 'x1-017',
      type: 'choice',
      prompt: 'My sister makes barely enough money to ___.',
      answers: ['get by', 'get along', 'get out', 'get over'],
      options: ['get by', 'get along', 'get out', 'get over'],
      explanation: '"Get by" is to manage on very little.',
      errorTags: ['phrasal-verb'],
      level: 'B2',
    },
    {
      id: 'x1-018',
      type: 'choice',
      prompt: 'If trains ___ more reliable, more people ___ use them.',
      answers: ['were / would', 'would / would', 'were / will', 'are / will'],
      options: ['were / would', 'would / would', 'were / will', 'are / will'],
      explanation: 'Second conditional with "were" for every person.',
      errorTags: ['conditional'],
      level: 'B2',
    },
  ],
};
