import type { Unit } from '../types';

export const x2Reading: Unit = {
  id: 'x2', stage: 'exam', order: 2, title: 'Reading: academic texts and news', summary: 'Read short texts, identify the main idea and answer from evidence.', level: 'B2', errorTags: ['esp-structure', 'esp-trend-vocabulary'],
  lesson: {
    rule: 'For reading comprehension, read the question first, find the relevant part of the text, then choose the answer supported by the words on the page rather than by outside knowledge.',
    schema: [
      { label: 'First reading', value: 'Read title and first/last sentence for the main idea.' },
      { label: 'Question reading', value: 'Underline the key word and locate its synonym in the text.' },
      { label: 'Answer choice', value: 'Select the option with evidence; reject answers that are too broad or add information.' },
      { label: 'Unknown word', value: 'Use the surrounding sentence and do not stop unless it changes the meaning.' },
    ],
    examples: [
      { wrong: 'I choose the answer because it sounds generally true.', right: 'I choose the answer because the passage states or clearly implies it.', note: 'Reading questions test evidence, not general knowledge.' },
      { wrong: 'I translate every word before answering.', right: 'I read for the main idea, then scan for the evidence.', note: 'Reading efficiently means selecting what matters.' },
    ],
    traps: ['An option can repeat words from the text but still change the meaning.', 'Words such as only, always and never often make an answer too strong.', 'A news headline may be dramatic; read the body for the precise claim.'],
  },
  cards: [
    { id: 'x2-001', type: 'reading', prompt: 'What is the main purpose of the study?', passage: { heading: 'Remote work and team performance', body: 'A university study followed 180 project teams for six months. It found that remote teams performed as well as office-based teams when they had clear goals and regular opportunities for informal communication. The researchers did not claim that location was irrelevant; instead, they argued that management practices were more important than location alone.' }, answers: ['To show that management practices can matter more than work location'], options: ['To show that management practices can matter more than work location', 'To prove that all remote teams perform better', 'To compare salaries in different offices', 'To argue that offices are unnecessary'], explanation: 'The passage says remote teams did well under specific conditions and stresses management practices over location alone.', errorTags: ['esp-structure'], level: 'B2' },
    { id: 'x2-002', type: 'reading', prompt: 'Which statement is supported by the passage?', passage: { heading: 'Remote work and team performance', body: 'A university study followed 180 project teams for six months. It found that remote teams performed as well as office-based teams when they had clear goals and regular opportunities for informal communication. The researchers did not claim that location was irrelevant; instead, they argued that management practices were more important than location alone.' }, answers: ['Informal communication was one condition linked to strong remote performance.'], options: ['Informal communication was one condition linked to strong remote performance.', 'Remote work always improves performance.', 'The study followed teams for several years.', 'Location has no effect in any situation.'], explanation: 'The passage explicitly names regular informal communication as one of the conditions.', errorTags: ['esp-structure'], level: 'B2' },
    { id: 'x2-003', type: 'news', prompt: 'What does the word “moderate” mean in this report?', passage: { heading: 'City transport use rises after fare change', body: 'Passenger journeys on the city tram network rose by 8% in the three months after a new off-peak fare was introduced, according to the local transport authority. Officials described the increase as moderate but encouraging, noting that weekday morning travel remained broadly unchanged. The authority will review the policy again in autumn.' }, answers: ['Not large, but positive'], options: ['Not large, but positive', 'Unexpected and negative', 'Equal to zero', 'Certain to continue'], explanation: 'Moderate describes an increase that is limited in size, while encouraging shows it is positive.', errorTags: ['esp-trend-vocabulary'], level: 'B2' },
    { id: 'x2-004', type: 'news', prompt: 'Which change did NOT occur according to the report?', passage: { heading: 'City transport use rises after fare change', body: 'Passenger journeys on the city tram network rose by 8% in the three months after a new off-peak fare was introduced, according to the local transport authority. Officials described the increase as moderate but encouraging, noting that weekday morning travel remained broadly unchanged. The authority will review the policy again in autumn.' }, answers: ['Weekday morning travel increased substantially.'], options: ['Weekday morning travel increased substantially.', 'Passenger journeys rose by 8%.', 'An off-peak fare was introduced.', 'The policy will be reviewed in autumn.'], explanation: 'The report says weekday morning travel remained broadly unchanged.', errorTags: ['esp-trend-vocabulary'], level: 'B2' },
  ],
};
