import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Gradient } from '@/components/london/gradient';
import { SafeTop } from '@/components/safe-top';
import { Gradients, London, Radius, Shadows } from '@/constants/london';

/** A focused start screen: the 60-minute clock begins only after Ready. */
export default function ExamScreen() {
  const router = useRouter();
  return <View style={styles.root}><ScrollView contentContainerStyle={styles.scroll}><SafeTop><Gradient colors={Gradients.sunset} style={styles.header}><View style={styles.headerContent}><Text style={styles.kicker}>MAGISTRALE MOCK EXAM</Text><Text style={styles.title}>Ready for the paper?</Text><Text style={styles.subtitle}>A mixed simulation built around the formats in your course material.</Text></View></Gradient></SafeTop><View style={styles.body}>
    <View style={styles.ticket}><Text style={styles.ticketKicker}>EXAM CONDITIONS</Text><View style={styles.statRow}><Stat icon="timer-outline" value="60 min" label="countdown" /><Stat icon="format-list-numbered" value="50" label="questions" /><Stat icon="layers-outline" value="Mixed" label="formats" /></View></View>
    <View style={styles.info}><Text style={styles.infoTitle}>What you will find</Text><Text style={styles.infoText}>Multiple choice, gap fills, word formation, transformations, sentence correction, reading passages, short news reports and ESP questions on data and graphs.</Text><Text style={styles.infoText}>The timer begins only when you press “I’m ready”. Once it reaches zero, the session closes and shows your result.</Text></View>
    <Pressable onPress={() => router.push({ pathname: '/study', params: { mode: 'exam', length: '50', timerSeconds: '3600', title: 'Magistrale mock exam' } })} style={({ pressed }) => [styles.start, pressed && styles.pressed]}><Text style={styles.startText}>I&apos;m ready — start exam</Text><MaterialCommunityIcons name="arrow-right" size={19} color={London.white} /></Pressable><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>Not now</Text></Pressable>
  </View></ScrollView></View>;
}
function Stat({ icon, value, label }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; value: string; label: string }) { return <View style={styles.stat}><MaterialCommunityIcons name={icon} size={20} color={London.gold} /><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: London.stone }, scroll: { paddingBottom: 36 }, header: { paddingBottom: 30, borderBottomLeftRadius: Radius.xl, borderBottomRightRadius: Radius.xl }, headerContent: { paddingHorizontal: 20, paddingTop: 18, gap: 5 }, kicker: { color: London.gold, fontSize: 10.5, letterSpacing: 1.4, fontWeight: '900' }, title: { color: London.white, fontSize: 31, fontWeight: '900' }, subtitle: { color: 'rgba(255,255,255,0.88)', fontSize: 14, lineHeight: 20 }, body: { padding: 20, gap: 16 }, ticket: { backgroundColor: London.royal, padding: 18, borderRadius: Radius.lg, gap: 15, ...Shadows.raised }, ticketKicker: { color: London.gold, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 }, statRow: { flexDirection: 'row', justifyContent: 'space-between' }, stat: { alignItems: 'center', gap: 3, flex: 1 }, statValue: { color: London.white, fontSize: 18, fontWeight: '900' }, statLabel: { color: 'rgba(255,255,255,0.72)', fontSize: 10.5 }, info: { backgroundColor: London.white, borderRadius: Radius.lg, borderWidth: 1, borderColor: London.line, padding: 17, gap: 9, ...Shadows.card }, infoTitle: { color: London.cab, fontSize: 17, fontWeight: '900' }, infoText: { color: London.cab, fontSize: 13.5, lineHeight: 20 }, start: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, backgroundColor: London.flagRed, borderRadius: Radius.md, paddingVertical: 16 }, startText: { color: London.white, fontSize: 16, fontWeight: '900' }, back: { alignItems: 'center', paddingVertical: 5 }, backText: { color: London.tube, fontSize: 14, fontWeight: '800' }, pressed: { opacity: 0.82 } });
