import { MaterialCommunityIcons } from '@expo/vector-icons';
import Constants from 'expo-constants';
import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeTop } from '@/components/safe-top';
import { London, Radius, Shadows } from '@/constants/london';
import { allCards, units } from '@/src/content';
import { useAppState } from '@/src/store/app-state';
import { pageBuildId } from '@/src/sync/auto-update';
import { accountStatus, createAccount, ensureSession, findFriend, flush, pendingCount, sendFriendRequest, signIn, signOut, type AuthAccount, type FriendSearchResult } from '@/src/sync/remote';

export default function Settings() {
 const {profile,setProfile,answers}=useAppState(); const [auth,setAuth]=useState<AuthAccount|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[found,setFound]=useState<FriendSearchResult|null>(null),[pending,setPending]=useState(0);
 const refresh=()=>void accountStatus().then(setAuth); useEffect(()=>{let live=true;void(async()=>{await flush();await ensureSession();if(live){setAuth(await accountStatus());setPending(pendingCount());}})();return()=>{live=false};},[answers.length]);
 return <View style={s.root}><SafeTop><View style={s.top}><Pressable onPress={()=>router.back()}><MaterialCommunityIcons name="arrow-left" size={25} color={London.cab}/></Pressable><Text style={s.topTitle}>Settings</Text><View style={{width:25}}/></View></SafeTop><ScrollView contentContainerStyle={s.body} showsVerticalScrollIndicator={false}>
 <Text style={s.label}>ACCOUNT & FRIENDS</Text><Text style={s.copy}>Set this up once to keep your progress, find friends and use the same account on another device.</Text>
 <View style={s.card}><Text style={s.title}>Your identity</Text><TextInput value={profile.name} onChangeText={name=>setProfile({name})} placeholder="Your name" placeholderTextColor={London.fog} style={s.input} maxLength={40}/><TextInput value={profile.nickname} onChangeText={nickname=>setProfile({nickname:nickname.replace(/\s/g,'')})} placeholder="Unique nickname" placeholderTextColor={London.fog} style={s.input} maxLength={24} autoCapitalize="none"/><Text style={s.copy}>Friends can only find you through your nickname. Your name appears on Profile.</Text></View>
 <View style={s.card}>{auth&&!auth.anonymous?<><Text style={s.title}>Signed in</Text><Text style={s.email}>{auth.email}</Text><Text style={s.copy}>Your progress is securely linked to this account.</Text><Pressable onPress={()=>void signOut().then(()=>setAuth(null))}><Text style={s.signout}>Sign out</Text></Pressable></>:<><Text style={s.title}>Save your progress everywhere</Text><Text style={s.copy}>Creating an account upgrades this device, so current results remain with you.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Email" placeholderTextColor={London.fog} autoCapitalize="none" keyboardType="email-address" style={s.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Password (at least 6 characters)" placeholderTextColor={London.fog} secureTextEntry style={s.input}/><View style={s.actions}><Pressable onPress={()=>void createAccount(email,password).then(m=>{setMessage(m??'Check your email to confirm the account.');refresh();})} style={s.primary}><Text style={s.primaryText}>Create account</Text></Pressable><Pressable onPress={()=>void signIn(email,password).then(m=>{setMessage(m??'Signed in successfully.');refresh();})} style={s.secondary}><Text style={s.secondaryText}>Sign in</Text></Pressable></View>{message?<Text style={s.message}>{message}</Text>:null}</>}</View>
 {auth&&!auth.anonymous?<View style={s.card}><Text style={s.title}>Add a friend</Text><Text style={s.copy}>Search their exact nickname and send a private request.</Text><View style={s.search}><TextInput value={query} onChangeText={setQuery} placeholder="@nickname" placeholderTextColor={London.fog} autoCapitalize="none" style={s.searchInput}/><Pressable onPress={()=>void findFriend(query).then(r=>{setFound(r);setMessage(r?'':'No learner found with that nickname.');})} style={s.searchBtn}><MaterialCommunityIcons name="magnify" size={19} color={London.white}/></Pressable></View>{found?<View style={s.result}><Text style={s.email}>@{found.nickname}</Text><Pressable onPress={()=>void sendFriendRequest(found.id).then(m=>{setMessage(m??'Friend request sent.');setFound(null);})} style={s.add}><Text style={s.primaryText}>Add</Text></Pressable></View>:null}{message?<Text style={s.message}>{message}</Text>:null}</View>:null}
 <Text style={s.label}>APP INFORMATION</Text><View style={s.card}><Info icon="cards-outline" label="Activities available" value={`${allCards.length}`}/><Info icon="folder-outline" label="Topics" value={`${units.length}`}/><Info icon="tag-outline" label="Version" value={Constants.expoConfig?.version??'--'}/><Info icon="update" label="Build" value={pageBuildId()??'dev'}/><Info icon="cloud-check-outline" label="Sync" value={pending?`${pending} waiting`:'Up to date'}/></View>
 </ScrollView></View>;
}
function Info({icon,label,value}:{icon:keyof typeof MaterialCommunityIcons.glyphMap;label:string;value:string}){return <View style={s.info}><MaterialCommunityIcons name={icon} size={18} color={London.fog}/><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:London.stone},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:20,paddingVertical:15,backgroundColor:London.white,borderBottomWidth:1,borderBottomColor:London.line},topTitle:{color:London.cab,fontSize:19,fontWeight:'900'},body:{padding:20,paddingBottom:80,gap:12},label:{color:London.flagRed,fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:5},card:{backgroundColor:London.white,borderRadius:Radius.lg,padding:16,gap:10,borderWidth:1,borderColor:London.line,...Shadows.card},title:{color:London.cab,fontSize:16,fontWeight:'900'},email:{color:London.tube,fontSize:13.5,fontWeight:'800'},copy:{color:London.fog,fontSize:12.5,lineHeight:18},input:{borderWidth:1,borderColor:London.line,borderRadius:Radius.sm,paddingHorizontal:12,paddingVertical:11,color:London.cab,fontSize:14},actions:{flexDirection:'row',gap:8},primary:{flex:1,backgroundColor:London.royal,borderRadius:Radius.sm,paddingVertical:12,alignItems:'center'},primaryText:{color:London.white,fontSize:12,fontWeight:'900'},secondary:{flex:1,borderWidth:1,borderColor:London.tube,borderRadius:Radius.sm,paddingVertical:12,alignItems:'center'},secondaryText:{color:London.tube,fontSize:12,fontWeight:'900'},signout:{color:London.flagRed,fontSize:13,fontWeight:'900',paddingVertical:5},message:{color:London.tube,fontSize:12,lineHeight:17},search:{flexDirection:'row',gap:8},searchInput:{flex:1,borderWidth:1,borderColor:London.line,borderRadius:Radius.sm,paddingHorizontal:12,paddingVertical:10,color:London.cab},searchBtn:{width:43,alignItems:'center',justifyContent:'center',backgroundColor:London.royal,borderRadius:Radius.sm},result:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:11,borderRadius:Radius.sm,backgroundColor:London.sky},add:{backgroundColor:London.park,borderRadius:999,paddingHorizontal:14,paddingVertical:7},info:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:9},infoLabel:{flex:1,color:London.cab,fontSize:14},infoValue:{color:London.fog,fontSize:13,fontWeight:'700'}});
