import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { Gradient } from '@/components/london/gradient';
import { AppIcon } from '@/components/app-icon';
import { LondonHeroArt } from '@/components/london/hero-art';
import { SafeTop } from '@/components/safe-top';
import { Gradients, London, Radius, Shadows } from '@/constants/london';
import { allCards, PRACTICE_FORMATS } from '@/src/content';

const PROFILE_SIZED_ART = { width: '74%' as const, height: 224, right: -20, top: -12, opacity: 0.58 };

/** First level of Practice: choose how to train before choosing the topic. */
export default function PracticeScreen() {
  const router = useRouter();
  return <View style={styles.root}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
    <SafeTop><Gradient colors={Gradients.royal} style={[styles.header, { minHeight: 205 }]}><LondonHeroArt style={[styles.headerArt, PROFILE_SIZED_ART]} /><View style={styles.headerContent}><Text style={styles.kicker}>PRACTICE STATION</Text><Text style={styles.title}>How do you want to practise?</Text><Text style={styles.subtitle}>Choose an exercise type, then select one of the 21 study areas.</Text></View></Gradient></SafeTop>
    <View style={styles.body}>
      <Pressable onPress={() => router.push('/study')} style={({ pressed }) => [styles.mixed, pressed && styles.pressed]}><View style={styles.mixedIcon}><AppIcon name="shuffle-variant" size={25} color={London.royal} /></View><View style={styles.flex}><Text style={styles.mixedKicker}>MIXED SESSION</Text><Text style={styles.mixedTitle}>Surprise me</Text><Text style={styles.mixedText}>A varied session from every topic and format.</Text></View><AppIcon name="arrow-right" size={21} color={London.white} /></Pressable>
      <Pressable onPress={() => router.push('/exam' as never)} style={({ pressed }) => [styles.exam, pressed && styles.pressed]}><AppIcon name="timer-sand" size={25} color={London.gold} /><View style={styles.flex}><Text style={styles.examKicker}>EXAM PRACTICE</Text><Text style={styles.examTitle}>50 questions · 60 minutes</Text><Text style={styles.examText}>A timed mixed mock based on your magistrale course.</Text></View><AppIcon name="arrow-right" size={21} color={London.white} /></Pressable>
      <Text style={styles.sectionKicker}>CHOOSE AN EXERCISE TYPE</Text>
      <View style={styles.list}>{PRACTICE_FORMATS.map((format) => { const count = allCards.filter((card) => format.types.includes(card.type)).length; return <Pressable key={format.id} onPress={() => router.push({ pathname: '/practice' as never, params: { format: format.id } })} style={({ pressed }) => [styles.format, pressed && styles.pressed]}><View style={styles.formatIcon}><AppIcon name={format.icon} size={23} color={London.white} /></View><View style={styles.flex}><Text style={styles.formatTitle}>{format.title}</Text><Text style={styles.formatText}>{format.subtitle}</Text><Text style={styles.count}>{count} activities available</Text></View><AppIcon name="chevron-right" size={22} color={London.tube} /></Pressable>; })}</View>
    </View>
  </ScrollView></View>;
}

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: London.stone }, scroll: { paddingBottom: 130 }, header: { paddingBottom: 26, borderBottomLeftRadius: Radius.xl, borderBottomRightRadius: Radius.xl }, headerArt: { position: 'absolute', width: '66%', height: 205, right: -20, top: -10, opacity: 0.48 }, headerContent: { paddingHorizontal: 20, paddingTop: 14, gap: 4 }, kicker: { color: London.gold, fontSize: 10.5, letterSpacing: 1.4, fontWeight: '900' }, title: { color: London.white, fontSize: 29, lineHeight: 35, fontWeight: '900', maxWidth: '82%' }, subtitle: { color: 'rgba(255,255,255,0.86)', fontSize: 13.5, lineHeight: 20, maxWidth: '76%' }, body: { padding: 20, gap: 14 }, mixed: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: London.flagRed, padding: 16, borderRadius: Radius.lg, ...Shadows.raised }, mixedIcon: { width: 48, height: 48, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: London.gold }, exam: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: London.royal, padding: 16, borderRadius: Radius.lg, ...Shadows.raised }, examKicker: { color: London.gold, fontSize: 9.5, letterSpacing: 1.1, fontWeight: '900' }, examTitle: { color: London.white, fontSize: 17, fontWeight: '900', marginTop: 1 }, examText: { color: 'rgba(255,255,255,0.82)', fontSize: 12, marginTop: 2 }, flex: { flex: 1 }, mixedKicker: { color: London.gold, fontSize: 9.5, letterSpacing: 1.1, fontWeight: '900' }, mixedTitle: { color: London.white, fontSize: 18, fontWeight: '900', marginTop: 1 }, mixedText: { color: 'rgba(255,255,255,0.85)', fontSize: 12, marginTop: 2 }, sectionKicker: { color: London.flagRed, fontSize: 10, letterSpacing: 1.4, fontWeight: '900', marginTop: 6 }, list: { gap: 11 }, format: { flexDirection: 'row', alignItems: 'center', gap: 13, padding: 15, backgroundColor: London.white, borderRadius: Radius.lg, borderWidth: 1, borderColor: London.line, ...Shadows.card }, formatIcon: { width: 47, height: 47, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: London.royal }, formatTitle: { color: London.cab, fontSize: 16, fontWeight: '900' }, formatText: { color: London.fog, fontSize: 12.5, lineHeight: 18, marginTop: 2 }, count: { color: London.tube, fontSize: 10.5, fontWeight: '800', marginTop: 4 }, pressed: { opacity: 0.82 } });
