import { MaterialCommunityIcons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Gradient } from '@/components/london/gradient';
import { LondonHeroArt } from '@/components/london/hero-art';
import { RewardBadge } from '@/components/london/reward-badge';
import { SafeTop } from '@/components/safe-top';
import { Gradients, London, Radius, Shadows } from '@/constants/london';
import { computeRewards, isUnlocked, type Reward } from '@/src/domain/rewards';
import { useAppState } from '@/src/store/app-state';

export default function ProfileScreen() {
  const { profile, setProfile, answers } = useAppState(); const rewards = computeRewards(answers); const unlocked = rewards.filter(isUnlocked); const featured = useMemo(() => profile.featuredRewardIds.filter((id) => unlocked.some((r) => r.id === id)), [profile.featuredRewardIds, unlocked]); const [choosing, setChoosing] = useState(false);
  const toggle = (reward: Reward) => { const selected = featured.includes(reward.id); if ((!selected && featured.length >= 4) || !isUnlocked(reward)) return; setProfile({ featuredRewardIds: selected ? featured.filter((id) => id !== reward.id) : [...featured, reward.id] }); };
  const openSettings = () => router.push('../settings');
  return <View style={s.root}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><SafeTop><Gradient colors={Gradients.royal} style={s.header}><LondonHeroArt variant="profile" style={s.art} /><View style={s.head}><Text style={s.kicker}>YOUR LONDON LEARNER PASS</Text><Text style={s.title}>Hi, {profile.name.trim() || 'Learner'}</Text><Text style={s.sub}>Keep learning, collect rewards and connect with your study circle.</Text><Pressable onPress={openSettings} style={s.settings}><MaterialCommunityIcons name="cog-outline" size={18} color={London.royal}/><Text style={s.settingsText}>Settings</Text></Pressable></View></Gradient></SafeTop><View style={s.body}>
    <Text style={s.label}>FRIENDS</Text><Pressable onPress={openSettings} style={s.friends}><View style={s.friendIcon}><MaterialCommunityIcons name="account-group-outline" size={24} color={London.royal}/></View><View style={s.flex}><Text style={s.cardTitle}>Your study circle</Text><Text style={s.copy}>Add friends from Settings using their unique nickname. Accepted friends will appear here.</Text></View><MaterialCommunityIcons name="chevron-right" size={24} color={London.fog}/></Pressable>
    <View style={s.showHead}><Text style={s.label}>YOUR SHOWCASE</Text><Text style={s.count}>{featured.length}/4</Text></View><Text style={s.copy}>Tap an empty place to choose a reward.</Text><View style={s.showcase}>{[0,1,2,3].map((slot) => { const reward = unlocked.find((r) => r.id === featured[slot]); return <Pressable key={slot} onPress={() => setChoosing(true)} style={s.slot}>{reward ? <RewardBadge reward={reward} size={58}/> : <><MaterialCommunityIcons name="plus" size={20} color={London.gold}/><Text style={s.slotText}>Add reward</Text></>}</Pressable>; })}</View>
    {choosing ? <View style={s.chooser}><View style={s.chooserHead}><Text style={s.cardTitle}>Choose your rewards</Text><Pressable onPress={() => setChoosing(false)}><MaterialCommunityIcons name="close" size={20} color={London.fog}/></Pressable></View>{unlocked.length ? <View style={s.grid}>{unlocked.map((reward) => { const selected=featured.includes(reward.id); return <Pressable key={reward.id} onPress={() => toggle(reward)} style={[s.reward, selected && s.selected]}><RewardBadge reward={reward} size={44}/><Text numberOfLines={1} style={s.rewardName}>{reward.title}</Text>{selected ? <View style={s.check}><MaterialCommunityIcons name="check" size={12} color={London.white}/></View> : null}</Pressable>; })}</View> : <Text style={s.copy}>Complete activities to earn your first reward.</Text>}</View> : null}
    <Pressable onPress={openSettings} style={s.friends}><View style={s.friendIcon}><MaterialCommunityIcons name="account-cog-outline" size={21} color={London.royal}/></View><View style={s.flex}><Text style={s.cardTitle}>Account & friends</Text><Text style={s.copy}>Name, nickname, sign-in and friend requests</Text></View><MaterialCommunityIcons name="chevron-right" size={24} color={London.fog}/></Pressable>
  </View></ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:London.stone},scroll:{paddingBottom:130},header:{minHeight:245,paddingBottom:25,borderBottomLeftRadius:Radius.xl,borderBottomRightRadius:Radius.xl},art:{position:'absolute',width:'74%',height:224,right:-20,top:-12,opacity:.58},head:{paddingHorizontal:20,paddingTop:16,gap:7},kicker:{color:London.gold,fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{color:London.white,fontSize:31,fontWeight:'900'},sub:{maxWidth:'79%',color:'rgba(255,255,255,.85)',fontSize:13.5,fontWeight:'600',lineHeight:19},settings:{marginTop:6,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:13,paddingVertical:9,borderRadius:999,backgroundColor:London.white},settingsText:{color:London.royal,fontSize:12.5,fontWeight:'900'},body:{padding:20,gap:13},label:{color:London.flagRed,fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:8},friends:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:London.white,borderRadius:Radius.lg,borderWidth:1,borderColor:London.line,padding:15,...Shadows.card},friendIcon:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:London.sky},flex:{flex:1,gap:3},cardTitle:{color:London.cab,fontSize:15,fontWeight:'900'},copy:{color:London.fog,fontSize:12,lineHeight:17},showHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},count:{color:London.gold,fontSize:13,fontWeight:'900'},showcase:{flexDirection:'row',gap:9,backgroundColor:London.royal,borderRadius:Radius.lg,padding:14,justifyContent:'space-between',...Shadows.raised},slot:{flex:1,height:67,borderRadius:17,alignItems:'center',justifyContent:'center',gap:2,backgroundColor:'rgba(255,255,255,.1)',borderWidth:1,borderColor:'rgba(255,255,255,.16)'},slotText:{color:'rgba(255,255,255,.7)',fontSize:8.5,fontWeight:'800'},chooser:{backgroundColor:London.white,borderRadius:Radius.lg,padding:15,gap:12,borderWidth:1,borderColor:London.line,...Shadows.card},chooserHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},reward:{width:'31.7%',alignItems:'center',gap:5,borderRadius:Radius.md,paddingVertical:10,backgroundColor:London.stone,borderWidth:1,borderColor:London.line},selected:{borderColor:London.gold,borderWidth:2,backgroundColor:'#FFFDF7'},rewardName:{maxWidth:'90%',color:London.cab,fontSize:10,fontWeight:'800'},check:{position:'absolute',top:5,right:5,width:18,height:18,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:London.park}});
