import { Image } from 'expo-image';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppIcon } from '@/components/app-icon';
import { Gradient } from '@/components/london/gradient';
import { LondonHeroArt } from '@/components/london/hero-art';
import { RewardBadge } from '@/components/london/reward-badge';
import { SafeTop } from '@/components/safe-top';
import { Gradients, London, Radius, Shadows } from '@/constants/london';
import { avatarFor } from '@/src/avatars';
import { computeRewards, isUnlocked, type Reward } from '@/src/domain/rewards';
import { useAppState } from '@/src/store/app-state';
import { accountStatus, answerFriendRequest, findFriend, getFriendships, sendFriendRequest, type Friendship, type FriendSearchResult } from '@/src/sync/remote';

export default function Profile() {
  const { profile, setProfile, answers } = useAppState();
  const unlocked = computeRewards(answers).filter(isUnlocked);
  const featured = useMemo(() => profile.featuredRewardIds.filter((id) => unlocked.some((reward) => reward.id === id)), [profile.featuredRewardIds, unlocked]);
  const [chooser, setChooser] = useState(false); const [signed, setSigned] = useState(false); const [friends, setFriends] = useState<Friendship[]>([]); const [query, setQuery] = useState(''); const [found, setFound] = useState<FriendSearchResult | null>(null); const [note, setNote] = useState('');
  const load = () => void getFriendships().then(setFriends);
  useFocusEffect(useCallback(() => () => setChooser(false), []));
  useEffect(() => { void accountStatus().then((a) => { setSigned(!!a && !a.anonymous); if (a && !a.anonymous) load(); }); }, []);
  const toggle = (reward: Reward) => { const on = featured.includes(reward.id); if (!isUnlocked(reward) || (!on && featured.length >= 4)) return; setProfile({ featuredRewardIds: on ? featured.filter((id) => id !== reward.id) : [...featured, reward.id] }); setChooser(false); };
  const accepted = friends.filter((friend) => friend.status === 'accepted'); const incoming = friends.filter((friend) => friend.incoming && friend.status === 'pending');
  return <View style={s.root}><ScrollView contentContainerStyle={s.scroll} onTouchStart={() => chooser && setChooser(false)}>
    <SafeTop><Gradient colors={Gradients.royal} style={s.header}><LondonHeroArt variant="profile" style={s.art}/><View style={s.head}><Text style={s.kicker}>YOUR LONDON LEARNER PASS</Text><View style={s.greeting}><Image source={avatarFor(profile.avatarId).source} contentFit="cover" style={s.headAvatar}/><Text style={s.title}>Hi, {profile.name || 'Learner'}</Text></View><Pressable onPress={() => router.push('../settings')} style={s.settings}><AppIcon name="cog-outline" size={18} color={London.royal}/><Text style={s.settingsText}>Settings</Text></Pressable></View></Gradient></SafeTop>
    <View style={s.body}><View style={s.heading}><Text style={s.label}>YOUR SHOWCASE</Text><Text style={s.count}>{featured.length}/4</Text></View><Text style={s.copy}>Tap a place to choose or remove a reward.</Text><View style={s.show}>{[0, 1, 2, 3].map((index) => { const reward = unlocked.find((item) => item.id === featured[index]); return <Pressable key={index} onPress={() => setChooser((value) => !value)} style={s.slot}>{reward ? <RewardBadge reward={reward} size={58}/> : <><AppIcon name="plus" size={20} color={London.gold}/><Text style={s.slotText}>Add reward</Text></>}</Pressable>; })}</View>
      {chooser ? <View style={s.card} onStartShouldSetResponder={() => true}><View style={s.chooserHead}><Text style={s.cardTitle}>Choose your rewards</Text><Pressable onPress={() => setChooser(false)} hitSlop={12}><AppIcon name="close" size={20} color={London.fog}/></Pressable></View><View style={s.grid}>{unlocked.map((reward) => <Pressable key={reward.id} onPress={() => toggle(reward)} style={[s.reward, featured.includes(reward.id) && s.selected]}><RewardBadge reward={reward} size={43}/><Text numberOfLines={1} style={s.rewardText}>{reward.title}</Text></Pressable>)}</View></View> : null}
      <Text style={s.label}>FRIENDS</Text>{signed ? <><View style={s.card}><Text style={s.cardTitle}>Your friends</Text>{accepted.length ? accepted.map((friend) => <View key={friend.id} style={s.friend}><Image source={avatarFor(friend.avatarId).source} contentFit="cover" style={s.friendAvatar}/><Text style={s.blue}>@{friend.nickname}</Text></View>) : <Text style={s.copy}>No friends yet.</Text>}</View>{incoming.length ? <View style={s.card}><Text style={s.cardTitle}>Friend requests</Text>{incoming.map((friend) => <View key={friend.id} style={s.result}><Text style={s.blue}>@{friend.nickname}</Text><View style={s.actions}><Pressable onPress={() => void answerFriendRequest(friend.id, true).then(load)} style={s.add}><Text style={s.addText}>Accept</Text></Pressable><Pressable onPress={() => void answerFriendRequest(friend.id, false).then(load)}><Text style={s.decline}>Decline</Text></Pressable></View></View>)}</View> : null}<View style={s.card}><Text style={s.cardTitle}>Add a friend</Text><Text style={s.copy}>Search their exact nickname.</Text><View style={s.search}><TextInput value={query} onChangeText={setQuery} placeholder="@nickname" placeholderTextColor={London.fog} autoCapitalize="none" style={s.input}/><Pressable onPress={() => void findFriend(query).then((result) => { setFound(result); setNote(result ? '' : 'No learner found with that nickname.'); })} style={s.searchBtn}><AppIcon name="magnify" size={19} color={London.white}/></Pressable></View>{found ? <View style={s.result}><Text style={s.blue}>@{found.nickname}</Text><Pressable onPress={() => void sendFriendRequest(found.id).then((message) => { setNote(message ?? 'Friend request sent.'); setFound(null); load(); })} style={s.add}><Text style={s.addText}>Add</Text></Pressable></View> : null}{note ? <Text style={s.copy}>{note}</Text> : null}</View></> : <Pressable onPress={() => router.push('../settings')} style={s.card}><Text style={s.cardTitle}>Create an account to add friends</Text></Pressable>}</View>
  </ScrollView></View>;
}
const s = StyleSheet.create({root:{flex:1,backgroundColor:London.stone},scroll:{paddingBottom:130},header:{minHeight:205,paddingBottom:25,borderBottomLeftRadius:Radius.xl,borderBottomRightRadius:Radius.xl},art:{position:'absolute',width:'74%',height:224,right:-20,top:-12,opacity:.58},head:{paddingHorizontal:20,paddingTop:16,gap:7},kicker:{color:London.gold,fontSize:10,fontWeight:'900',letterSpacing:1.3},greeting:{flexDirection:'row',alignItems:'center',gap:10},headAvatar:{width:46,height:46,borderRadius:23,borderWidth:2,borderColor:London.gold},title:{color:London.white,fontSize:31,fontWeight:'900'},settings:{alignSelf:'flex-start',flexDirection:'row',gap:6,padding:10,borderRadius:99,backgroundColor:London.white},settingsText:{color:London.royal,fontWeight:'900'},body:{padding:20,gap:13},heading:{flexDirection:'row',justifyContent:'space-between'},label:{color:London.flagRed,fontSize:10,fontWeight:'900',letterSpacing:1.4},count:{color:London.gold,fontWeight:'900'},copy:{color:London.fog,fontSize:12.5,lineHeight:18},show:{flexDirection:'row',gap:9,backgroundColor:London.royal,borderRadius:Radius.lg,padding:14},slot:{flex:1,height:67,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.1)'},slotText:{color:'rgba(255,255,255,.7)',fontSize:8.5,fontWeight:'800'},card:{backgroundColor:London.white,borderRadius:Radius.lg,padding:15,gap:10,borderWidth:1,borderColor:London.line,...Shadows.card},chooserHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},cardTitle:{color:London.cab,fontSize:16,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},reward:{width:'31%',alignItems:'center',padding:8,borderWidth:1,borderColor:London.line,borderRadius:Radius.md},selected:{borderColor:London.gold,borderWidth:2},rewardText:{fontSize:10,fontWeight:'800',color:London.cab},friend:{flexDirection:'row',alignItems:'center',gap:9},friendAvatar:{width:30,height:30,borderRadius:15,backgroundColor:London.sky},search:{flexDirection:'row',gap:8},input:{flex:1,borderWidth:1,borderColor:London.line,borderRadius:Radius.sm,padding:11,color:London.cab},searchBtn:{width:43,alignItems:'center',justifyContent:'center',backgroundColor:London.royal,borderRadius:Radius.sm},result:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:11,borderRadius:Radius.sm,backgroundColor:London.sky},blue:{color:London.tube,fontSize:14,fontWeight:'900'},actions:{flexDirection:'row',alignItems:'center',gap:12},add:{backgroundColor:London.park,borderRadius:99,paddingHorizontal:14,paddingVertical:7},addText:{color:London.white,fontSize:12,fontWeight:'900'},decline:{color:London.flagRed,fontSize:12,fontWeight:'900'}});
