import type { Deck } from '../types';

/**
 * The ESP thread of the course: describing charts, tables and figures in
 * English. It is the part of the syllabus that overlaps with what Nicola
 * actually studies (data analysis, financial markets) and the part no general
 * language app covers.
 */
export const chartsAndData: Deck = {
  id: 'esp',
  title: 'Charts and data in English',
  description:
    'Describing trends, percentages and tables: the ESP vocabulary you need for the exam and for your thesis.',
  syllabusUnits: [2, 7, 13],
  level: 'B2',
  cards: [
    {
      id: 'esp-001',
      type: 'vocab',
      prompt: 'GRAFICO A TORTA',
      answers: ['pie chart', 'a pie chart'],
      explanation: "Bar chart, line graph, scatter plot are the other three you need.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'esp-002',
      type: 'vocab',
      prompt: 'AUMENTARE BRUSCAMENTE (di un valore)',
      answers: ['to soar', 'soar', 'to surge', 'surge', 'to rocket', 'rocket'],
      explanation: "Scale of intensity: rise or increase (neutral), then climb, then soar, surge, rocket (strong).",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-003',
      type: 'vocab',
      prompt: 'CROLLARE (di un mercato)',
      answers: ['to plummet', 'plummet', 'to plunge', 'plunge', 'to collapse', 'collapse'],
      explanation: "Scale downwards: fall or decrease (neutral), then decline, drop, plummet, plunge, collapse.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-004',
      type: 'vocab',
      prompt: 'RIMANERE STABILE',
      answers: [
        'to remain stable',
        'remain stable',
        'to level off',
        'level off',
        'to plateau',
        'plateau',
      ],
      explanation: "\"To level off\" is the verb you want when the curve flattens after a climb.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-005',
      type: 'vocab',
      prompt: 'OSCILLARE / FLUTTUARE',
      answers: ['to fluctuate', 'fluctuate'],
      explanation: "The noun is \"fluctuation\", the adjective \"volatile\", a golden word in finance.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-006',
      type: 'choice',
      prompt: 'Sales increased ___ 15% in the second quarter.',
      answers: ['by', 'of', 'with', 'for'],
      options: ['by', 'of', 'with', 'for'],
      explanation: "The size of the change takes \"by\". The level reached takes \"to\": \"rose to 40%\".",
      errorTags: ['preposition'],
      level: 'B2',
    },
    {
      id: 'esp-007',
      type: 'choice',
      prompt: 'There was a sharp ___ in unemployment between 2020 and 2021.',
      answers: ['rise', 'raise', 'arise', 'rising'],
      options: ['rise', 'raise', 'arise', 'rising'],
      explanation: "\"Rise\" is the noun and the intransitive verb: it goes up by itself. \"Raise\" is transitive: you lift something. \"Arise\" means to come up, of a problem.",
      errorTags: ['false-friend', 'irregular-verb'],
      level: 'B2',
    },
    {
      id: 'esp-008',
      type: 'choice',
      prompt: 'The chart ___ the distribution of students by faculty.',
      answers: ['shows', 'says', 'tells', 'explains to'],
      options: ['shows', 'says', 'tells', 'explains to'],
      explanation: "A chart \"shows\", \"illustrates\" or \"represents\". \"Say\" and \"tell\" are for people.",
      errorTags: ['false-friend'],
      level: 'B1',
    },
    {
      id: 'esp-009',
      type: 'choice',
      prompt: 'Roughly one ___ of the sample was under 25.',
      answers: ['third', 'three', 'thirds', 'tierce'],
      options: ['third', 'three', 'thirds', 'tierce'],
      explanation: "Fractions take the ordinal: one third, two thirds, a quarter, three quarters.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'esp-010',
      type: 'choice',
      prompt: 'The figures ___ that inflation is slowing down.',
      answers: ['suggest', 'suggests', 'is suggesting', 'suggesting'],
      options: ['suggest', 'suggests', 'is suggesting', 'suggesting'],
      explanation: "\"Figures\" is plural, so no -s on the verb. It is the most frequent slip in written reports.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'esp-011',
      type: 'rewrite',
      prompt: 'Il grafico mostra un aumento costante tra il 2019 e il 2023.',
      answers: [
        'The chart shows a steady increase between 2019 and 2023.',
        'The graph shows a steady rise between 2019 and 2023.',
      ],
      explanation: "\"Steady\" means constant and regular. Its opposite is \"sharp\" or \"sudden\".",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-012',
      type: 'rewrite',
      prompt: 'I prezzi sono saliti leggermente nella prima metà dell\'anno.',
      answers: [
        'Prices rose slightly in the first half of the year.',
        'Prices increased slightly in the first half of the year.',
      ],
      explanation: "Adverbs worth keeping: slightly, gradually, steadily, sharply, dramatically. They go after the verb.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-013',
      type: 'rewrite',
      prompt: 'Nel complesso, il trend è positivo.',
      answers: ['Overall, the trend is positive.', 'On the whole, the trend is positive.'],
      explanation: "Useful openers for commenting on a chart: Overall, On the whole, Broadly speaking.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-014',
      type: 'rewrite',
      prompt: 'Il valore più alto è stato raggiunto a marzo.',
      answers: [
        'The highest value was reached in March.',
        'The peak was reached in March.',
        'Values peaked in March.',
      ],
      explanation: "\"Peak\" works as a noun (the highest point) and as a verb (to reach the top). The low point is the \"trough\".",
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'esp-015',
      type: 'rewrite',
      prompt: 'I dati sono stati raccolti tramite un questionario.',
      answers: [
        'The data were collected through a questionnaire.',
        'The data was collected through a questionnaire.',
      ],
      explanation: "The passive is the normal voice of academic writing: what counts is the method, not who applied it.",
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'esp-016',
      type: 'fill',
      prompt: 'The blue line ___ (represent) the control group.',
      answers: ['represents'],
      explanation: "Present simple to describe what is in the chart: it is a permanent fact of the figure.",
      errorTags: ['word-formation'],
      level: 'B1',
    },
    {
      id: 'esp-017',
      type: 'fill',
      prompt: 'Between 2015 and 2018 the index ___ (remain) broadly unchanged.',
      answers: ['remained'],
      explanation: "A closed, finished period: past simple. \"Broadly unchanged\" means essentially flat.",
      errorTags: ['present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'esp-018',
      type: 'fill',
      prompt: 'Since January the rate ___ (fall) by two percentage points.',
      answers: ['has fallen'],
      explanation: "Mind the vocabulary: \"percentage points\" is not \"per cent\". From 6% to 4% is a fall of 2 points, but of 33 per cent.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'C1',
    },
    {
      id: 'esp-019',
      type: 'vocab',
      prompt: 'ASSE ORIZZONTALE / ASSE VERTICALE',
      answers: ['horizontal axis and vertical axis', 'x-axis and y-axis'],
      explanation: "The plural of \"axis\" is \"axes\". The wording on it is the \"label\", and the key is the \"legend\".",
      errorTags: ['word-formation'],
      level: 'B2',
    },
    {
      id: 'esp-020',
      type: 'vocab',
      prompt: 'MEDIA (aritmetica)',
      answers: ['average', 'mean', 'the mean'],
      explanation: "In statistics: mean, median, mode, range.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-021',
      type: 'vocab',
      prompt: 'TASSO DI CRESCITA',
      answers: ['growth rate', 'the growth rate'],
      explanation: "Useful family: interest rate, exchange rate, unemployment rate, inflation rate.",
      errorTags: ['false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-022',
      type: 'choice',
      prompt: 'Compared ___ last year, revenues are up by 8%.',
      answers: ['with', 'at', 'from', 'than'],
      options: ['with', 'at', 'from', 'than'],
      explanation: "\"Compared with\" and \"compared to\" are both fine. \"Compared than\" never is.",
      errorTags: ['preposition'],
      level: 'B2',
    },
    {
      id: 'esp-023',
      type: 'choice',
      prompt: 'The sample ___ of 240 undergraduate students.',
      answers: ['consisted', 'consisted in', 'was consisting', 'consists in'],
      options: ['consisted', 'consisted in', 'was consisting', 'consists in'],
      explanation: "\"Consist OF\" means to be made up of. Italian \"consistere in\" leads straight to the mistake.",
      errorTags: ['preposition', 'false-friend'],
      level: 'B2',
    },
    {
      id: 'esp-024',
      type: 'correct',
      prompt: 'The datas shows a clear trend.',
      answers: ['The data show a clear trend.', 'The data shows a clear trend.'],
      explanation: "\"Datas\" does not exist in any register. \"Data\" is already the plural of \"datum\", and in academic English it takes a plural verb.",
      errorTags: ['uncountable'],
      level: 'B2',
    },
    {
      id: 'esp-025',
      type: 'correct',
      prompt: 'In the graph we can see that the sales are increased of 10%.',
      answers: ['The graph shows that sales increased by 10%.'],
      explanation: "Three mistakes: \"are increased\" (wrong passive, increase is intransitive here), \"of\" instead of \"by\", and the article in front of \"sales\" used in a general sense.",
      errorTags: ['passive', 'preposition', 'article'],
      level: 'B2',
    },
    {
      id: 'esp-026',
      type: 'rewrite',
      prompt: 'Vale la pena notare che il campione era piuttosto piccolo.',
      answers: [
        'It is worth noting that the sample was rather small.',
        "It's worth noting that the sample was quite small.",
      ],
      explanation: "\"It is worth + -ing\" is a formula to keep ready for discussing the limitations of a study.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'C1',
    },
  ],
};
