import type { Deck } from '../types';

/**
 * Syllabus lessons 2-3. Every sentence is written from scratch (ADR-007) and set
 * in the world the learner actually lives in: university, data, financial markets.
 */
export const presentPerfectVsPastSimple: Deck = {
  id: 'ppps',
  title: 'Present perfect or past simple',
  description:
    'The classic Italian mistake: "I have seen him yesterday". When the past is closed and when it is still open.',
  syllabusUnits: [2, 3],
  level: 'B1',
  cards: [
    // --- correct: la frase contiene l'errore tipico, va riscritta giusta ---
    {
      id: 'ppps-001',
      type: 'correct',
      prompt: 'I have seen him yesterday.',
      answers: ['I saw him yesterday.'],
      explanation: "\"Yesterday\" closes the time frame: the moment is finished and identified, so the past simple is compulsory. Italian says \"l'ho visto ieri\" with a compound past, and that is where the mistake comes from.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-002',
      type: 'correct',
      prompt: 'I have finished the exam two hours ago.',
      answers: ['I finished the exam two hours ago.'],
      explanation: "\"Ago\" always points to an exact moment in the past, so it takes the past simple. Rule of thumb: where there is \"ago\", there is no \"have\".",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-003',
      type: 'correct',
      prompt: 'I live in Milan since 2023.',
      answers: ['I have lived in Milan since 2023.', "I've lived in Milan since 2023."],
      explanation: "Italian uses the present (\"vivo a Milano dal 2023\"), English does not. An action that started in the past and is still going on takes the present perfect.",
      errorTags: ['present-perfect-vs-past-simple', 'for-since'],
      level: 'B1',
    },
    {
      id: 'ppps-004',
      type: 'correct',
      prompt: 'I study English for ten years.',
      answers: [
        'I have studied English for ten years.',
        'I have been studying English for ten years.',
        "I've studied English for ten years.",
        "I've been studying English for ten years.",
      ],
      explanation: "The same calque from Italian. The continuous form stresses the duration, and it is the one a native speaker would reach for here.",
      errorTags: ['present-perfect-vs-past-simple', 'for-since'],
      level: 'B1',
    },
    {
      id: 'ppps-005',
      type: 'correct',
      prompt: 'Did you ever work with R?',
      answers: ['Have you ever worked with R?'],
      explanation: "\"Ever\" asks whether something happened at any point in your life, which is still open, so present perfect. \"Did you work with R?\" is only right about a finished period, such as a job that ended.",
      errorTags: ['present-perfect-vs-past-simple', 'question-form'],
      level: 'B1',
    },
    {
      id: 'ppps-006',
      type: 'correct',
      prompt: 'I am knowing this dataset very well.',
      answers: ['I know this dataset very well.'],
      explanation: "\"Know\" is a state verb: it describes a state, not an action, and never takes the -ing form. Same family: believe, understand, belong, need, want.",
      errorTags: ['state-verbs'],
      level: 'B1',
    },
    {
      id: 'ppps-007',
      type: 'correct',
      prompt: "She is gone to the library, she'll be back at six.",
      answers: [
        "She has gone to the library, she'll be back at six.",
        "She's gone to the library, she'll be back at six.",
      ],
      explanation: "A direct calque of \"\u00e8 andata\". In English the perfect auxiliary is always \"have\", never \"be\": has gone, has arrived, has come.",
      errorTags: ['been-vs-gone', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'ppps-008',
      type: 'correct',
      prompt: 'I have been to the conference last March.',
      answers: ['I went to the conference last March.', 'I was at the conference last March.'],
      explanation: "\"Last March\" is a closed time frame, so past simple. Careful though: \"I have been to Berlin\", with no time expression, is correct and means you have been there at least once.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial', 'been-vs-gone'],
      level: 'B1',
    },
    {
      id: 'ppps-009',
      type: 'correct',
      prompt: 'When have you submitted the report?',
      answers: ['When did you submit the report?'],
      explanation: "A question starting with \"when\" asks for an exact moment, and an exact moment is closed past. Never \"when\" plus present perfect.",
      errorTags: ['present-perfect-vs-past-simple', 'question-form'],
      level: 'B1',
    },
    {
      id: 'ppps-010',
      type: 'correct',
      prompt: 'The market has crashed in 2008.',
      answers: ['The market crashed in 2008.'],
      explanation: "An explicit date identifies a finished moment, so past simple. \"The market has crashed\" with no date would mean it just happened and the effects are visible now.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-011',
      type: 'correct',
      prompt: 'How long do you know your supervisor?',
      answers: [
        'How long have you known your supervisor?',
        "How long've you known your supervisor?",
      ],
      explanation: "\"How long\" about a situation still going on takes the present perfect. And since \"know\" is a state verb, no continuous: \"have you known\", not \"have you been knowing\".",
      errorTags: ['for-since', 'state-verbs', 'question-form'],
      level: 'B2',
    },
    {
      id: 'ppps-012',
      type: 'correct',
      prompt: "I didn't finish yet.",
      answers: ["I haven't finished yet.", 'I have not finished yet.'],
      explanation: "\"Yet\" signals that the thing is still pending, so the past is not closed: present perfect. It always goes at the end.",
      errorTags: ['present-perfect-vs-past-simple', 'negative-form', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-013',
      type: 'correct',
      prompt: 'He has wrote the introduction.',
      answers: ['He has written the introduction.', "He's written the introduction."],
      explanation: "After \"have\" comes the past participle (third column), not the past simple: write / wrote / written. Very common even among people who know the present perfect rule.",
      errorTags: ['irregular-verb'],
      level: 'B1',
    },
    {
      id: 'ppps-014',
      type: 'correct',
      prompt: 'I have already send you the file.',
      answers: ['I have already sent you the file.', "I've already sent you the file."],
      explanation: "Past participle: send / sent / sent. Note where \"already\" sits: between the auxiliary and the verb.",
      errorTags: ['irregular-verb', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-015',
      type: 'correct',
      prompt: 'We are here since two hours.',
      answers: ['We have been here for two hours.', "We've been here for two hours."],
      explanation: "Two mistakes in five words: the present perfect is needed, and length of time takes \"for\", not \"since\". \"Since\" wants a starting point (since 2023, since Monday), \"for\" an amount of time (for two hours).",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'ppps-016',
      type: 'correct',
      prompt: 'Yesterday I have gone to the lecture.',
      answers: ['Yesterday I went to the lecture.'],
      explanation: "\"Yesterday\" plus present perfect again, this time with the adverb at the front: moving it does not change the rule. Go / went / gone.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'ppps-017',
      type: 'correct',
      prompt: 'I am here in Italy from January.',
      answers: ['I have been here in Italy since January.', "I've been in Italy since January."],
      explanation: "The Italian \"da\" of time is never \"from\" when it marks the start of something still going on: use \"since\" plus the present perfect.",
      errorTags: ['for-since', 'preposition', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },

    // --- fill: un solo spazio, verbo fra parentesi ---
    {
      id: 'ppps-018',
      type: 'fill',
      prompt: 'I ___ (not / read) the paper yet.',
      answers: ["haven't read", 'have not read'],
      hint: "\"Yet\" tells you the matter is still open.",
      explanation: "Negative present perfect. Mind the pronunciation: the participle \"read\" sounds /red/, like the colour.",
      errorTags: ['present-perfect-vs-past-simple', 'negative-form', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'ppps-019',
      type: 'fill',
      prompt: 'The professor ___ (publish) three articles last year.',
      answers: ['published'],
      explanation: "\"Last year\" is a finished period: past simple.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-020',
      type: 'fill',
      prompt: '___ you ever ___ (present) your work in English?',
      answers: ['Have / presented', 'Have you ever presented'],
      hint: "Two gaps: auxiliary at the front, participle after \"ever\".",
      explanation: "A life experience with no time given: present perfect. Fixed question pattern: Have + subject + ever + participle.",
      errorTags: ['present-perfect-vs-past-simple', 'question-form'],
      level: 'B1',
    },
    {
      id: 'ppps-021',
      type: 'fill',
      prompt: 'She ___ (work) at the central bank since she graduated.',
      answers: ['has worked', 'has been working'],
      explanation: "Started in the past, still true today: present perfect. Note that after \"since\" the verb goes to the past simple (\"graduated\"), because graduating is one finished moment.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'ppps-022',
      type: 'fill',
      prompt: 'We ___ (analyse) the data for two weeks and there is still no clear pattern.',
      answers: ['have been analysing', 'have been analyzing', 'have analysed', 'have analyzed'],
      hint: "The work is still going on as you speak.",
      explanation: "Present perfect continuous stresses the duration of an unfinished activity. The simple form is also correct but sounds more like a summing-up.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'ppps-023',
      type: 'fill',
      prompt: 'The euro ___ (fall) sharply against the dollar in 2022.',
      answers: ['fell'],
      explanation: "An explicit, finished date: past simple. Fall / fell / fallen.",
      errorTags: ['present-perfect-vs-past-simple', 'irregular-verb', 'time-adverbial'],
      level: 'B1',
    },
    {
      id: 'ppps-024',
      type: 'fill',
      prompt: 'I ___ (just / send) the email to the whole group.',
      answers: ['have just sent', "'ve just sent"],
      explanation: "Something that just happened, with an effect on now: present perfect. \"Just\" goes between auxiliary and participle.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'ppps-025',
      type: 'fill',
      prompt: 'They ___ (not / decide) yet whether to invest.',
      answers: ["haven't decided", 'have not decided'],
      explanation: "The decision is still pending, flagged by \"yet\": negative present perfect.",
      errorTags: ['present-perfect-vs-past-simple', 'negative-form'],
      level: 'B1',
    },
    {
      id: 'ppps-026',
      type: 'fill',
      prompt: 'When I was in London, I ___ (visit) the Bank of England.',
      answers: ['visited'],
      explanation: "The stay in London is over, so everything inside it takes the past simple.",
      errorTags: ['present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'ppps-027',
      type: 'fill',
      prompt: 'This is the first time I ___ (write) a report in English.',
      answers: ['have written', "'ve written"],
      hint: 'Dopo "it is the first time" l\'inglese non usa il presente.',
      explanation: "Fixed structure: \"It is the first / second / last time\" plus present perfect. Italian says \"\u00e8 la prima volta che scrivo\", which is why we get it wrong.",
      errorTags: ['present-perfect-vs-past-simple', 'irregular-verb'],
      level: 'B2',
    },
    {
      id: 'ppps-028',
      type: 'fill',
      prompt: 'The index ___ (rise) by three per cent since Monday.',
      answers: ['has risen'],
      explanation: "\"Since Monday\" opens a period running up to now: present perfect. Rise / rose / risen, a verb that comes up constantly in the ESP part of the exam.",
      errorTags: ['for-since', 'irregular-verb', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },
    {
      id: 'ppps-029',
      type: 'fill',
      prompt: "I ___ (lose) my student card, so I can't get into the library.",
      answers: ['have lost', "'ve lost"],
      explanation: "Present perfect of consequence: the action is past, the problem is now. Here English and Italian agree, so it comes easily.",
      errorTags: ['present-perfect-vs-past-simple', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'ppps-030',
      type: 'fill',
      prompt: 'He ___ (live) in Rome for five years, then he moved to Berlin.',
      answers: ['lived'],
      hint: "There is a \"for\", but look at how the sentence ends.",
      explanation: "A trap: \"for five years\" does not imply the present perfect. The Roman period is closed, since he moved away, so past simple. Context decides, not the adverb.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'B2',
    },

    // --- rewrite: dall'italiano all'inglese ---
    {
      id: 'ppps-031',
      type: 'rewrite',
      prompt: 'Studio statistica da due anni.',
      answers: [
        'I have been studying statistics for two years.',
        'I have studied statistics for two years.',
        "I've been studying statistics for two years.",
      ],
      explanation: "Italian present plus \"da\" becomes English present perfect plus \"for\". This is the swap to make automatic: if you catch yourself writing \"I study... for\", stop.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'ppps-032',
      type: 'rewrite',
      prompt: 'Non sono mai stato a Londra.',
      answers: ["I have never been to London.", "I've never been to London."],
      hint: "The verb is \"be\", not \"go\".",
      explanation: "\"Been to\" means you went and came back. \"Gone to\" would mean you are still there. With \"never\" the present perfect is compulsory: it is a life summary.",
      errorTags: ['been-vs-gone', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'ppps-033',
      type: 'rewrite',
      prompt: "Hai già finito l'esercizio?",
      answers: [
        'Have you finished the exercise yet?',
        'Have you already finished the exercise?',
      ],
      explanation: "Two versions, two shades: \"yet\" is the neutral question, \"already\" carries surprise. \"Yet\" goes at the end, \"already\" in the middle.",
      errorTags: ['present-perfect-vs-past-simple', 'question-form', 'time-adverbial'],
      level: 'B2',
    },
    {
      id: 'ppps-034',
      type: 'rewrite',
      prompt: 'Ho comprato questo portatile tre anni fa.',
      answers: ['I bought this laptop three years ago.'],
      explanation: "Italian compound past, English past simple: \"ago\" closes the time frame. The instinct to write \"I have bought\" is exactly what the examiner is looking for.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial', 'irregular-verb'],
      level: 'B1',
    },
    {
      id: 'ppps-035',
      type: 'rewrite',
      prompt: 'Il mercato è sceso del 2% questa settimana.',
      answers: [
        'The market has fallen by 2% this week.',
        'The market has dropped by 2% this week.',
      ],
      explanation: "\"This week\" is still open, since the week is not over, so present perfect. With \"last week\" you would need the past simple.",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial'],
      level: 'B2',
    },
    {
      id: 'ppps-036',
      type: 'rewrite',
      prompt: 'Quando hai iniziato il master?',
      answers: [
        "When did you start your master's?",
        "When did you start your master's degree?",
      ],
      explanation: "A question with \"when\" takes the past simple. Note the vocabulary too: \"master\" on its own is not the degree in English, you say \"a master's\".",
      errorTags: ['present-perfect-vs-past-simple', 'question-form', 'false-friend'],
      level: 'B1',
    },
    {
      id: 'ppps-037',
      type: 'rewrite',
      prompt: 'Lavoro qui da settembre.',
      answers: ['I have worked here since September.', "I've been working here since September."],
      explanation: "Italian present plus \"da\" plus a starting point becomes present perfect plus \"since\". Compare with the \"for\" card: since wants a date, for wants a duration.",
      errorTags: ['for-since', 'present-perfect-vs-past-simple'],
      level: 'B1',
    },
    {
      id: 'ppps-038',
      type: 'rewrite',
      prompt: 'Ieri ho parlato con il mio relatore.',
      answers: [
        'Yesterday I spoke to my supervisor.',
        'I spoke to my supervisor yesterday.',
        'I talked to my supervisor yesterday.',
      ],
      explanation: "\"Yesterday\" closes the time frame: past simple. Useful word: a thesis supervisor is a \"supervisor\", not a \"relator\".",
      errorTags: ['present-perfect-vs-past-simple', 'time-adverbial', 'false-friend'],
      level: 'B1',
    },
  ],
};
