import type { Deck } from '../types';

/**
 * Exam-style multiple choice over the whole verb system of the syllabus
 * (lessons 4-18): narrative tenses, future, modals, passive, conditionals,
 * gerunds and infinitives. Same format as the university mock exam.
 */
export const verbForms: Deck = {
  id: 'verb',
  title: 'The right verb form',
  description:
    'Multiple choice, exam style: narrative tenses, future forms, modals, the passive, conditionals, gerunds and infinitives.',
  syllabusUnits: [4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 17, 18],
  level: 'B2',
  cards: [
    // --- narrative tenses (4-6) ---
    {
      id: 'verb-001',
      type: 'choice',
      prompt: 'While I ___ my notes, the lecturer changed the slide.',
      answers: ['was reading', 'read', 'have read', 'had read'],
      options: ['was reading', 'read', 'have read', 'had read'],
      explanation: "Past continuous for the long action interrupted by a short one. Standard pattern: \"while\" plus past continuous, then past simple.",
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'verb-002',
      type: 'choice',
      prompt: 'When we arrived, the seminar ___ already ___.',
      answers: ['had / started', 'has / started', 'was / starting', 'did / start'],
      options: ['had / started', 'has / started', 'was / starting', 'did / start'],
      explanation: "Past perfect: something that happened before another past event. It is the Italian trapassato prossimo.",
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'verb-003',
      type: 'choice',
      prompt: 'I ___ take the bus to campus, but now I cycle.',
      answers: ['used to', 'was used to', 'use to', 'am used to'],
      options: ['used to', 'was used to', 'use to', 'am used to'],
      explanation: "\"Used to + infinitive\" is a past habit that is over. Do not confuse it with \"to be used to + -ing\", which means to be accustomed to something.",
      errorTags: ['narrative-tense'],
      level: 'B1',
    },
    {
      id: 'verb-004',
      type: 'choice',
      prompt: 'She ___ for three hours when the results finally came out.',
      answers: [
        'had been waiting',
        'was waiting',
        'has been waiting',
        'waited',
      ],
      options: ['had been waiting', 'was waiting', 'has been waiting', 'waited'],
      explanation: "Past perfect continuous: the duration of an activity up to a point in the past. \"For three hours\" plus a second past event calls for it.",
      errorTags: ['narrative-tense'],
      level: 'B2',
    },
    {
      id: 'verb-005',
      type: 'choice',
      prompt: 'The professor was explaining the model when the projector ___.',
      answers: ['broke down', 'was breaking down', 'had broken down', 'breaks down'],
      options: ['broke down', 'was breaking down', 'had broken down', 'breaks down'],
      explanation: "The short action that interrupts takes the past simple. Note the phrasal verb too: \"break down\" means to stop working.",
      errorTags: ['narrative-tense', 'phrasal-verb'],
      level: 'B1',
    },

    // --- future (7-9) ---
    {
      id: 'verb-006',
      type: 'choice',
      prompt: "Look at those clouds: it ___ rain.",
      answers: ['is going to', 'will', 'is raining', 'shall'],
      options: ['is going to', 'will', 'is raining', 'shall'],
      explanation: "\"Going to\" when there is present evidence of what is about to happen. \"Will\" is the prediction based on an opinion.",
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'verb-007',
      type: 'choice',
      prompt: "I ___ my supervisor at four, it's already in the diary.",
      answers: ['am meeting', 'will meet', 'meet', 'will be met'],
      options: ['am meeting', 'will meet', 'meet', 'will be met'],
      explanation: "Present continuous for arrangements already fixed. It is the most natural form for an organised future.",
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'verb-008',
      type: 'choice',
      prompt: "That bag looks heavy: I ___ you.",
      answers: ["'ll help", "'m going to help", 'help', "'m helping"],
      options: ["'ll help", "'m going to help", 'help', "'m helping"],
      explanation: "\"Will\" for a decision made on the spot. \"Going to\" would imply you had already thought about it.",
      errorTags: ['future-form'],
      level: 'B1',
    },
    {
      id: 'verb-009',
      type: 'choice',
      prompt: "I'll call you as soon as I ___ the email.",
      answers: ['get', 'will get', 'am getting', 'will have got'],
      options: ['get', 'will get', 'am getting', 'will have got'],
      explanation: "After \"when, as soon as, until, before, after\" the future is not used: put the present. Italian says \"appena ricever\u00f2\", which is where the mistake comes from.",
      errorTags: ['future-form'],
      level: 'B2',
    },
    {
      id: 'verb-010',
      type: 'choice',
      prompt: 'By the end of the year I ___ all the exams of the first term.',
      answers: ['will have passed', 'will pass', 'am passing', 'would pass'],
      options: ['will have passed', 'will pass', 'am passing', 'would pass'],
      explanation: "Future perfect: an action that will be complete by a future point. The signal is \"by\" plus a future time.",
      errorTags: ['future-form'],
      level: 'B2',
    },

    // --- modals (10-11) ---
    {
      id: 'verb-011',
      type: 'choice',
      prompt: "You ___ be tired: you've been studying since seven.",
      answers: ['must', 'can', 'should', 'might not'],
      options: ['must', 'can', 'should', 'might not'],
      explanation: "\"Must\" for a logical deduction when you are almost certain. The opposite is \"can't\": \"You can't be tired, you slept ten hours\".",
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'verb-012',
      type: 'choice',
      prompt: "You ___ have told me! I waited outside for an hour.",
      answers: ['could', 'can', 'must', 'should not'],
      options: ['could', 'can', 'must', 'should not'],
      explanation: "\"Could have + participle\" reproaches somebody for something that was possible and did not happen. \"Should have told me\" would also work in real life.",
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'verb-013',
      type: 'choice',
      prompt: "In the library you ___ eat: there is a sign at the entrance.",
      answers: ["mustn't", "don't have to", "shouldn't have to", 'may not have to'],
      options: ["mustn't", "don't have to", "shouldn't have to", 'may not have to'],
      explanation: "A classic trap: \"mustn't\" means it is forbidden, \"don't have to\" means it is not necessary. They are opposites, not synonyms.",
      errorTags: ['modal'],
      level: 'B2',
    },
    {
      id: 'verb-014',
      type: 'choice',
      prompt: "It ___ be the postman, but I'm not sure.",
      answers: ['might', 'must', "can't", 'will'],
      options: ['might', 'must', "can't", 'will'],
      explanation: "\"Might / may / could\" for uncertain possibility. \"Must\" would be near certainty.",
      errorTags: ['modal'],
      level: 'B1',
    },
    {
      id: 'verb-015',
      type: 'choice',
      prompt: "When I was eight I ___ swim quite well.",
      answers: ['could', 'can', 'was able', 'managed'],
      options: ['could', 'can', 'was able', 'managed'],
      explanation: "\"Could\" for a general ability in the past. For one specific success you use \"was able to\" or \"managed to\".",
      errorTags: ['modal'],
      level: 'B1',
    },

    // --- passive & reporting (13-14) ---
    {
      id: 'verb-016',
      type: 'choice',
      prompt: 'The results ___ next Monday.',
      answers: ['will be published', 'will publish', 'are publishing', 'will been published'],
      options: ['will be published', 'will publish', 'are publishing', 'will been published'],
      explanation: "Passive: who does it is not the point. Fixed structure: be plus past participle, with \"be\" carrying the tense of the sentence.",
      errorTags: ['passive'],
      level: 'B1',
    },
    {
      id: 'verb-017',
      type: 'choice',
      prompt: 'The data ___ by two different teams last year.',
      answers: ['were analysed', 'analysed', 'have analysed', 'was analysing'],
      options: ['were analysed', 'analysed', 'have analysed', 'was analysing'],
      explanation: "Passive in the past simple. In academic English \"data\" is technically plural (\"data were\"), though \"data was\" is common in speech.",
      errorTags: ['passive'],
      level: 'B2',
    },
    {
      id: 'verb-018',
      type: 'choice',
      prompt: 'He said he ___ the report the day before.',
      answers: ['had finished', 'has finished', 'finished', 'was finishing'],
      options: ['had finished', 'has finished', 'finished', 'was finishing'],
      explanation: "Reported speech: the present perfect becomes the past perfect, and \"yesterday\" becomes \"the day before\".",
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'verb-019',
      type: 'choice',
      prompt: 'She ___ me to check the figures again.',
      answers: ['asked', 'said', 'told to', 'said to me to'],
      options: ['asked', 'said', 'told to', 'said to me to'],
      explanation: "\"Ask / tell somebody TO do something\". \"Say\" never takes a person straight after it: you say something to me, you never \"say me\".",
      errorTags: ['reported-speech'],
      level: 'B2',
    },
    {
      id: 'verb-020',
      type: 'choice',
      prompt: 'The lecture ___ every Tuesday in room 12.',
      answers: ['is held', 'holds', 'is holding', 'has held'],
      options: ['is held', 'holds', 'is holding', 'has held'],
      explanation: "Passive in the present simple for a routine: be plus participle.",
      errorTags: ['passive'],
      level: 'B1',
    },

    // --- conditionals (15) ---
    {
      id: 'verb-021',
      type: 'choice',
      prompt: 'If I ___ more time, I would read the whole paper.',
      answers: ['had', 'have', 'would have', 'will have'],
      options: ['had', 'have', 'would have', 'will have'],
      explanation: "Second conditional, an unreal present situation: if plus past simple, then would plus infinitive. Never \"would\" inside the if.",
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'verb-022',
      type: 'choice',
      prompt: 'If you ___ the deadline, email the secretary.',
      answers: ['miss', 'will miss', 'missed', 'would miss'],
      options: ['miss', 'will miss', 'missed', 'would miss'],
      explanation: "First conditional: if plus present simple. The future never goes into the \"if\" half.",
      errorTags: ['conditional'],
      level: 'B1',
    },
    {
      id: 'verb-023',
      type: 'choice',
      prompt: 'If I had revised more, I ___ that question.',
      answers: ['would have answered', 'would answer', 'had answered', 'will have answered'],
      options: ['would have answered', 'would answer', 'had answered', 'will have answered'],
      explanation: "Third conditional, the regret: if plus past perfect, then would have plus participle. It is about a past you cannot change.",
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'verb-024',
      type: 'choice',
      prompt: 'I wish I ___ how to code in Python.',
      answers: ['knew', 'know', 'would know', 'have known'],
      options: ['knew', 'know', 'would know', 'have known'],
      explanation: "After \"I wish\", a wish about the present takes the past simple. Same unreal logic as the second conditional.",
      errorTags: ['conditional'],
      level: 'B2',
    },
    {
      id: 'verb-025',
      type: 'choice',
      prompt: "Unless we ___ now, we'll miss the train.",
      answers: ['leave', "don't leave", 'will leave', 'left'],
      options: ['leave', "don't leave", 'will leave', 'left'],
      explanation: "\"Unless\" already means \"if not\": adding a negative doubles it. And it is still a first conditional, so the present.",
      errorTags: ['conditional'],
      level: 'B2',
    },

    // --- gerunds & infinitives (17-18) ---
    {
      id: 'verb-026',
      type: 'choice',
      prompt: 'I look forward to ___ from you.',
      answers: ['hearing', 'hear', 'be hearing', 'have heard'],
      options: ['hearing', 'hear', 'be hearing', 'have heard'],
      explanation: "Here \"to\" is a preposition, not an infinitive, so it takes the -ing form. It is the standard closing line of a formal email.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'verb-027',
      type: 'choice',
      prompt: 'They decided ___ the project until September.',
      answers: ['to postpone', 'postponing', 'postpone', 'for postponing'],
      options: ['to postpone', 'postponing', 'postpone', 'for postponing'],
      explanation: "\"Decide\" takes the infinitive with \"to\". Same family: agree, hope, manage, refuse, promise.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'verb-028',
      type: 'choice',
      prompt: "I don't mind ___ early when I have a lecture at nine.",
      answers: ['getting up', 'to get up', 'get up', 'to getting up'],
      options: ['getting up', 'to get up', 'get up', 'to getting up'],
      explanation: "\"Mind\" takes the gerund. Same family: enjoy, avoid, suggest, finish, keep, consider.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B1',
    },
    {
      id: 'verb-029',
      type: 'choice',
      prompt: 'Remember ___ the attachment before you send it.',
      answers: ['to check', 'checking', 'check', 'of checking'],
      options: ['to check', 'checking', 'check', 'of checking'],
      explanation: "\"Remember to do\" means do not forget to do it. \"Remember doing\" means you recall having done it. The meaning changes, not just the form.",
      errorTags: ['gerund-vs-infinitive'],
      level: 'B2',
    },
    {
      id: 'verb-030',
      type: 'choice',
      prompt: "He's good at ___ complex ideas simply.",
      answers: ['explaining', 'explain', 'to explain', 'explained'],
      options: ['explaining', 'explain', 'to explain', 'explained'],
      explanation: "After a preposition (\"at, of, in, about, for\") the verb always takes -ing.",
      errorTags: ['gerund-vs-infinitive', 'preposition'],
      level: 'B1',
    },
  ],
};
